import type { OTBookContext } from "../context-types";

export const CONTEXT_1CH_TO_NEH: OTBookContext[] = [
  {
    id: "1CH",
    name: "1 Chronicles",
    overview: {
      shortSummary: "Genealogies from Adam to David, then David's reign retold with temple focus.",
      fullSummary: "1 Chronicles opens with sweeping genealogies, then focuses on David's reign — especially his preparations for temple worship. Written for post-exilic Jews to reconnect with their heritage and the centrality of worship.",
      themes: ["God's faithfulness to David", "Temple worship", "Continuity of the covenant people", "Heritage and identity"],
      keyMessages: ["God's promises outlast empires", "Worship is the center of life", "The Davidic line endures"],
    },
    author: { traditional: "Ezra (tradition)", notes: "Anonymous; post-exilic priestly author." },
    timePeriod: {
      eventsDate: "Adam to c.970 BC",
      writingDate: "c.450-400 BC",
      biblicalPlacement: "Writings (Hebrew canon); History (English canon)",
      relationToEvents: "Retrospective compilation for post-exilic community",
    },
    historicalSetting: {
      rulers: ["David (main focus)"],
      israelKings: ["David"],
      neighboringPowers: ["Post-exile: Persian empire (context of writing)"],
      politicalBackground: "Written to post-exilic Jews under Persian rule, emphasizing David and temple.",
    },
    mapLocations: [
      { name: "Hebron", type: "city", description: "David's first capital", svgX: 158, svgY: 170 },
      { name: "Jerusalem", type: "city", description: "City of David, future temple site", svgX: 160, svgY: 165 },
      { name: "Threshing floor of Ornan", type: "city", description: "Future temple site purchased", svgX: 160, svgY: 165 },
    ],
    genealogy: {
      description: "Exhaustive genealogies establish Israel's identity.",
      nodes: [
        { id: "adam", name: "Adam" },
        { id: "noah", name: "Noah", parentId: "adam" },
        { id: "abraham", name: "Abraham", parentId: "noah" },
        { id: "jacob", name: "Jacob", parentId: "abraham" },
        { id: "judah", name: "Judah", parentId: "jacob" },
        { id: "david", name: "David", parentId: "judah" },
        { id: "solomon", name: "Solomon", parentId: "david" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Genealogies Adam to Israel", description: "Cosmic sweep from creation to exile", reference: "1 Chronicles 1-9" },
      { order: 2, title: "David made king", description: "Anointed over all Israel", reference: "1 Chronicles 11" },
      { order: 3, title: "Ark brought to Jerusalem", description: "Proper procedure after initial error", reference: "1 Chronicles 13-16" },
      { order: 4, title: "Davidic covenant", description: "Eternal dynasty promised", reference: "1 Chronicles 17" },
      { order: 5, title: "David's census and plague", description: "Threshing floor marked for temple", reference: "1 Chronicles 21" },
      { order: 6, title: "Preparations for the temple", description: "David organizes Levites, collects materials", reference: "1 Chronicles 22-29" },
    ],
    culturalNotes: [
      { category: "worship", title: "Levitical divisions", content: "David organized 24 courses of priests and Levites for temple service." },
      { category: "social", title: "Genealogical identity", content: "Post-exilic Jews needed proof of tribal/priestly lineage to serve." },
      { category: "customs", title: "Singers and musicians", content: "Temple music was a formal, covenantal institution." },
      { category: "law", title: "Proper ark transport", content: "Priests must carry the ark on poles; no cart (Uzzah's error)." },
    ],
    didYouKnow: [
      "Chronicles is titled \"Events of the Days\" in Hebrew.",
      "The book almost entirely omits David's sins — focus is on God's unchanging purposes.",
      "Chronicles is the final book of the Hebrew Bible (not Malachi).",
      "Jesus alludes to this placement when He mentions \"the blood of Zechariah\" (Matt 23:35).",
    ],
  },
  {
    id: "2CH",
    name: "2 Chronicles",
    overview: {
      shortSummary: "Solomon's temple and the southern kingdom of Judah through the exile.",
      fullSummary: "2 Chronicles continues from David to the fall of Jerusalem, focusing almost exclusively on Judah and the temple. It ends with Cyrus's decree allowing the Jews to return home.",
      themes: ["Temple centrality", "Reform and revival", "Covenant faithfulness", "Hope beyond exile"],
      keyMessages: ["If My people will humble themselves...", "Judgment is real but not final", "God rules history"],
    },
    author: { traditional: "Ezra (tradition)", notes: "Same author as 1 Chronicles." },
    timePeriod: {
      eventsDate: "c.970-538 BC",
      writingDate: "c.450-400 BC",
      biblicalPlacement: "Final book of the Hebrew canon",
      relationToEvents: "Post-exilic retrospection",
    },
    historicalSetting: {
      rulers: ["Solomon", "Rehoboam", "Jehoshaphat", "Hezekiah", "Josiah", "Cyrus"],
      israelKings: ["Southern kings only"],
      neighboringPowers: ["Egypt", "Assyria", "Babylon", "Persia"],
      politicalBackground: "Follows southern kingdom's trajectory through reforms and decline to exile and Cyrus's decree.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Temple built, destroyed, rebuilt", svgX: 160, svgY: 165 },
      { name: "Mount Moriah", type: "city", description: "Temple location", svgX: 160, svgY: 165 },
      { name: "En-gedi / Ziz", type: "battle", description: "Jehoshaphat's miraculous victory", svgX: 165, svgY: 170 },
      { name: "Babylon", type: "exile", description: "70-year exile destination", svgX: 272, svgY: 178 },
      { name: "Persia", type: "region", description: "Cyrus's empire; decree to return", svgX: 310, svgY: 170 },
    ],
    genealogy: {
      description: "Davidic line through the exile.",
      nodes: [
        { id: "solomon", name: "Solomon" },
        { id: "rehoboam", name: "Rehoboam", parentId: "solomon" },
        { id: "jehoshaphat", name: "Jehoshaphat", parentId: "rehoboam" },
        { id: "hezekiah", name: "Hezekiah" },
        { id: "manasseh", name: "Manasseh", parentId: "hezekiah" },
        { id: "josiah", name: "Josiah", parentId: "manasseh" },
        { id: "zedekiah", name: "Zedekiah", parentId: "josiah" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Temple built and dedicated", description: "Glory cloud fills the house", reference: "2 Chronicles 3-7" },
      { order: 2, title: "\"If my people\" promise", description: "Conditional covenant of restoration", reference: "2 Chronicles 7:14" },
      { order: 3, title: "Jehoshaphat's prayer", description: "Victory through worship", reference: "2 Chronicles 20" },
      { order: 4, title: "Hezekiah's Passover", description: "Revival and deliverance from Assyria", reference: "2 Chronicles 29-32" },
      { order: 5, title: "Josiah finds the Law", description: "National reform follows", reference: "2 Chronicles 34-35" },
      { order: 6, title: "Fall of Jerusalem", description: "Temple destroyed, people exiled", reference: "2 Chronicles 36" },
      { order: 7, title: "Cyrus's decree", description: "Return authorized; ends with hope", reference: "2 Chronicles 36:22-23" },
    ],
    culturalNotes: [
      { category: "worship", title: "Annual Passover", content: "Major reforms centered on reinstating Passover." },
      { category: "social", title: "Good and evil kings alternate", content: "Judah experienced cycles of reform and apostasy." },
      { category: "customs", title: "Prophet confrontations", content: "Micaiah, Isaiah, Jeremiah challenged kings throughout." },
      { category: "law", title: "Sabbath rests of the land", content: "70 years of exile matched missed sabbatical years (Lev 26:34-35)." },
    ],
    didYouKnow: [
      "2 Chronicles 7:14 is one of the most quoted promises in the Bible.",
      "Manasseh repented after being taken captive to Babylon.",
      "The temple was destroyed in 586 BC on the 9th of Av — same date as the second temple in AD 70.",
      "Cyrus's decree fulfilled Jeremiah's 70-year prophecy.",
    ],
  },
  {
    id: "EZR",
    name: "Ezra",
    overview: {
      shortSummary: "Return from exile and rebuilding of the temple under Zerubbabel and Ezra.",
      fullSummary: "Ezra narrates two returns from Babylon — the first under Zerubbabel to rebuild the temple (538 BC), the second under Ezra the scribe (458 BC) to restore the Law. Emphasizes God's providence through Persian kings.",
      themes: ["Return and restoration", "Temple rebuilding", "Covenant renewal", "God's sovereignty over nations"],
      keyMessages: ["God stirs up kings' hearts", "The Word must come back to the center", "Holiness requires separation"],
    },
    author: { traditional: "Ezra", notes: "First-person sections support Ezra's authorship." },
    timePeriod: {
      eventsDate: "c.538-458 BC",
      writingDate: "c.457-440 BC",
      biblicalPlacement: "Part of Ezra-Nehemiah in Hebrew canon",
      relationToEvents: "Ezra wrote about events he helped lead",
    },
    historicalSetting: {
      rulers: ["Cyrus", "Darius", "Artaxerxes", "Zerubbabel", "Ezra"],
      israelKings: [],
      neighboringPowers: ["Persia (ruling empire)", "Samaritans (local opposition)"],
      politicalBackground: "Persia's tolerant policy allowed subject peoples to return and worship in their own ways.",
    },
    mapLocations: [
      { name: "Babylon", type: "exile", description: "Starting point of return", svgX: 272, svgY: 178 },
      { name: "Jerusalem", type: "city", description: "Temple rebuilt", svgX: 160, svgY: 165 },
      { name: "Susa", type: "city", description: "Persian capital", svgX: 298, svgY: 173 },
      { name: "Ahava Canal", type: "region", description: "Ezra's fast before journey", svgX: 265, svgY: 170 },
    ],
    genealogy: {
      description: "Leaders of the returns.",
      nodes: [
        { id: "zerubbabel", name: "Zerubbabel", notes: "Governor, Davidic descendant" },
        { id: "jeshua", name: "Jeshua (Joshua)", notes: "High priest" },
        { id: "ezra", name: "Ezra", notes: "Priest and scribe" },
        { id: "haggai", name: "Haggai", notes: "Prophet supporting rebuilding" },
        { id: "zechariah", name: "Zechariah", notes: "Prophet supporting rebuilding" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Cyrus's decree", description: "Persian king authorizes return", reference: "Ezra 1" },
      { order: 2, title: "First return under Zerubbabel", description: "~50,000 return", reference: "Ezra 2" },
      { order: 3, title: "Altar and foundation laid", description: "Joy mingled with weeping of elders", reference: "Ezra 3" },
      { order: 4, title: "Opposition halts work", description: "Samaritans and local officials interfere", reference: "Ezra 4" },
      { order: 5, title: "Haggai and Zechariah prophesy", description: "Work resumes; temple finished 516 BC", reference: "Ezra 5-6" },
      { order: 6, title: "Ezra's return", description: "Arrives with scribes and teachers", reference: "Ezra 7-8" },
      { order: 7, title: "Mixed marriages reform", description: "Painful separation of foreign wives", reference: "Ezra 9-10" },
    ],
    culturalNotes: [
      { category: "worship", title: "Second Temple", content: "Smaller than Solomon's but stood until AD 70 (after Herod's expansion)." },
      { category: "social", title: "Samaritan conflict", content: "Ezra-Nehemiah explains centuries of Jewish-Samaritan hostility." },
      { category: "customs", title: "Public reading of Scripture", content: "Return of the Law to center of community life." },
      { category: "law", title: "Prohibition of mixed marriage", content: "Concern was religious, not ethnic — to prevent idolatry." },
    ],
    didYouKnow: [
      "Ezra was contemporary with Socrates and the flowering of Greek philosophy.",
      "Parts of Ezra are written in Aramaic, the imperial language.",
      "The Second Temple lacked the Ark of the Covenant.",
      "Ezra's return took about 4 months traveling ~900 miles.",
    ],
  },
  {
    id: "NEH",
    name: "Nehemiah",
    overview: {
      shortSummary: "Nehemiah rebuilds Jerusalem's walls and leads covenant renewal.",
      fullSummary: "Nehemiah, cupbearer to King Artaxerxes, returns to Jerusalem as governor to rebuild the walls despite fierce opposition. He and Ezra lead a massive covenant renewal. Book closes with reforms against renewed apostasy.",
      themes: ["Leadership under opposition", "Prayer and planning", "Community and covenant", "Reform and restoration"],
      keyMessages: ["Pray and work", "Unity completes great tasks", "Reform requires constant vigilance"],
    },
    author: { traditional: "Nehemiah (memoirs) with Ezra's compilation", notes: "Large first-person sections." },
    timePeriod: {
      eventsDate: "c.445-430 BC",
      writingDate: "c.430-400 BC",
      biblicalPlacement: "Paired with Ezra in Hebrew canon",
      relationToEvents: "Written by participant",
    },
    historicalSetting: {
      rulers: ["Artaxerxes I", "Nehemiah (governor)", "Ezra (scribe)"],
      israelKings: [],
      neighboringPowers: ["Sanballat the Horonite", "Tobiah the Ammonite", "Geshem the Arab"],
      politicalBackground: "Despite Persian protection, local powers opposed Jewish resurgence.",
    },
    mapLocations: [
      { name: "Susa", type: "city", description: "Nehemiah's starting post as cupbearer", svgX: 298, svgY: 173 },
      { name: "Jerusalem", type: "city", description: "Walls rebuilt in 52 days", svgX: 160, svgY: 165 },
      { name: "Water Gate", type: "city", description: "Ezra reads the Law", svgX: 160, svgY: 165 },
      { name: "Valley gate", type: "city", description: "Nehemiah's night inspection", svgX: 160, svgY: 165 },
    ],
    genealogy: {
      description: "Key figures of reform.",
      nodes: [
        { id: "nehemiah", name: "Nehemiah", notes: "Cupbearer, then governor" },
        { id: "ezra", name: "Ezra", notes: "Priest and scribe" },
        { id: "eliashib", name: "Eliashib", notes: "High priest" },
        { id: "sanballat", name: "Sanballat", notes: "Chief opponent" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Nehemiah's prayer and request", description: "Artaxerxes grants leave", reference: "Nehemiah 1-2" },
      { order: 2, title: "Night inspection of walls", description: "Quiet survey before announcing plans", reference: "Nehemiah 2:11-16" },
      { order: 3, title: "Rebuilding begins", description: "Each family assigned a section", reference: "Nehemiah 3" },
      { order: 4, title: "Opposition and threats", description: "Trowel in one hand, sword in the other", reference: "Nehemiah 4" },
      { order: 5, title: "Walls finished in 52 days", description: "Enemies lose heart", reference: "Nehemiah 6:15" },
      { order: 6, title: "Ezra reads the Law", description: "People weep, then rejoice", reference: "Nehemiah 8" },
      { order: 7, title: "Covenant renewal", description: "Sealed commitment to obey", reference: "Nehemiah 9-10" },
      { order: 8, title: "Final reforms", description: "Sabbath, tithes, mixed marriages addressed", reference: "Nehemiah 13" },
    ],
    culturalNotes: [
      { category: "social", title: "Cupbearer", content: "A trusted court position; the king's taste-tester and confidant." },
      { category: "customs", title: "Feast of Booths", content: "Celebrated after reading the Law; remembered wilderness wanderings." },
      { category: "law", title: "Sabbath enforcement", content: "Foreign merchants locked out on Sabbath." },
      { category: "geography", title: "Jerusalem's walls", content: "Nehemiah's walls followed roughly the lines of David's city, not the expanded Solomonic or Herodian walls." },
    ],
    didYouKnow: [
      "Nehemiah closes the historical narrative of the Old Testament.",
      "After Malachi, ~400 years of prophetic silence followed.",
      "Nehemiah's prayers punctuate almost every chapter.",
      "The walls were completed so quickly that enemies attributed it to God.",
    ],
  },
];
