import type { OTBookContext } from "../context-types";

export const CONTEXT_1SA_TO_2KI: OTBookContext[] = [
  {
    id: "1SA",
    name: "1 Samuel",
    overview: {
      shortSummary: "Transition from judges to monarchy; Samuel, Saul, and the rise of David.",
      fullSummary: "1 Samuel chronicles Israel's move from tribal confederacy to monarchy. Samuel the last judge anoints Saul, Israel's first king, who fails. David is secretly anointed and pursued by a jealous Saul until Saul dies on Mount Gilboa.",
      themes: ["Kingship under God", "Obedience over sacrifice", "God chooses the heart", "Faithfulness in adversity"],
      keyMessages: ["The LORD looks at the heart", "To obey is better than sacrifice", "God raises up and tears down kings"],
    },
    author: { traditional: "Samuel, Nathan, and Gad (tradition)", notes: "Compilation of prophetic records." },
    timePeriod: {
      eventsDate: "c.1100-1010 BC",
      writingDate: "c.930 BC",
      biblicalPlacement: "Former Prophets; origin of the monarchy",
      relationToEvents: "Compiled from contemporary prophetic sources",
    },
    historicalSetting: {
      rulers: ["Samuel (judge/prophet)", "Saul (first king)"],
      israelKings: ["Saul (c.1050-1010 BC)"],
      neighboringPowers: ["Philistines", "Ammonites", "Amalekites"],
      politicalBackground: "Philistine pressure drove Israel to demand a king \"like the other nations.\"",
    },
    mapLocations: [
      { name: "Shiloh", type: "city", description: "Tabernacle; Eli and young Samuel", svgX: 162, svgY: 155 },
      { name: "Ramah", type: "city", description: "Samuel's hometown and burial", svgX: 160, svgY: 160 },
      { name: "Gibeah", type: "city", description: "Saul's capital", svgX: 162, svgY: 163 },
      { name: "Bethlehem", type: "city", description: "David's hometown", svgX: 160, svgY: 167 },
      { name: "Valley of Elah", type: "battle", description: "David vs. Goliath", svgX: 153, svgY: 168 },
      { name: "Ein Gedi", type: "city", description: "David's wilderness refuge", svgX: 165, svgY: 172 },
      { name: "Mount Gilboa", type: "battle", description: "Saul's death", svgX: 165, svgY: 150 },
      { name: "Endor", type: "city", description: "Saul consults medium", svgX: 162, svgY: 148 },
    ],
    genealogy: {
      description: "Key figures in the transition to monarchy.",
      nodes: [
        { id: "eli", name: "Eli", notes: "High priest" },
        { id: "samuel", name: "Samuel", notes: "Prophet, priest, judge" },
        { id: "kish", name: "Kish", notes: "Father of Saul" },
        { id: "saul", name: "Saul", parentId: "kish", notes: "First king" },
        { id: "jonathan", name: "Jonathan", parentId: "saul", notes: "Prince and David's friend" },
        { id: "jesse", name: "Jesse" },
        { id: "david", name: "David", parentId: "jesse", notes: "Shepherd, anointed king" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Samuel's birth and call", description: "Hannah's prayer answered; God calls young Samuel", reference: "1 Samuel 1-3" },
      { order: 2, title: "Ark captured and returned", description: "Philistines take and return the ark", reference: "1 Samuel 4-6" },
      { order: 3, title: "Saul anointed king", description: "First king chosen under prophetic protest", reference: "1 Samuel 8-10" },
      { order: 4, title: "Saul's disobedience", description: "Unlawful sacrifice and sparing Agag", reference: "1 Samuel 13, 15" },
      { order: 5, title: "David anointed", description: "Samuel secretly anoints the shepherd boy", reference: "1 Samuel 16" },
      { order: 6, title: "David and Goliath", description: "Young David defeats the Philistine champion", reference: "1 Samuel 17" },
      { order: 7, title: "David flees Saul", description: "Years as fugitive; spares Saul twice", reference: "1 Samuel 19-26" },
      { order: 8, title: "Saul's death at Gilboa", description: "Saul and Jonathan die in battle", reference: "1 Samuel 31" },
    ],
    culturalNotes: [
      { category: "worship", title: "Tabernacle at Shiloh", content: "Central worship until the ark was captured." },
      { category: "social", title: "Kingship demanded", content: "Israel's demand for a king was seen as rejection of God's rule." },
      { category: "customs", title: "Anointing with oil", content: "Public consecration ritual for kings, priests, prophets." },
      { category: "law", title: "Holy war and herem", content: "Saul's failure to fully destroy Amalek cost him the kingdom." },
    ],
    didYouKnow: [
      "Samuel served as judge, prophet, and priest — all three offices.",
      "Saul was a head taller than any other Israelite.",
      "David played the harp to soothe Saul's troubled spirit.",
      "The covenant between David and Jonathan is a model of godly friendship.",
    ],
  },
  {
    id: "2SA",
    name: "2 Samuel",
    overview: {
      shortSummary: "David's reign — his triumphs, his sin with Bathsheba, and the fracturing of his house.",
      fullSummary: "2 Samuel narrates David's rise to kingship over all Israel, his establishment of Jerusalem, the Davidic covenant, and the devastating consequences of his sin with Bathsheba — including Absalom's rebellion.",
      themes: ["Davidic covenant", "Kingship and worship", "Sin and consequences", "Forgiveness and restoration"],
      keyMessages: ["God's promises to David endure", "Sin has public consequences", "God disciplines those He loves"],
    },
    author: { traditional: "Nathan and Gad (tradition)", notes: "Prophetic compilation." },
    timePeriod: {
      eventsDate: "c.1010-970 BC",
      writingDate: "c.930 BC",
      biblicalPlacement: "Former Prophets",
      relationToEvents: "Written shortly after David's reign",
    },
    historicalSetting: {
      rulers: ["David"],
      israelKings: ["David (c.1010-970 BC)"],
      neighboringPowers: ["Philistines", "Moab", "Ammon", "Edom", "Aram"],
      politicalBackground: "David unified the tribes, subdued surrounding peoples, and built an empire from the Euphrates to Egypt's border.",
    },
    mapLocations: [
      { name: "Hebron", type: "city", description: "David's first capital (7 years)", svgX: 158, svgY: 170 },
      { name: "Jerusalem", type: "city", description: "Captured from Jebusites; new capital", svgX: 160, svgY: 165 },
      { name: "Rabbah", type: "battle", description: "Ammonite capital; siege scene", svgX: 172, svgY: 162 },
      { name: "Valley of Rephaim", type: "battle", description: "David defeats Philistines", svgX: 158, svgY: 166 },
      { name: "Mahanaim", type: "city", description: "David's refuge during Absalom's revolt", svgX: 172, svgY: 160 },
      { name: "Forest of Ephraim", type: "battle", description: "Absalom killed", svgX: 168, svgY: 158 },
    ],
    genealogy: {
      description: "David's extensive family, crucial for messianic lineage.",
      nodes: [
        { id: "david", name: "David" },
        { id: "bathsheba", name: "Bathsheba" },
        { id: "amnon", name: "Amnon", parentId: "david" },
        { id: "absalom", name: "Absalom", parentId: "david", notes: "Rebelled against father" },
        { id: "adonijah", name: "Adonijah", parentId: "david" },
        { id: "solomon", name: "Solomon", parentId: "david", notes: "Son of Bathsheba, heir" },
      ],
    },
    keyEvents: [
      { order: 1, title: "David anointed over all Israel", description: "After 7 years in Hebron, united monarchy", reference: "2 Samuel 5:1-5" },
      { order: 2, title: "Jerusalem captured", description: "City of David established", reference: "2 Samuel 5:6-10" },
      { order: 3, title: "Ark brought to Jerusalem", description: "David dances; Uzzah struck down", reference: "2 Samuel 6" },
      { order: 4, title: "Davidic covenant", description: "God promises David an eternal dynasty", reference: "2 Samuel 7" },
      { order: 5, title: "David and Bathsheba", description: "Adultery, murder, and Nathan's rebuke", reference: "2 Samuel 11-12" },
      { order: 6, title: "Absalom's rebellion", description: "Absalom steals hearts; David flees; Absalom dies", reference: "2 Samuel 15-18" },
      { order: 7, title: "Census and plague", description: "David's pride brings plague; altar at threshing floor", reference: "2 Samuel 24" },
    ],
    culturalNotes: [
      { category: "worship", title: "Ark in Jerusalem", content: "David made Jerusalem the religious and political center." },
      { category: "customs", title: "Royal court prophets", content: "Nathan and Gad served as court prophets." },
      { category: "law", title: "Kinsman avenger restricted", content: "David protected Mephibosheth from tribal blood revenge." },
      { category: "social", title: "Polygamy", content: "Kings took multiple wives for alliance — the Bible shows the chaos this produced." },
    ],
    didYouKnow: [
      "The Davidic covenant (2 Sam 7) underlies all New Testament Messianic expectation.",
      "David wrote Psalm 51 after Nathan's rebuke.",
      "Absalom was killed while hanging from an oak tree by his famous hair.",
      "The temple site was purchased by David from Araunah the Jebusite.",
    ],
  },
  {
    id: "1KI",
    name: "1 Kings",
    overview: {
      shortSummary: "Solomon's glory, the temple, the division of the kingdom, and Elijah vs. Ahab.",
      fullSummary: "1 Kings covers Solomon's golden reign, the building and dedication of the temple, the kingdom's division under Rehoboam and Jeroboam, and the ministry of Elijah against Ahab and Jezebel.",
      themes: ["Wisdom and folly", "Temple worship", "Covenant unfaithfulness", "Prophetic confrontation"],
      keyMessages: ["Partial obedience is disobedience", "Idolatry destroys nations", "God preserves a remnant"],
    },
    author: { traditional: "Jeremiah (tradition)", notes: "Anonymous compilation from royal and prophetic records." },
    timePeriod: {
      eventsDate: "c.970-850 BC",
      writingDate: "c.560 BC (final form)",
      biblicalPlacement: "Former Prophets",
      relationToEvents: "Final form compiled during/after exile",
    },
    historicalSetting: {
      rulers: ["Solomon", "Rehoboam", "Jeroboam I", "Ahab", "Jezebel"],
      israelKings: ["Solomon (970-930)", "Rehoboam (Judah)", "Jeroboam I through Ahab (Israel)"],
      neighboringPowers: ["Egypt", "Phoenicia/Tyre", "Aram (Syria)", "Moab"],
      politicalBackground: "Solomon's empire peaked then fractured into Israel (north, 10 tribes) and Judah (south, 2 tribes).",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Temple built; Judah's capital", svgX: 160, svgY: 165 },
      { name: "Gibeon", type: "city", description: "Solomon's dream of wisdom", svgX: 158, svgY: 162 },
      { name: "Samaria", type: "city", description: "Later northern capital built by Omri", svgX: 158, svgY: 152 },
      { name: "Mount Carmel", type: "battle", description: "Elijah vs. prophets of Baal", svgX: 152, svgY: 147 },
      { name: "Zarephath", type: "city", description: "Elijah and the widow", svgX: 150, svgY: 142 },
      { name: "Tyre", type: "city", description: "Hiram's kingdom; supplied cedar", svgX: 153, svgY: 140 },
      { name: "Horeb (Sinai)", type: "city", description: "Elijah's flight", svgX: 150, svgY: 210 },
    ],
    genealogy: {
      description: "Division of David's kingdom.",
      nodes: [
        { id: "david", name: "David" },
        { id: "solomon", name: "Solomon", parentId: "david" },
        { id: "rehoboam", name: "Rehoboam", parentId: "solomon", notes: "King of Judah" },
        { id: "jeroboam", name: "Jeroboam I", notes: "King of Israel (north)" },
        { id: "omri", name: "Omri", notes: "Built Samaria" },
        { id: "ahab", name: "Ahab", parentId: "omri", notes: "Married Jezebel" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Solomon's request for wisdom", description: "God grants wisdom, riches, honor", reference: "1 Kings 3" },
      { order: 2, title: "Temple built and dedicated", description: "Seven years of construction; glory fills house", reference: "1 Kings 6-8" },
      { order: 3, title: "Queen of Sheba visits", description: "Fame of Solomon reaches far", reference: "1 Kings 10" },
      { order: 4, title: "Solomon's apostasy", description: "Foreign wives lead him to idolatry", reference: "1 Kings 11" },
      { order: 5, title: "Kingdom divided", description: "Rehoboam's folly splits Israel and Judah", reference: "1 Kings 12" },
      { order: 6, title: "Elijah and the drought", description: "Three-year famine announced", reference: "1 Kings 17" },
      { order: 7, title: "Mount Carmel showdown", description: "Fire from heaven; Baal prophets slain", reference: "1 Kings 18" },
      { order: 8, title: "Still small voice", description: "Elijah meets God at Horeb", reference: "1 Kings 19" },
    ],
    culturalNotes: [
      { category: "worship", title: "First Temple", content: "Built with cedar from Lebanon and overlaid with gold; stood ~380 years." },
      { category: "social", title: "Forced labor", content: "Solomon's building projects used corvée labor from non-Israelites and Israelites." },
      { category: "worship", title: "Golden calves at Dan and Bethel", content: "Jeroboam set up rival worship to keep subjects from Jerusalem." },
      { category: "law", title: "Marriage alliances", content: "Royal marriages imported foreign religions and bred apostasy." },
    ],
    didYouKnow: [
      "Solomon had 700 wives and 300 concubines.",
      "The temple's Most Holy Place was a 30-ft cube of gold.",
      "Elijah never died — he was taken up in a whirlwind.",
      "Jezebel was a Phoenician princess from Sidon.",
    ],
  },
  {
    id: "2KI",
    name: "2 Kings",
    overview: {
      shortSummary: "Decline of Israel and Judah; Elisha's ministry; exile to Assyria and Babylon.",
      fullSummary: "2 Kings traces the continuing apostasy of Israel and Judah through prophetic ministries of Elisha and others. Israel falls to Assyria in 722 BC; Judah falls to Babylon in 586 BC.",
      themes: ["Prophetic witness", "Divine judgment", "Remnant preserved", "Apostasy's cost"],
      keyMessages: ["God is patient but not lenient forever", "Idolatry brings exile", "The remnant survives"],
    },
    author: { traditional: "Jeremiah (tradition)", notes: "Anonymous; completed during exile." },
    timePeriod: {
      eventsDate: "c.850-560 BC",
      writingDate: "c.560 BC",
      biblicalPlacement: "Former Prophets; completion of Samuel-Kings history",
      relationToEvents: "Written during Babylonian exile",
    },
    historicalSetting: {
      rulers: ["Elisha", "Jehu", "Hezekiah", "Josiah", "Nebuchadnezzar"],
      israelKings: ["All northern kings to Hoshea (fall 722 BC)", "All southern kings to Zedekiah (fall 586 BC)"],
      neighboringPowers: ["Assyria", "Babylon", "Egypt", "Aram", "Moab"],
      politicalBackground: "Rising Assyrian empire crushed Israel; Babylon then replaced Assyria and destroyed Judah.",
    },
    mapLocations: [
      { name: "Samaria", type: "city", description: "Northern capital; fell to Assyria 722 BC", svgX: 158, svgY: 152 },
      { name: "Jerusalem", type: "city", description: "Southern capital; fell to Babylon 586 BC", svgX: 160, svgY: 165 },
      { name: "Nineveh", type: "city", description: "Assyrian capital", svgX: 248, svgY: 128 },
      { name: "Babylon", type: "city", description: "Destination of Judah's exile", svgX: 272, svgY: 178 },
      { name: "Jordan River", type: "region", description: "Naaman dipped 7 times", svgX: 165, svgY: 155 },
      { name: "Dothan", type: "city", description: "Elisha and chariots of fire", svgX: 158, svgY: 150 },
      { name: "Carchemish", type: "battle", description: "Babylon defeats Egypt 605 BC", svgX: 210, svgY: 118 },
    ],
    genealogy: {
      description: "Kings of divided monarchy.",
      nodes: [
        { id: "elisha", name: "Elisha", notes: "Successor to Elijah" },
        { id: "jehu", name: "Jehu", notes: "Destroyed house of Ahab" },
        { id: "hezekiah", name: "Hezekiah", notes: "Reformer king of Judah" },
        { id: "josiah", name: "Josiah", notes: "Last great reformer" },
        { id: "zedekiah", name: "Zedekiah", notes: "Last king of Judah" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Elijah taken up", description: "Chariot of fire; Elisha receives double portion", reference: "2 Kings 2" },
      { order: 2, title: "Naaman healed", description: "Syrian commander cleansed of leprosy", reference: "2 Kings 5" },
      { order: 3, title: "Jehu's purge", description: "House of Ahab destroyed; Jezebel killed", reference: "2 Kings 9-10" },
      { order: 4, title: "Fall of Samaria", description: "Assyria deports northern Israel (722 BC)", reference: "2 Kings 17" },
      { order: 5, title: "Hezekiah's deliverance", description: "Angel kills 185,000 Assyrians", reference: "2 Kings 19" },
      { order: 6, title: "Josiah's reforms", description: "Book of the Law found in temple", reference: "2 Kings 22-23" },
      { order: 7, title: "Fall of Jerusalem", description: "Babylon destroys city and temple (586 BC)", reference: "2 Kings 25" },
    ],
    culturalNotes: [
      { category: "social", title: "Assyrian deportation", content: "Assyria's policy was to exile populations and resettle them to prevent rebellion." },
      { category: "social", title: "Samaritans", content: "Mixed population resettled in Samaria after 722 BC became the Samaritans of NT times." },
      { category: "worship", title: "Passover restored", content: "Josiah's Passover was the greatest since the days of the judges." },
      { category: "customs", title: "Prophetic schools", content: "Elisha oversaw \"sons of the prophets\" — communities of prophet-trainees." },
    ],
    didYouKnow: [
      "2 Kings ends with Jehoiachin released from Babylonian prison — a small sign of hope.",
      "Josiah began his reforms at age 16 and died at 39 at Megiddo.",
      "Manasseh's 55-year reign was the longest and one of the most evil.",
      "Elisha performed exactly twice as many recorded miracles as Elijah.",
    ],
  },
];
