import type { OTBookContext } from "../context-types";

export const CONTEXT_DEU_TO_RUT: OTBookContext[] = [
  {
    id: "DEU",
    name: "Deuteronomy",
    overview: {
      shortSummary: "Moses' final sermons to Israel before entering the Promised Land; a covenant renewal.",
      fullSummary: "Deuteronomy (\"second law\") records Moses' farewell addresses on the plains of Moab. He reviews Israel's history, restates the law, warns of the dangers of unfaithfulness, and calls a new generation to love and obey the LORD before crossing into Canaan.",
      themes: ["Covenant renewal", "Love and obedience", "Blessing and cursing", "Remembrance", "One true God"],
      keyMessages: ["Love the LORD with all your heart", "Teach the law to your children", "Obedience brings blessing, disobedience brings curse", "Choose life"],
    },
    author: { traditional: "Moses", notes: "Moses is the speaker; the account of his death in ch. 34 was likely added by Joshua or a later editor." },
    timePeriod: {
      eventsDate: "c.1406 BC",
      writingDate: "c.1406 BC",
      biblicalPlacement: "Fifth book of the Torah; final book of the Pentateuch",
      relationToEvents: "Delivered in the final month of the wilderness wanderings",
    },
    historicalSetting: {
      rulers: ["Moses (prophet-leader)", "Og of Bashan (recently defeated)", "Sihon of the Amorites (recently defeated)"],
      israelKings: [],
      neighboringPowers: ["Moab", "Ammon", "Edom", "Canaanite kings"],
      politicalBackground: "Israel camped east of the Jordan, poised to enter Canaan under Joshua's coming leadership.",
    },
    mapLocations: [
      { name: "Plains of Moab", type: "region", description: "Where Moses delivered his sermons", svgX: 172, svgY: 175 },
      { name: "Mount Nebo", type: "city", description: "Where Moses viewed the Promised Land and died", svgX: 170, svgY: 172 },
      { name: "Jordan River", type: "region", description: "The boundary Israel was about to cross", svgX: 165, svgY: 165 },
      { name: "Bashan", type: "region", description: "Conquered from King Og", svgX: 180, svgY: 145 },
      { name: "Heshbon", type: "city", description: "Former capital of Sihon the Amorite", svgX: 175, svgY: 170 },
    ],
    genealogy: {
      description: "The new generation of Israel; Moses passes leadership to Joshua son of Nun.",
      nodes: [
        { id: "moses", name: "Moses", notes: "Dies on Mt. Nebo, age 120" },
        { id: "joshua", name: "Joshua son of Nun", parentId: "moses", notes: "Successor and new leader" },
        { id: "eleazar", name: "Eleazar", parentId: "moses", notes: "High priest, son of Aaron" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Review of wilderness journey", description: "Moses recounts 40 years of wandering", reference: "Deuteronomy 1-3" },
      { order: 2, title: "Restatement of the Ten Commandments", description: "The covenant law renewed for the new generation", reference: "Deuteronomy 5" },
      { order: 3, title: "The Shema", description: "\"Hear, O Israel: the LORD our God, the LORD is one\"", reference: "Deuteronomy 6:4-9" },
      { order: 4, title: "Blessings and curses", description: "Conditions of the covenant proclaimed", reference: "Deuteronomy 28" },
      { order: 5, title: "Joshua commissioned", description: "Moses publicly appoints his successor", reference: "Deuteronomy 31" },
      { order: 6, title: "Song and blessing of Moses", description: "Prophetic song and tribal blessings", reference: "Deuteronomy 32-33" },
      { order: 7, title: "Death of Moses", description: "Moses views Canaan from Nebo and dies", reference: "Deuteronomy 34" },
    ],
    culturalNotes: [
      { category: "law", title: "Covenant treaty form", content: "Deuteronomy follows the structure of ancient Near Eastern suzerain-vassal treaties." },
      { category: "worship", title: "Central sanctuary", content: "Worship was to be centralized at the place the LORD would choose." },
      { category: "social", title: "Care for the vulnerable", content: "Repeated commands to care for widows, orphans, and sojourners." },
      { category: "customs", title: "Tefillin and mezuzot", content: "Deuteronomy 6:8-9 is the basis for Jewish practices of binding Scripture on hand and doorpost." },
    ],
    didYouKnow: [
      "Jesus quoted Deuteronomy more than any other OT book when resisting Satan.",
      "The Shema (Deut 6:4) remains central to daily Jewish prayer.",
      "Moses never entered the Promised Land because he struck the rock instead of speaking to it.",
      "Deuteronomy is structured as three sermons plus final blessings.",
    ],
  },
  {
    id: "JOS",
    name: "Joshua",
    overview: {
      shortSummary: "Israel conquers and divides the Promised Land under Joshua's leadership.",
      fullSummary: "Joshua narrates the conquest of Canaan, the division of the land among the twelve tribes, and Joshua's final covenant renewal at Shechem. It demonstrates God's faithfulness to His promises to Abraham.",
      themes: ["God's faithfulness", "Conquest and inheritance", "Obedience and courage", "Covenant renewal"],
      keyMessages: ["Be strong and courageous", "God fights for His people", "Choose whom you will serve"],
    },
    author: { traditional: "Joshua (with later editorial additions)", notes: "Joshua likely wrote most; the account of his death was added later." },
    timePeriod: {
      eventsDate: "c.1406-1380 BC",
      writingDate: "c.1380 BC",
      biblicalPlacement: "First of the Former Prophets; bridge from Pentateuch to Judges",
      relationToEvents: "Contemporaneous with the events described",
    },
    historicalSetting: {
      rulers: ["Joshua son of Nun", "Eleazar the priest"],
      israelKings: [],
      neighboringPowers: ["31 Canaanite city-states", "Philistines", "Egypt (weakened)"],
      politicalBackground: "Canaan was fragmented among petty kings; Egypt's influence was waning, creating an opening for Israelite conquest.",
    },
    mapLocations: [
      { name: "Jericho", type: "battle", description: "First city conquered; walls fell", svgX: 168, svgY: 165 },
      { name: "Ai", type: "battle", description: "Defeat then victory after Achan's sin", svgX: 165, svgY: 160 },
      { name: "Gilgal", type: "city", description: "First camp in Canaan", svgX: 170, svgY: 165 },
      { name: "Gibeon", type: "city", description: "Site of the long day; sun stood still", svgX: 158, svgY: 162 },
      { name: "Shechem", type: "city", description: "Covenant renewal site", svgX: 160, svgY: 150 },
      { name: "Shiloh", type: "city", description: "Tabernacle established here", svgX: 162, svgY: 155 },
      { name: "Hazor", type: "battle", description: "Head of northern kingdoms", svgX: 170, svgY: 138 },
    ],
    genealogy: {
      description: "Twelve tribes inherit the land.",
      nodes: [
        { id: "jacob", name: "Jacob (Israel)" },
        { id: "reuben", name: "Reuben", parentId: "jacob" },
        { id: "simeon", name: "Simeon", parentId: "jacob" },
        { id: "levi", name: "Levi", parentId: "jacob", notes: "Priestly tribe, no territorial inheritance" },
        { id: "judah", name: "Judah", parentId: "jacob" },
        { id: "dan", name: "Dan", parentId: "jacob" },
        { id: "naphtali", name: "Naphtali", parentId: "jacob" },
        { id: "gad", name: "Gad", parentId: "jacob" },
        { id: "asher", name: "Asher", parentId: "jacob" },
        { id: "issachar", name: "Issachar", parentId: "jacob" },
        { id: "zebulun", name: "Zebulun", parentId: "jacob" },
        { id: "ephraim", name: "Ephraim", parentId: "jacob", notes: "Son of Joseph" },
        { id: "manasseh", name: "Manasseh", parentId: "jacob", notes: "Son of Joseph" },
        { id: "benjamin", name: "Benjamin", parentId: "jacob" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Crossing the Jordan", description: "Waters parted as priests carried the ark", reference: "Joshua 3-4" },
      { order: 2, title: "Fall of Jericho", description: "Walls collapsed after seven-day march", reference: "Joshua 6" },
      { order: 3, title: "Achan's sin and Ai", description: "Defeat, then victory after judgment", reference: "Joshua 7-8" },
      { order: 4, title: "Gibeonite deception", description: "Gibeonites tricked Israel into treaty", reference: "Joshua 9" },
      { order: 5, title: "Sun stands still", description: "Long day at Gibeon; southern coalition defeated", reference: "Joshua 10" },
      { order: 6, title: "Northern campaign", description: "Defeat of Jabin and Hazor", reference: "Joshua 11" },
      { order: 7, title: "Division of the land", description: "Tribal inheritances allotted", reference: "Joshua 13-21" },
      { order: 8, title: "Covenant at Shechem", description: "\"As for me and my house, we will serve the LORD\"", reference: "Joshua 24" },
    ],
    culturalNotes: [
      { category: "worship", title: "The ark of the covenant", content: "Led Israel into the land and across the Jordan." },
      { category: "law", title: "Herem (devoted to destruction)", content: "Certain cities were to be entirely destroyed as an act of divine judgment." },
      { category: "geography", title: "Cities of refuge", content: "Six cities set aside for accidental manslayers." },
      { category: "customs", title: "Covenant memorial stones", content: "Twelve stones from the Jordan commemorated the crossing." },
    ],
    didYouKnow: [
      "Rahab, a Canaanite prostitute, is in the genealogy of Jesus.",
      "Joshua's Hebrew name (Yehoshua) is the same as Jesus' name.",
      "The conquest took about seven years.",
      "Caleb received Hebron at age 85.",
    ],
  },
  {
    id: "JDG",
    name: "Judges",
    overview: {
      shortSummary: "Cycles of apostasy, oppression, repentance, and deliverance through raised-up judges.",
      fullSummary: "Judges describes Israel's spiritual decline after Joshua. Without a king, tribes fell into idolatry and were oppressed; God raised up charismatic deliverers (judges) to rescue them. The cycle repeats with growing darkness.",
      themes: ["Apostasy and deliverance", "Need for godly leadership", "God's patience", "Consequences of compromise"],
      keyMessages: ["Everyone did what was right in their own eyes", "God's mercy endures", "Partial obedience leads to disaster"],
    },
    author: { traditional: "Samuel (tradition)", notes: "Anonymous; Jewish tradition credits Samuel as compiler." },
    timePeriod: {
      eventsDate: "c.1380-1050 BC",
      writingDate: "c.1050-1000 BC",
      biblicalPlacement: "Between conquest and monarchy",
      relationToEvents: "Compiled during the early monarchy",
    },
    historicalSetting: {
      rulers: ["12 judges including Othniel, Ehud, Deborah, Gideon, Jephthah, Samson"],
      israelKings: [],
      neighboringPowers: ["Philistines", "Moabites", "Ammonites", "Midianites", "Canaanites", "Amalekites"],
      politicalBackground: "Israel was a loose tribal confederacy with no central government; foreign oppressors regularly took advantage.",
    },
    mapLocations: [
      { name: "Shiloh", type: "city", description: "Tabernacle location", svgX: 162, svgY: 155 },
      { name: "Jezreel Valley", type: "battle", description: "Deborah and Barak defeat Sisera", svgX: 158, svgY: 148 },
      { name: "Mount Tabor", type: "city", description: "Barak's staging ground", svgX: 160, svgY: 148 },
      { name: "Spring of Harod", type: "city", description: "Gideon's 300 selected here", svgX: 160, svgY: 150 },
      { name: "Gaza", type: "city", description: "Samson's exploits and death", svgX: 140, svgY: 168 },
      { name: "Timnah", type: "city", description: "Samson's Philistine bride", svgX: 147, svgY: 165 },
    ],
    genealogy: {
      description: "Notable judges raised up by God.",
      nodes: [
        { id: "othniel", name: "Othniel", notes: "First judge; Caleb's nephew" },
        { id: "ehud", name: "Ehud", notes: "Left-handed Benjamite" },
        { id: "deborah", name: "Deborah", notes: "Prophetess and judge" },
        { id: "gideon", name: "Gideon", notes: "Defeated Midian with 300 men" },
        { id: "jephthah", name: "Jephthah", notes: "Defeated Ammonites; tragic vow" },
        { id: "samson", name: "Samson", notes: "Nazirite of supernatural strength" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Deborah and Barak defeat Sisera", description: "Jael drives tent peg through Sisera's temple", reference: "Judges 4-5" },
      { order: 2, title: "Gideon's fleece and 300 men", description: "Midianite army routed at night", reference: "Judges 6-7" },
      { order: 3, title: "Jephthah's rash vow", description: "Victory over Ammonites; tragic consequence", reference: "Judges 11" },
      { order: 4, title: "Samson's exploits", description: "Lion, Delilah, temple of Dagon", reference: "Judges 13-16" },
      { order: 5, title: "Civil war against Benjamin", description: "Tribe nearly annihilated after Gibeah atrocity", reference: "Judges 19-21" },
    ],
    culturalNotes: [
      { category: "social", title: "Tribal confederacy", content: "Tribes acted independently, often only uniting in crisis." },
      { category: "worship", title: "Syncretism", content: "Israelites mixed Yahweh worship with Canaanite Baal and Asherah practices." },
      { category: "customs", title: "Nazirite vow", content: "Samson was dedicated from birth: no wine, uncut hair, no corpse contact." },
      { category: "law", title: "Kinsman avenger", content: "Blood feuds were common in this lawless era." },
    ],
    didYouKnow: [
      "The book ends by saying \"everyone did what was right in his own eyes.\"",
      "Deborah is the only female judge named.",
      "Samson's strength was tied to his Nazirite vow, not his hair itself.",
      "Gideon had 70 sons; only Jotham survived Abimelech's massacre.",
    ],
  },
  {
    id: "RUT",
    name: "Ruth",
    overview: {
      shortSummary: "A Moabite widow's loyalty leads to her becoming great-grandmother of King David.",
      fullSummary: "Set in the dark period of the judges, Ruth is a bright story of loyalty, providence, and redemption. Naomi returns from Moab with her Moabite daughter-in-law Ruth, who marries Boaz — a kinsman-redeemer — and becomes David's ancestor.",
      themes: ["Loyalty (hesed)", "Providence", "Redemption", "Inclusion of Gentiles"],
      keyMessages: ["God works quietly through ordinary faithfulness", "Redemption extends beyond Israel", "Loyal love mirrors God's own"],
    },
    author: { traditional: "Samuel (tradition)", notes: "Anonymous; dates to early monarchy." },
    timePeriod: {
      eventsDate: "c.1100 BC (time of the judges)",
      writingDate: "c.1000 BC",
      biblicalPlacement: "Between Judges and 1 Samuel; in Hebrew canon among the Writings (Megilloth)",
      relationToEvents: "Set in the era of the judges, written later",
    },
    historicalSetting: {
      rulers: ["Unnamed judges"],
      israelKings: [],
      neighboringPowers: ["Moab"],
      politicalBackground: "Famine in Israel drove Elimelech's family to Moab; relations between Israel and Moab were often hostile.",
    },
    mapLocations: [
      { name: "Bethlehem", type: "city", description: "Home of Naomi and Boaz; \"house of bread\"", svgX: 160, svgY: 167 },
      { name: "Moab", type: "region", description: "Naomi's family sojourn during famine", svgX: 175, svgY: 175 },
      { name: "Fields of Boaz", type: "region", description: "Where Ruth gleaned", svgX: 160, svgY: 168 },
    ],
    genealogy: {
      description: "Ruth's line leads directly to King David.",
      nodes: [
        { id: "boaz", name: "Boaz" },
        { id: "ruth", name: "Ruth", notes: "Moabite widow" },
        { id: "obed", name: "Obed", parentId: "boaz" },
        { id: "jesse", name: "Jesse", parentId: "obed" },
        { id: "david", name: "David", parentId: "jesse", notes: "Future king" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Naomi's loss in Moab", description: "Husband and sons die; she prepares to return", reference: "Ruth 1:1-5" },
      { order: 2, title: "Ruth's pledge", description: "\"Your people shall be my people, and your God my God\"", reference: "Ruth 1:16-17" },
      { order: 3, title: "Gleaning in Boaz's field", description: "Boaz shows favor to Ruth", reference: "Ruth 2" },
      { order: 4, title: "Threshing floor scene", description: "Ruth asks Boaz to redeem her", reference: "Ruth 3" },
      { order: 5, title: "Redemption at the gate", description: "Boaz legally redeems Ruth and Naomi's land", reference: "Ruth 4:1-12" },
      { order: 6, title: "Birth of Obed", description: "Ancestor of David and ultimately Jesus", reference: "Ruth 4:13-22" },
    ],
    culturalNotes: [
      { category: "law", title: "Gleaning laws", content: "Farmers left edges of fields for the poor, widows, and foreigners (Lev 19:9-10)." },
      { category: "customs", title: "Kinsman-redeemer (goel)", content: "A near relative could redeem family land and marry a widow to continue the family name." },
      { category: "law", title: "Levirate marriage", content: "A brother-in-law or near kin married a childless widow to preserve lineage." },
      { category: "customs", title: "Sandal as legal symbol", content: "Removing a sandal symbolized transfer of legal rights." },
    ],
    didYouKnow: [
      "Ruth is one of only two books named after women (with Esther).",
      "Ruth is Jesus' great-great-...-grandmother.",
      "The book is read at the Jewish festival of Shavuot (Pentecost).",
      "Boaz was the son of Rahab — another Gentile ancestor of Christ.",
    ],
  },
];
