import type { OTBookContext } from "../context-types";

export const CONTEXT_ECC_TO_JER: OTBookContext[] = [
  {
    id: "ECC",
    name: "Ecclesiastes",
    overview: {
      shortSummary: "A philosophical quest for meaning \"under the sun\" — life is vapor apart from God.",
      fullSummary: "The Preacher (Qoheleth) explores life's meaning through pleasure, work, wealth, wisdom, and power, concluding that all is \"vapor\" without God. The book ends urging readers to fear God and keep His commandments.",
      themes: ["Vanity of earthly pursuits", "Fear of God", "Enjoyment as gift", "Wisdom's limits"],
      keyMessages: ["Fear God and keep His commandments", "Everything apart from God is vapor", "Enjoy God's gifts in their seasons"],
    },
    author: { traditional: "Solomon", notes: "\"Son of David, king in Jerusalem\" points to Solomon; some argue for later reflection." },
    timePeriod: {
      eventsDate: "c.970-930 BC",
      writingDate: "c.935 BC",
      biblicalPlacement: "Third Wisdom book; Megilloth",
      relationToEvents: "Written late in Solomon's life",
    },
    historicalSetting: {
      rulers: ["Solomon"],
      israelKings: ["Solomon"],
      neighboringPowers: ["Peace with surrounding kingdoms"],
      politicalBackground: "Solomon's empire at its peak — wealth, wisdom, and leisure to reflect.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Solomon's court", svgX: 160, svgY: 165 },
    ],
    genealogy: {
      description: "Speaker and audience.",
      nodes: [
        { id: "solomon", name: "Solomon (Qoheleth)", notes: "The Preacher" },
      ],
    },
    keyEvents: [
      { order: 1, title: "All is vapor", description: "Opening declaration", reference: "Ecclesiastes 1:2" },
      { order: 2, title: "Quest for meaning", description: "Pleasure, wealth, work all tested", reference: "Ecclesiastes 2" },
      { order: 3, title: "Times and seasons", description: "\"For everything there is a season\"", reference: "Ecclesiastes 3" },
      { order: 4, title: "Enjoyment of life", description: "Eat, drink, find satisfaction in toil", reference: "Ecclesiastes 5:18-20" },
      { order: 5, title: "Remember your Creator", description: "Especially in youth", reference: "Ecclesiastes 12:1-7" },
      { order: 6, title: "Conclusion", description: "Fear God and keep His commandments", reference: "Ecclesiastes 12:13-14" },
    ],
    culturalNotes: [
      { category: "customs", title: "Wisdom literature", content: "Part of the ancient Near Eastern tradition that wrestled with life's puzzles." },
      { category: "social", title: "Royal reflection", content: "Solomon reflects from the vantage of having it all." },
      { category: "worship", title: "Fear of God", content: "Appropriate awe is the anchor of the book." },
      { category: "law", title: "Limits of wisdom", content: "Human wisdom cannot penetrate divine mysteries." },
    ],
    didYouKnow: [
      "\"Vanity of vanities\" translates Hebrew \"hevel\" — vapor, breath.",
      "Ecclesiastes 3:1-8 was popularized by the 1960s song \"Turn! Turn! Turn!\"",
      "The book raises hard questions without quick answers — a mark of honest faith.",
      "Life \"under the sun\" occurs 29 times — viewpoint matters.",
    ],
  },
  {
    id: "SNG",
    name: "Song of Solomon",
    overview: {
      shortSummary: "A celebration of covenantal love between a bride and bridegroom.",
      fullSummary: "Also called Song of Songs, this poetic dialogue extols the beauty of marital love. Traditionally read as allegory of God and Israel (or Christ and the Church), and as an affirmation of human love as a gift.",
      themes: ["Covenant love", "Beauty and desire", "Faithfulness", "God's love for His people"],
      keyMessages: ["Love is strong as death", "Faithful love is worth guarding", "Sexuality within covenant is God's design"],
    },
    author: { traditional: "Solomon", notes: "Solomon is named; some argue the book is written about or to him." },
    timePeriod: {
      eventsDate: "c.970 BC",
      writingDate: "c.970 BC",
      biblicalPlacement: "Megilloth; read at Passover",
      relationToEvents: "Likely early in Solomon's reign",
    },
    historicalSetting: {
      rulers: ["Solomon"],
      israelKings: ["Solomon"],
      neighboringPowers: [],
      politicalBackground: "Peaceful era of Solomon's early reign.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Scene of royal wedding", svgX: 160, svgY: 165 },
      { name: "Lebanon", type: "region", description: "Metaphorical beauty references", svgX: 153, svgY: 135 },
      { name: "En-gedi", type: "city", description: "Fertile oasis metaphor", svgX: 165, svgY: 172 },
      { name: "Mount Carmel", type: "region", description: "Beauty image", svgX: 152, svgY: 147 },
    ],
    genealogy: {
      description: "Speakers.",
      nodes: [
        { id: "bridegroom", name: "Bridegroom", notes: "Solomon or representative" },
        { id: "bride", name: "Bride (Shulamite)", notes: "Beloved" },
        { id: "friends", name: "Daughters of Jerusalem", notes: "Chorus" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Mutual admiration", description: "Opening poems of love", reference: "Song 1-2" },
      { order: 2, title: "Bride's search", description: "Nighttime search for beloved", reference: "Song 3" },
      { order: 3, title: "Wedding procession", description: "Solomon's splendor described", reference: "Song 3:6-11" },
      { order: 4, title: "Descriptions of beauty", description: "Poetic exchange of praise", reference: "Song 4-7" },
      { order: 5, title: "Love as strong as death", description: "Climactic affirmation", reference: "Song 8:6-7" },
    ],
    culturalNotes: [
      { category: "customs", title: "Ancient wedding customs", content: "Grooms came in procession to claim brides; night journeys were part of the tradition." },
      { category: "social", title: "Poetic imagery", content: "Agricultural, architectural, and floral metaphors pervade." },
      { category: "worship", title: "Allegorical reading", content: "Early Jewish and Christian tradition read it as God's love for His people." },
      { category: "law", title: "Covenant love", content: "Hebrew culture saw marriage as a covenant, not merely a contract." },
    ],
    didYouKnow: [
      "Song of Songs = \"the greatest of songs.\"",
      "God is not explicitly named in the book.",
      "Jewish tradition reads it on the 8th day of Passover.",
      "The bride actively pursues the bridegroom — unusual for ancient literature.",
    ],
  },
  {
    id: "ISA",
    name: "Isaiah",
    overview: {
      shortSummary: "Judgment and hope: the Holy One of Israel, the Servant who suffers, and a new creation.",
      fullSummary: "Isaiah ministered during the Assyrian crisis. His 66 chapters announce judgment on Judah and the nations, promise a messianic Servant, and envision a renewed creation. Isaiah is the most quoted prophet in the New Testament.",
      themes: ["Holiness of God", "Judgment and hope", "Messianic Servant", "Redemption and new creation"],
      keyMessages: ["Holy, holy, holy is the LORD of hosts", "A Servant will bear our sins", "Behold, I make all things new"],
    },
    author: { traditional: "Isaiah son of Amoz", notes: "Critical scholarship posits multiple authors; traditional view affirms single authorship." },
    timePeriod: {
      eventsDate: "c.740-686 BC",
      writingDate: "c.700-680 BC",
      biblicalPlacement: "First of the Major Prophets",
      relationToEvents: "Prophet during Uzziah through Hezekiah (and Manasseh by tradition)",
    },
    historicalSetting: {
      rulers: ["Uzziah", "Jotham", "Ahaz", "Hezekiah"],
      israelKings: ["Uzziah, Jotham, Ahaz, Hezekiah (Judah)"],
      neighboringPowers: ["Assyria (dominant)", "Babylon (rising)", "Egypt"],
      politicalBackground: "Assyria crushed Israel (722 BC) and besieged Jerusalem (701 BC). Isaiah ministered through this existential crisis.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Isaiah's ministry center", svgX: 160, svgY: 165 },
      { name: "Nineveh", type: "city", description: "Assyrian capital threatening Judah", svgX: 248, svgY: 128 },
      { name: "Babylon", type: "city", description: "Predicted future captor", svgX: 272, svgY: 178 },
      { name: "Samaria", type: "city", description: "Northern capital, fell in 722", svgX: 158, svgY: 152 },
      { name: "Lachish", type: "battle", description: "Sennacherib's siege base", svgX: 155, svgY: 168 },
      { name: "Tyre", type: "city", description: "Oracles against the nations", svgX: 153, svgY: 140 },
    ],
    genealogy: {
      description: "Key figures.",
      nodes: [
        { id: "amoz", name: "Amoz" },
        { id: "isaiah", name: "Isaiah", parentId: "amoz", notes: "Prophet" },
        { id: "hezekiah", name: "Hezekiah", notes: "Reformer king" },
        { id: "ahaz", name: "Ahaz", notes: "Unbelieving king" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Isaiah's vision and call", description: "Holy, holy, holy; burning coal", reference: "Isaiah 6" },
      { order: 2, title: "Immanuel prophecy", description: "A virgin shall conceive", reference: "Isaiah 7:14" },
      { order: 3, title: "Messianic Prince of Peace", description: "\"Unto us a child is born\"", reference: "Isaiah 9:6-7" },
      { order: 4, title: "Oracles against the nations", description: "Babylon, Moab, Egypt, Tyre judged", reference: "Isaiah 13-23" },
      { order: 5, title: "Hezekiah's deliverance", description: "Assyrian army struck down", reference: "Isaiah 36-37" },
      { order: 6, title: "Comfort for exiles", description: "\"Comfort, comfort my people\"", reference: "Isaiah 40" },
      { order: 7, title: "Suffering Servant", description: "He was wounded for our transgressions", reference: "Isaiah 52:13-53:12" },
      { order: 8, title: "New heavens and new earth", description: "Final restoration vision", reference: "Isaiah 65-66" },
    ],
    culturalNotes: [
      { category: "worship", title: "Seraphim", content: "Six-winged heavenly beings proclaiming God's holiness." },
      { category: "social", title: "Remnant theology", content: "A faithful remnant would survive judgment." },
      { category: "customs", title: "Symbolic acts", content: "Isaiah walked naked 3 years as a sign against Egypt (Isa 20)." },
      { category: "law", title: "True fasting", content: "Isaiah 58 reframes fasting as justice and mercy." },
    ],
    didYouKnow: [
      "Isaiah has 66 chapters — some see a mini-Bible structure (39 + 27).",
      "The Dead Sea Scrolls included a nearly complete Isaiah scroll.",
      "Isaiah 53 is the clearest OT prophecy of Christ's atonement.",
      "Jesus began His ministry by reading Isaiah 61 in Nazareth.",
    ],
  },
  {
    id: "JER",
    name: "Jeremiah",
    overview: {
      shortSummary: "The weeping prophet announces Judah's fall and a new covenant.",
      fullSummary: "Jeremiah ministered for 40 years as Judah collapsed into Babylonian exile. He wept over his people's stubbornness, suffered persecution, and announced both judgment and a new covenant written on the heart.",
      themes: ["Judgment", "Persistence in ministry", "New covenant", "God's sovereignty"],
      keyMessages: ["The heart is deceitful above all things", "I will make a new covenant", "Seek the welfare of the city where I sent you"],
    },
    author: { traditional: "Jeremiah with Baruch as scribe", notes: "Baruch recorded and preserved Jeremiah's words." },
    timePeriod: {
      eventsDate: "c.627-586 BC",
      writingDate: "c.620-580 BC",
      biblicalPlacement: "Major Prophet",
      relationToEvents: "Contemporary with events",
    },
    historicalSetting: {
      rulers: ["Josiah", "Jehoiakim", "Zedekiah", "Nebuchadnezzar"],
      israelKings: ["Last five kings of Judah"],
      neighboringPowers: ["Babylon (rising)", "Egypt", "Assyria (collapsing)"],
      politicalBackground: "Assyria fell (612 BC); Babylon rose and destroyed Jerusalem in 586 BC. Jeremiah urged submission to Babylon.",
    },
    mapLocations: [
      { name: "Anathoth", type: "city", description: "Jeremiah's hometown", svgX: 162, svgY: 163 },
      { name: "Jerusalem", type: "city", description: "Ministry and destruction", svgX: 160, svgY: 165 },
      { name: "Mizpah", type: "city", description: "Gedaliah's center after exile", svgX: 160, svgY: 162 },
      { name: "Egypt (Tahpanhes)", type: "city", description: "Jeremiah forced into exile here", svgX: 120, svgY: 195 },
      { name: "Babylon", type: "exile", description: "Exile destination", svgX: 272, svgY: 178 },
      { name: "Carchemish", type: "battle", description: "Babylon defeats Egypt 605 BC", svgX: 210, svgY: 118 },
    ],
    genealogy: {
      description: "Jeremiah and contemporaries.",
      nodes: [
        { id: "hilkiah", name: "Hilkiah (priest)" },
        { id: "jeremiah", name: "Jeremiah", parentId: "hilkiah" },
        { id: "baruch", name: "Baruch", notes: "Scribe" },
        { id: "gedaliah", name: "Gedaliah", notes: "Governor after fall" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Jeremiah's call", description: "Appointed prophet before birth", reference: "Jeremiah 1" },
      { order: 2, title: "Temple sermon", description: "Condemns false confidence in temple", reference: "Jeremiah 7" },
      { order: 3, title: "Potter's house", description: "God reshapes nations like clay", reference: "Jeremiah 18-19" },
      { order: 4, title: "70 years foretold", description: "Length of Babylonian exile", reference: "Jeremiah 25:11-12" },
      { order: 5, title: "New covenant promise", description: "Law written on hearts", reference: "Jeremiah 31:31-34" },
      { order: 6, title: "Jeremiah imprisoned", description: "Thrown into cistern", reference: "Jeremiah 38" },
      { order: 7, title: "Fall of Jerusalem", description: "Babylon destroys city and temple", reference: "Jeremiah 39, 52" },
      { order: 8, title: "Taken to Egypt", description: "Remaining Jews force Jeremiah to Egypt", reference: "Jeremiah 43" },
    ],
    culturalNotes: [
      { category: "customs", title: "Symbolic acts", content: "Yoke on neck, hidden waistcloth, bought field — all prophetic dramas." },
      { category: "social", title: "Rechabites", content: "A Bedouin-like group whose faithfulness to family vows shamed Judah's unfaithfulness to God." },
      { category: "law", title: "Land redemption", content: "Jeremiah bought a field during the siege as a sign of hope." },
      { category: "worship", title: "False prophets", content: "Jeremiah contended with popular prophets promising peace." },
    ],
    didYouKnow: [
      "Jeremiah is the longest book by word count in the Bible.",
      "The \"new covenant\" promise is quoted at length in Hebrews 8.",
      "Jeremiah likely never married by divine command.",
      "Daniel was inspired by Jeremiah's 70-year prophecy to pray for restoration (Dan 9).",
    ],
  },
];
