import type { OTBookContext } from "../context-types";

export const CONTEXT_EST_TO_PRO: OTBookContext[] = [
  {
    id: "EST",
    name: "Esther",
    overview: {
      shortSummary: "A Jewish queen in Persia saves her people from genocide.",
      fullSummary: "Esther, a young Jewish woman, becomes queen of Persia and, at the risk of her life, exposes Haman's plot to exterminate the Jews. The book establishes the feast of Purim. God is never named but providentially active throughout.",
      themes: ["Hidden providence", "Courage", "Reversal", "Jewish preservation"],
      keyMessages: ["For such a time as this", "God works unseen", "Evil schemes boomerang"],
    },
    author: { traditional: "Mordecai (tradition)", notes: "Anonymous; insider knowledge of Persian court." },
    timePeriod: {
      eventsDate: "c.483-473 BC",
      writingDate: "c.460 BC",
      biblicalPlacement: "Writings (Megilloth) in Hebrew canon",
      relationToEvents: "Written shortly after the events by someone familiar with Persia",
    },
    historicalSetting: {
      rulers: ["Xerxes I (Ahasuerus)", "Esther", "Mordecai", "Haman"],
      israelKings: [],
      neighboringPowers: ["Persian empire at its peak"],
      politicalBackground: "Jews remained in the Persian empire even after the returns to Judah; Esther's story unfolds in the capital.",
    },
    mapLocations: [
      { name: "Susa (Shushan)", type: "city", description: "Persian winter capital; the entire story", svgX: 298, svgY: 173 },
      { name: "Persia (empire)", type: "region", description: "127 provinces from India to Cush", svgX: 310, svgY: 170 },
    ],
    genealogy: {
      description: "Key figures in Esther.",
      nodes: [
        { id: "kish", name: "Kish", notes: "Benjamite ancestor" },
        { id: "mordecai", name: "Mordecai", parentId: "kish" },
        { id: "esther", name: "Esther (Hadassah)", parentId: "mordecai", notes: "Cousin raised as daughter" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Vashti deposed", description: "Queen refuses command; position opens", reference: "Esther 1" },
      { order: 2, title: "Esther chosen queen", description: "Out of many young women", reference: "Esther 2" },
      { order: 3, title: "Mordecai foils plot", description: "Saves king's life; recorded in annals", reference: "Esther 2:21-23" },
      { order: 4, title: "Haman's decree", description: "Plot to destroy all Jews", reference: "Esther 3" },
      { order: 5, title: "\"For such a time as this\"", description: "Mordecai's challenge to Esther", reference: "Esther 4:14" },
      { order: 6, title: "Esther's banquets", description: "Two feasts prepared for the king and Haman", reference: "Esther 5, 7" },
      { order: 7, title: "Haman hanged", description: "On the gallows he built for Mordecai", reference: "Esther 7:10" },
      { order: 8, title: "Feast of Purim", description: "Jews defend themselves; festival established", reference: "Esther 9" },
    ],
    culturalNotes: [
      { category: "customs", title: "Purim", content: "Annual Jewish festival celebrating deliverance; includes reading Esther, feasting, gift-giving." },
      { category: "social", title: "Persian court protocol", content: "Approaching the king unsummoned was punishable by death." },
      { category: "law", title: "Irrevocable decrees", content: "A Persian king's decree could not be revoked, only countered." },
      { category: "worship", title: "God unnamed", content: "God is never explicitly named, yet His providence is unmistakable." },
    ],
    didYouKnow: [
      "The word \"pur\" (lot) gives the festival Purim its name.",
      "Haman's Agagite ancestry links him to the Amalekites Saul failed to destroy.",
      "Esther's real name, Hadassah, means \"myrtle.\"",
      "The book spans about 10 years.",
    ],
  },
  {
    id: "JOB",
    name: "Job",
    overview: {
      shortSummary: "A righteous man suffers; wisdom dialogue about the problem of pain.",
      fullSummary: "Job, a blameless man, suffers catastrophic losses allowed by God and instigated by Satan. Long dialogues with his friends explore why the righteous suffer. God finally speaks, humbling Job and restoring him.",
      themes: ["Suffering and faith", "God's sovereignty", "Limits of human wisdom", "Integrity"],
      keyMessages: ["God is trustworthy even in suffering", "Humility before mystery", "Pat answers fail"],
    },
    author: { traditional: "Moses or Job (tradition)", notes: "Anonymous; possibly ancient pre-Mosaic setting." },
    timePeriod: {
      eventsDate: "Patriarchal era (c.2000-1800 BC)",
      writingDate: "Disputed: c.1400 BC or later",
      biblicalPlacement: "First Wisdom book",
      relationToEvents: "Set in the patriarchal period; written possibly much later",
    },
    historicalSetting: {
      rulers: ["Job (chief of Uz)"],
      israelKings: [],
      neighboringPowers: ["Sabean and Chaldean raiders"],
      politicalBackground: "Set in the land of Uz (possibly Edom or northern Arabia); pastoral patriarchal context.",
    },
    mapLocations: [
      { name: "Land of Uz", type: "region", description: "Job's homeland, possibly near Edom", svgX: 195, svgY: 195 },
      { name: "Chaldean lands", type: "region", description: "Raiders attacked Job's camels", svgX: 272, svgY: 178 },
      { name: "Sabean lands", type: "region", description: "Raiders attacked Job's oxen", svgX: 240, svgY: 225 },
    ],
    genealogy: {
      description: "Job and his circle.",
      nodes: [
        { id: "job", name: "Job", notes: "Chief of Uz" },
        { id: "eliphaz", name: "Eliphaz", notes: "Temanite friend" },
        { id: "bildad", name: "Bildad", notes: "Shuhite friend" },
        { id: "zophar", name: "Zophar", notes: "Naamathite friend" },
        { id: "elihu", name: "Elihu", notes: "Younger speaker" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Prologue in heaven", description: "Satan challenges Job's integrity", reference: "Job 1-2" },
      { order: 2, title: "Job's losses", description: "Children, wealth, health — all gone", reference: "Job 1:13-2:10" },
      { order: 3, title: "Three friends arrive", description: "Sit silent for seven days", reference: "Job 2:11-13" },
      { order: 4, title: "Dialogue cycles", description: "Three rounds of speeches about suffering", reference: "Job 3-31" },
      { order: 5, title: "Elihu's speeches", description: "Younger man rebukes all", reference: "Job 32-37" },
      { order: 6, title: "God speaks from whirlwind", description: "Asks Job unanswerable questions", reference: "Job 38-41" },
      { order: 7, title: "Job's restoration", description: "Blessing doubled", reference: "Job 42" },
    ],
    culturalNotes: [
      { category: "customs", title: "Mourning rites", content: "Tearing robes, shaving heads, sitting in ashes, sackcloth — all present." },
      { category: "social", title: "City gate elders", content: "Job sat at the gate, a place of authority and justice." },
      { category: "worship", title: "Priestly father", content: "Job interceded with sacrifices for his children — pre-Mosaic pattern." },
      { category: "law", title: "Blessing and cursing theology", content: "The friends assumed wealth = righteousness, poverty = sin." },
    ],
    didYouKnow: [
      "Job is possibly the oldest book in the Bible.",
      "The book contains the earliest references to Leviathan and Behemoth.",
      "God never explains His reasons to Job.",
      "Job 19:25 — \"I know that my Redeemer lives\" — is a remarkable early hope of resurrection.",
    ],
  },
  {
    id: "PSA",
    name: "Psalms",
    overview: {
      shortSummary: "The Bible's hymnbook: prayers, praise, laments, and messianic hope.",
      fullSummary: "Psalms is a collection of 150 inspired songs and prayers written over ~1000 years. Organized into 5 books, it spans every human emotion — praise, lament, thanksgiving, royal, wisdom, and messianic psalms.",
      themes: ["Worship", "Lament", "Messianic hope", "Trust in God", "Torah meditation"],
      keyMessages: ["God hears honest prayer", "Praise in every season", "The Messiah reigns"],
    },
    author: { traditional: "Multiple: David (73), Asaph, sons of Korah, Moses, Solomon, anonymous", notes: "Compiled over centuries into final 5-book form." },
    timePeriod: {
      eventsDate: "c.1410-430 BC (composition span)",
      writingDate: "c.430 BC (final compilation)",
      biblicalPlacement: "Heart of the Writings; central worship book",
      relationToEvents: "Spans from Moses (Ps 90) through post-exilic period",
    },
    historicalSetting: {
      rulers: ["David", "Solomon", "post-exilic leaders"],
      israelKings: ["David, Solomon, various"],
      neighboringPowers: ["Varies by psalm"],
      politicalBackground: "Covers wilderness, monarchy, exile, and return — a spiritual journal of a nation.",
    },
    mapLocations: [
      { name: "Jerusalem / Zion", type: "city", description: "Center of worship in many psalms", svgX: 160, svgY: 165 },
      { name: "Mount Zion", type: "city", description: "Symbol of God's dwelling", svgX: 160, svgY: 165 },
      { name: "Babylon", type: "exile", description: "Psalm 137 \"by the rivers of Babylon\"", svgX: 272, svgY: 178 },
      { name: "Wilderness of Judah", type: "region", description: "Many Davidic laments", svgX: 163, svgY: 170 },
      { name: "Jordan", type: "region", description: "Psalm 42 \"deer panting\"", svgX: 165, svgY: 155 },
    ],
    genealogy: {
      description: "Psalmists.",
      nodes: [
        { id: "moses", name: "Moses", notes: "Wrote Psalm 90" },
        { id: "david", name: "David", notes: "73 psalms" },
        { id: "asaph", name: "Asaph", notes: "12 psalms; Levite musician" },
        { id: "korah", name: "Sons of Korah", notes: "11 psalms; Levite guild" },
        { id: "solomon", name: "Solomon", notes: "Psalms 72, 127" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Book I (1-41)", description: "Primarily Davidic; personal psalms", reference: "Psalms 1-41" },
      { order: 2, title: "Book II (42-72)", description: "Davidic and sons of Korah", reference: "Psalms 42-72" },
      { order: 3, title: "Book III (73-89)", description: "Asaph and others; darker tone", reference: "Psalms 73-89" },
      { order: 4, title: "Book IV (90-106)", description: "Begins with Moses; kingship of God", reference: "Psalms 90-106" },
      { order: 5, title: "Book V (107-150)", description: "Post-exile praise; ends with hallelujahs", reference: "Psalms 107-150" },
    ],
    culturalNotes: [
      { category: "worship", title: "Temple worship", content: "Many psalms sung by temple choirs with musical instruments." },
      { category: "customs", title: "Selah", content: "Likely a musical notation for pause or interlude." },
      { category: "customs", title: "Hebrew poetry parallelism", content: "Thought-rhyme, not sound-rhyme — translation-friendly." },
      { category: "worship", title: "Pilgrim psalms", content: "Psalms 120-134 sung on journey up to Jerusalem." },
    ],
    didYouKnow: [
      "Psalm 119 is the longest chapter in the Bible (176 verses, alphabetic acrostic).",
      "Psalm 117 is the shortest chapter in the Bible (2 verses).",
      "Jesus quoted Psalms more than any other book.",
      "Psalm 22 prophesies crucifixion details written 1000 years before Christ.",
    ],
  },
  {
    id: "PRO",
    name: "Proverbs",
    overview: {
      shortSummary: "Wisdom for daily living — short sayings about money, speech, work, and relationships.",
      fullSummary: "Proverbs collects wisdom sayings, primarily from Solomon, that apply the fear of the LORD to everyday decisions. It personifies Lady Wisdom calling and Lady Folly seducing, and concludes with the virtuous woman.",
      themes: ["Fear of the LORD", "Wisdom vs. folly", "Speech", "Work and wealth", "Family"],
      keyMessages: ["The fear of the LORD is the beginning of wisdom", "Choose your companions wisely", "Diligence pays"],
    },
    author: { traditional: "Mostly Solomon", notes: "Also contains sayings of Agur (Pro 30) and King Lemuel (Pro 31)." },
    timePeriod: {
      eventsDate: "c.970-930 BC (Solomon's era)",
      writingDate: "c.930-700 BC (Hezekiah's scribes added later)",
      biblicalPlacement: "Second Wisdom book",
      relationToEvents: "Compiled over centuries",
    },
    historicalSetting: {
      rulers: ["Solomon"],
      israelKings: ["Solomon, Hezekiah (compiler)"],
      neighboringPowers: ["Broad wisdom tradition across ancient Near East"],
      politicalBackground: "Solomon's court cultivated international wisdom; Proverbs baptizes and transforms it under the fear of the LORD.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Solomon's court and wisdom center", svgX: 160, svgY: 165 },
      { name: "Gibeon", type: "city", description: "Solomon's dream of wisdom", svgX: 158, svgY: 162 },
    ],
    genealogy: {
      description: "Sages of Proverbs.",
      nodes: [
        { id: "solomon", name: "Solomon" },
        { id: "agur", name: "Agur son of Jakeh", notes: "Unknown sage" },
        { id: "lemuel", name: "King Lemuel", notes: "Possibly pseudonym" },
        { id: "hezekiahmen", name: "Men of Hezekiah", notes: "Compilers of chapters 25-29" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Prologue on wisdom", description: "Fear of the LORD; beware of the wicked", reference: "Proverbs 1-9" },
      { order: 2, title: "Lady Wisdom calls", description: "Personified wisdom pleads in streets", reference: "Proverbs 8" },
      { order: 3, title: "Solomon's proverbs", description: "Core collection of couplets", reference: "Proverbs 10-22" },
      { order: 4, title: "Sayings of the wise", description: "Advice on character and justice", reference: "Proverbs 22:17-24:34" },
      { order: 5, title: "Hezekiah collection", description: "More Solomonic proverbs preserved", reference: "Proverbs 25-29" },
      { order: 6, title: "Words of Agur", description: "Numerical sayings", reference: "Proverbs 30" },
      { order: 7, title: "Words of Lemuel / virtuous woman", description: "Acrostic of excellent wife", reference: "Proverbs 31" },
    ],
    culturalNotes: [
      { category: "customs", title: "Wisdom schools", content: "Royal scribes trained in wisdom literature across the ancient Near East." },
      { category: "social", title: "Father-son instruction", content: "Proverbs is framed as a father instructing his son." },
      { category: "law", title: "Economic wisdom", content: "Proverbs commands honest scales and care for the poor." },
      { category: "customs", title: "Wisdom poetry", content: "Hebrew synonymous, antithetic, and synthetic parallelism throughout." },
    ],
    didYouKnow: [
      "Solomon wrote 3,000 proverbs; this book contains a fraction.",
      "Proverbs 31 is often read to honor godly women.",
      "\"The fear of the LORD\" opens, anchors, and concludes the book.",
      "Many proverbs have parallels in Egyptian wisdom texts, showing God uses common grace.",
    ],
  },
];
