import type { OTBookContext } from "../context-types";

export const CONTEXT_GEN_TO_NUM: OTBookContext[] = [
  {
    id: "GEN",
    name: "Genesis",
    overview: {
      shortSummary: "Beginnings: creation, fall, flood, and the patriarchs Abraham, Isaac, Jacob, and Joseph.",
      fullSummary: "Genesis traces the origin of everything — the universe, humanity, sin, nations, and God's covenant people. From creation through Joseph's rise in Egypt, it establishes the foundation for the entire biblical story.",
      themes: ["Creation and God's sovereignty", "Sin and redemption", "Covenant with Abraham", "Providence and faithfulness", "Family and lineage"],
      keyMessages: ["God created everything good", "Sin has devastating consequences", "God keeps His covenant promises", "God works through flawed people"],
    },
    author: { traditional: "Moses", notes: "Traditional Mosaic authorship; Moses used oral tradition and divine revelation to compile pre-Mosaic history." },
    timePeriod: {
      eventsDate: "Creation to c.1805 BC",
      writingDate: "c.1445-1405 BC",
      biblicalPlacement: "Foundational book of Scripture; first book of the Torah",
      relationToEvents: "Moses wrote looking back on primeval history and patriarchal narratives",
    },
    historicalSetting: {
      rulers: ["Pharaoh (unnamed, Joseph's era)"],
      israelKings: [],
      neighboringPowers: ["Egypt", "Canaan city-states", "Mesopotamian kingdoms"],
      politicalBackground: "No unified Israel yet; patriarchs lived as semi-nomads in Canaan and later in Egypt.",
    },
    mapLocations: [
      { name: "Eden (traditional region)", type: "region", description: "Garden of Eden, near Tigris/Euphrates", svgX: 290, svgY: 120 },
      { name: "Ur of the Chaldees", type: "city", description: "Abraham's birthplace in Mesopotamia", svgX: 278, svgY: 182 },
      { name: "Haran", type: "city", description: "Abraham's stopover en route to Canaan", svgX: 222, svgY: 108 },
      { name: "Canaan", type: "region", description: "The Promised Land", svgX: 155, svgY: 158 },
      { name: "Egypt/Goshen", type: "region", description: "Where Joseph rose to power; Israel settled", svgX: 95, svgY: 185 },
    ],
    genealogy: {
      description: "From Adam through Noah to the patriarchs of Israel.",
      nodes: [
        { id: "adam", name: "Adam" },
        { id: "seth", name: "Seth", parentId: "adam" },
        { id: "noah", name: "Noah", parentId: "seth", notes: "10th generation from Adam" },
        { id: "shem", name: "Shem", parentId: "noah" },
        { id: "abraham", name: "Abraham", parentId: "shem", notes: "Father of faith" },
        { id: "isaac", name: "Isaac", parentId: "abraham" },
        { id: "ishmael", name: "Ishmael", parentId: "abraham" },
        { id: "jacob", name: "Jacob (Israel)", parentId: "isaac" },
        { id: "esau", name: "Esau", parentId: "isaac" },
        { id: "joseph", name: "Joseph", parentId: "jacob" },
        { id: "judah", name: "Judah", parentId: "jacob", notes: "Ancestor of David and Christ" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Creation", description: "God creates the heavens, earth, and all living things in six days", reference: "Genesis 1-2" },
      { order: 2, title: "The Fall", description: "Adam and Eve disobey, bringing sin and death into the world", reference: "Genesis 3" },
      { order: 3, title: "The Flood", description: "God judges humanity; Noah and his family are saved", reference: "Genesis 6-9" },
      { order: 4, title: "Tower of Babel", description: "Languages confused; nations scattered", reference: "Genesis 11" },
      { order: 5, title: "Call of Abram", description: "God promises Abram land, descendants, and blessing", reference: "Genesis 12" },
      { order: 6, title: "Jacob wrestles with God", description: "Renamed Israel after wrestling with the Angel", reference: "Genesis 32" },
      { order: 7, title: "Joseph sold to Egypt", description: "Joseph's brothers sell him into slavery", reference: "Genesis 37" },
      { order: 8, title: "Joseph saves Egypt & family", description: "Joseph reveals himself; Israel enters Egypt", reference: "Genesis 45-46" },
    ],
    culturalNotes: [
      { category: "worship", title: "Ancient Near East creation accounts", content: "Genesis parallels and directly contrasts with Babylonian and Egyptian creation myths, presenting one true Creator." },
      { category: "social", title: "Patriarchal clan society", content: "Extended families traveled together; the father was head and priest of the household." },
      { category: "customs", title: "Firstborn rights", content: "Birthright and blessing passed to the firstborn son — but God often subverted this (Isaac, Jacob, Joseph)." },
      { category: "law", title: "Covenant ceremonies", content: "Covenants sealed by cutting animals and passing between the pieces (Genesis 15)." },
    ],
    didYouKnow: [
      "Genesis uses the word 'good' 7 times in the creation account.",
      "Abraham is the only person in the OT called 'friend of God' (James 2:23).",
      "Joseph's story takes up more chapters (13) than any other patriarch.",
    ],
  },
  {
    id: "EXO",
    name: "Exodus",
    overview: {
      shortSummary: "Israel's deliverance from Egyptian slavery through Moses, the Ten Commandments, and the tabernacle.",
      fullSummary: "Exodus is the story of redemption: God hears His enslaved people, raises up Moses, defeats Egypt's gods through the plagues, leads Israel out, and establishes them as His covenant nation at Sinai.",
      themes: ["Deliverance and salvation", "God's power over false gods", "Law and covenant", "Worship and tabernacle", "Identity as God's people"],
      keyMessages: ["God hears the cries of the oppressed", "No god compares to YHWH", "Obedience flows from gratitude for redemption", "God dwells with His people"],
    },
    author: { traditional: "Moses", notes: "Eyewitness leader of the events; wrote contemporaneously." },
    timePeriod: {
      eventsDate: "c.1446-1406 BC",
      writingDate: "c.1445-1405 BC",
      biblicalPlacement: "Second book of the Torah",
      relationToEvents: "Moses recorded events as participant and leader",
    },
    historicalSetting: {
      rulers: ["Pharaoh (possibly Thutmose III or Ramesses II)"],
      israelKings: [],
      neighboringPowers: ["Egypt (superpower)"],
      politicalBackground: "Israel enslaved in Egypt for ~400 years; Exodus marks Israel's birth as a nation under God.",
    },
    mapLocations: [
      { name: "Goshen", type: "region", description: "Where Israel lived in Egypt", svgX: 95, svgY: 185 },
      { name: "Nile Delta", type: "region", description: "Setting of the plagues", svgX: 82, svgY: 182 },
      { name: "Red Sea crossing", type: "journey", description: "God parts the waters for Israel", svgX: 108, svgY: 202 },
      { name: "Mt Sinai (Horeb)", type: "city", description: "Where the Law was given", svgX: 118, svgY: 218 },
      { name: "Wilderness of Sinai", type: "region", description: "Where Israel camped for a year", svgX: 120, svgY: 212 },
    ],
    genealogy: {
      description: "The Levitical line from which Moses and Aaron came.",
      nodes: [
        { id: "levi", name: "Levi (son of Jacob)" },
        { id: "kohath", name: "Kohath", parentId: "levi" },
        { id: "amram", name: "Amram", parentId: "kohath" },
        { id: "moses", name: "Moses", parentId: "amram", notes: "Deliverer and lawgiver" },
        { id: "aaron", name: "Aaron", parentId: "amram", notes: "First high priest" },
        { id: "miriam", name: "Miriam", parentId: "amram", notes: "Prophetess" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Moses born & hidden", description: "Baby Moses rescued from Nile by Pharaoh's daughter", reference: "Exodus 2" },
      { order: 2, title: "The burning bush", description: "God calls Moses at Horeb to deliver Israel", reference: "Exodus 3" },
      { order: 3, title: "The Ten Plagues", description: "God judges Egypt and its gods", reference: "Exodus 7-12" },
      { order: 4, title: "The Passover", description: "Lamb's blood shields Israel from the angel of death", reference: "Exodus 12" },
      { order: 5, title: "Crossing the Red Sea", description: "Israel walks through on dry ground; Egypt drowns", reference: "Exodus 14" },
      { order: 6, title: "The Ten Commandments", description: "God gives the Law at Mt Sinai", reference: "Exodus 20" },
      { order: 7, title: "Golden calf rebellion", description: "Israel falls into idolatry while Moses is on the mountain", reference: "Exodus 32" },
      { order: 8, title: "Tabernacle constructed", description: "Portable sanctuary for God's presence built", reference: "Exodus 25-40" },
    ],
    culturalNotes: [
      { category: "worship", title: "Passover feast", content: "Foundational annual commemoration of deliverance, still kept by Jews today." },
      { category: "worship", title: "Plagues vs. Egyptian gods", content: "Each plague challenged a specific Egyptian deity — Nile (Hapi), darkness (Ra), firstborn (Pharaoh's heir)." },
      { category: "law", title: "Blood sacrifice for sin", content: "Life-for-life substitution foreshadows the atonement of Christ." },
      { category: "worship", title: "Tabernacle design", content: "Portable tent with specific dimensions, colors, and materials — each symbolic." },
    ],
    didYouKnow: [
      "The name 'Moses' comes from Egyptian meaning 'drawn out of water'.",
      "The ten plagues directly challenged ten Egyptian deities.",
      "Israel plundered Egypt's gold and silver on the way out, fulfilling God's promise to Abraham.",
    ],
  },
  {
    id: "LEV",
    name: "Leviticus",
    overview: {
      shortSummary: "God's manual for holy living, priestly service, sacrifices, and the Day of Atonement.",
      fullSummary: "Leviticus instructs Israel how to approach a holy God. Sacrifices, purity laws, festivals, and the Holiness Code teach that God's presence requires His people to be set apart.",
      themes: ["Holiness of God", "Atonement and sacrifice", "Clean and unclean", "Priestly service", "Covenant faithfulness"],
      keyMessages: ["Be holy, for I am holy", "Sin requires atonement", "God's presence demands purity", "Worship must be done God's way"],
    },
    author: { traditional: "Moses", notes: "Received during the year at Mt Sinai." },
    timePeriod: {
      eventsDate: "c.1445 BC (one month at Sinai)",
      writingDate: "c.1445-1405 BC",
      biblicalPlacement: "Third book of the Torah; Israel at Sinai",
      relationToEvents: "Given at Sinai before Israel marched toward Canaan",
    },
    historicalSetting: {
      rulers: ["Moses as mediator"],
      israelKings: [],
      neighboringPowers: ["Egypt (recently departed)"],
      politicalBackground: "Israel encamped at Sinai receiving the law, setting up the priestly worship system.",
    },
    mapLocations: [
      { name: "Mt Sinai", type: "city", description: "Where the Law was delivered", svgX: 118, svgY: 218 },
      { name: "Tabernacle at Sinai", type: "region", description: "Center of Israelite worship", svgX: 120, svgY: 215 },
    ],
    genealogy: {
      description: "The Aaronic priesthood.",
      nodes: [
        { id: "aaron", name: "Aaron (High Priest)" },
        { id: "nadab", name: "Nadab", parentId: "aaron", notes: "Died for strange fire" },
        { id: "abihu", name: "Abihu", parentId: "aaron", notes: "Died for strange fire" },
        { id: "eleazar", name: "Eleazar", parentId: "aaron" },
        { id: "ithamar", name: "Ithamar", parentId: "aaron" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Sacrificial system established", description: "Five offerings: burnt, grain, peace, sin, guilt", reference: "Leviticus 1-7" },
      { order: 2, title: "Ordination of Aaron and sons", description: "Priesthood inaugurated", reference: "Leviticus 8-9" },
      { order: 3, title: "Nadab and Abihu die", description: "Killed for offering unauthorized fire", reference: "Leviticus 10" },
      { order: 4, title: "Day of Atonement", description: "Annual cleansing of nation's sin; scapegoat sent away", reference: "Leviticus 16" },
      { order: 5, title: "Holiness Code given", description: "Rules for ethics, justice, and consecrated life", reference: "Leviticus 17-26" },
    ],
    culturalNotes: [
      { category: "worship", title: "Five offerings", content: "Burnt (total devotion), grain (thanksgiving), peace (fellowship), sin (purification), guilt (restitution)." },
      { category: "worship", title: "Day of Atonement (Yom Kippur)", content: "Most sacred day; only day high priest entered the Holy of Holies." },
      { category: "law", title: "Clean and unclean", content: "Dietary and ritual laws taught Israel to distinguish holy from common." },
      { category: "social", title: "Jubilee year", content: "Every 50 years debts forgiven, slaves freed, land returned." },
    ],
    didYouKnow: [
      "Jesus quoted Leviticus 19:18 ('love your neighbor') as one of the two greatest commandments.",
      "Rabbinic tradition counts 613 commandments in the Torah, most rooted in Leviticus.",
      "The word 'scapegoat' comes directly from Leviticus 16's ritual.",
    ],
  },
  {
    id: "NUM",
    name: "Numbers",
    overview: {
      shortSummary: "Israel's 40-year wandering in the wilderness due to unbelief, ending at the plains of Moab.",
      fullSummary: "Numbers records Israel's journey from Sinai toward Canaan — delayed 40 years because of unbelief. The old generation dies; a new generation stands ready to enter the Promised Land.",
      themes: ["Faithfulness and rebellion", "God's discipline", "Leadership and community", "The journey of faith", "God's persistent presence"],
      keyMessages: ["Unbelief has consequences", "God's purposes cannot be thwarted", "A new generation must trust God", "God remains faithful even to a faithless people"],
    },
    author: { traditional: "Moses", notes: "Written during the 40 years of wandering." },
    timePeriod: {
      eventsDate: "c.1445-1405 BC",
      writingDate: "c.1405 BC",
      biblicalPlacement: "Fourth book of Torah; wilderness period",
      relationToEvents: "Moses recorded events during the 40 years",
    },
    historicalSetting: {
      rulers: ["Moses and Aaron"],
      israelKings: [],
      neighboringPowers: ["Moabites", "Midianites", "Amorites", "Canaanites"],
      politicalBackground: "Israel as a migrating nation-in-formation, facing hostile neighbors en route to Canaan.",
    },
    mapLocations: [
      { name: "Mt Sinai", type: "city", description: "Departure point", svgX: 118, svgY: 218 },
      { name: "Kadesh Barnea", type: "city", description: "Where spies were sent; rebellion occurred", svgX: 128, svgY: 188 },
      { name: "Wilderness of Paran", type: "region", description: "Major portion of wandering", svgX: 125, svgY: 200 },
      { name: "Plains of Moab", type: "region", description: "Final camp before entering Canaan", svgX: 168, svgY: 168 },
      { name: "Edom", type: "region", description: "Refused Israel passage", svgX: 168, svgY: 195 },
    ],
    genealogy: {
      description: "Key leaders of the wilderness period.",
      nodes: [
        { id: "moses", name: "Moses" },
        { id: "aaron", name: "Aaron" },
        { id: "joshua", name: "Joshua son of Nun", notes: "Faithful spy; Moses' successor" },
        { id: "caleb", name: "Caleb son of Jephunneh", notes: "Faithful spy" },
        { id: "korah", name: "Korah", notes: "Led rebellion; killed" },
      ],
    },
    keyEvents: [
      { order: 1, title: "First census", description: "603,550 men of fighting age counted", reference: "Numbers 1" },
      { order: 2, title: "The Twelve Spies", description: "Ten spies bring bad report; Israel refuses to enter Canaan", reference: "Numbers 13-14" },
      { order: 3, title: "40 years decreed", description: "Whole generation dies in wilderness for unbelief", reference: "Numbers 14" },
      { order: 4, title: "Korah's rebellion", description: "Earth swallows Korah and co-conspirators", reference: "Numbers 16" },
      { order: 5, title: "Bronze serpent", description: "Lifted up to heal bitten Israelites (Jesus cites in John 3:14)", reference: "Numbers 21" },
      { order: 6, title: "Balaam and Balak", description: "Pagan prophet blesses Israel instead of cursing", reference: "Numbers 22-24" },
      { order: 7, title: "Second census", description: "New generation ready to enter Canaan", reference: "Numbers 26" },
    ],
    culturalNotes: [
      { category: "social", title: "Camp organization", content: "Twelve tribes camped in precise order around the tabernacle." },
      { category: "worship", title: "Nazirite vow", content: "Special dedication: no grapes, no haircut, no contact with death (Numbers 6)." },
      { category: "social", title: "Cities of refuge", content: "Six Levitical cities designated as safe havens for accidental killers." },
      { category: "worship", title: "Aaronic blessing", content: "'The LORD bless you and keep you...' still used in synagogues and churches today." },
    ],
    didYouKnow: [
      "The book's name comes from the two censuses taken (1:2; 26:2).",
      "Balaam's donkey is one of only two talking animals in the Bible.",
      "The priestly blessing in Numbers 6:24-26 is the oldest biblical text ever found in archaeology (silver scrolls c.600 BC).",
    ],
  },
];
