import type { OTBookContext } from "../context-types";

export const CONTEXT_JOL_TO_MIC: OTBookContext[] = [
  {
    id: "JOL",
    name: "Joel",
    overview: {
      shortSummary: "Locust plague becomes a warning of the coming Day of the LORD.",
      fullSummary: "Joel interprets a devastating locust plague as a sign of coming divine judgment. He calls for repentance and promises the outpouring of the Spirit on all flesh.",
      themes: ["Day of the LORD", "Repentance", "Outpouring of the Spirit", "Restoration"],
      keyMessages: ["Rend your heart and not your garments", "I will pour out My Spirit on all flesh", "The LORD is a refuge for His people"],
    },
    author: { traditional: "Joel son of Pethuel", notes: "Minor prophet; date debated." },
    timePeriod: {
      eventsDate: "c.835 or c.500 BC (disputed)",
      writingDate: "Same",
      biblicalPlacement: "Minor Prophet",
      relationToEvents: "Immediately after a locust disaster",
    },
    historicalSetting: {
      rulers: ["Unknown"],
      israelKings: [],
      neighboringPowers: ["Tyre", "Philistia", "Greece (mentioned)"],
      politicalBackground: "Addressed Judah at a time of agricultural catastrophe.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Mount Zion, place of deliverance", svgX: 160, svgY: 165 },
      { name: "Valley of Jehoshaphat", type: "region", description: "Final judgment setting", svgX: 162, svgY: 166 },
      { name: "Tyre and Sidon", type: "city", description: "Nations judged for slave trade", svgX: 153, svgY: 140 },
    ],
    genealogy: {
      description: "Minimal genealogical material.",
      nodes: [
        { id: "pethuel", name: "Pethuel" },
        { id: "joel", name: "Joel", parentId: "pethuel" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Locust plague", description: "Four successive waves devour the land", reference: "Joel 1" },
      { order: 2, title: "Call to repent", description: "Gather, fast, cry out", reference: "Joel 2:12-17" },
      { order: 3, title: "Promise of restoration", description: "\"I will restore the years the locusts have eaten\"", reference: "Joel 2:25" },
      { order: 4, title: "Spirit poured out", description: "Prophecy fulfilled at Pentecost", reference: "Joel 2:28-32" },
      { order: 5, title: "Judgment of the nations", description: "Valley of decision", reference: "Joel 3" },
    ],
    culturalNotes: [
      { category: "social", title: "Agricultural disaster", content: "Locust plagues were existential threats in ancient agrarian societies." },
      { category: "customs", title: "Sackcloth and fasting", content: "Communal fasting was the appropriate response to national crisis." },
      { category: "worship", title: "Temple lament", content: "Priests were called to weep between porch and altar." },
      { category: "law", title: "Day of the LORD", content: "A pivotal prophetic concept of climactic divine intervention." },
    ],
    didYouKnow: [
      "Peter quoted Joel 2 in his Pentecost sermon (Acts 2:16-21).",
      "Joel uses four Hebrew words for different locust stages.",
      "The phrase \"Day of the LORD\" appears five times in this short book.",
      "Joel is only three chapters in English (four in Hebrew).",
    ],
  },
  {
    id: "AMO",
    name: "Amos",
    overview: {
      shortSummary: "A shepherd-prophet denounces Israel's complacent injustice.",
      fullSummary: "Amos, a Judean shepherd from Tekoa, traveled north to Bethel to preach. He condemned surrounding nations, then Israel's own idolatry, exploitation, and religious hypocrisy.",
      themes: ["Justice and righteousness", "Social ethics", "Judgment", "God's universal sovereignty"],
      keyMessages: ["Let justice roll down like waters", "Prepare to meet your God", "I hate your feasts without justice"],
    },
    author: { traditional: "Amos", notes: "Shepherd and dresser of sycamore figs." },
    timePeriod: {
      eventsDate: "c.760 BC",
      writingDate: "c.760-755 BC",
      biblicalPlacement: "Minor Prophet",
      relationToEvents: "During Jeroboam II's prosperous reign",
    },
    historicalSetting: {
      rulers: ["Uzziah (Judah)", "Jeroboam II (Israel)"],
      israelKings: ["Jeroboam II"],
      neighboringPowers: ["Aram", "Philistia", "Tyre", "Edom", "Ammon", "Moab"],
      politicalBackground: "Both kingdoms enjoyed peace and wealth but at the cost of rampant injustice.",
    },
    mapLocations: [
      { name: "Tekoa", type: "city", description: "Amos's hometown in Judah", svgX: 160, svgY: 168 },
      { name: "Bethel", type: "city", description: "Northern shrine; center of ministry", svgX: 162, svgY: 158 },
      { name: "Samaria", type: "city", description: "Northern capital denounced", svgX: 158, svgY: 152 },
      { name: "Gilgal", type: "city", description: "Corrupt worship site", svgX: 170, svgY: 165 },
    ],
    genealogy: {
      description: "Simple backstory.",
      nodes: [
        { id: "amos", name: "Amos", notes: "Shepherd and sycamore worker" },
        { id: "amaziah", name: "Amaziah", notes: "Priest who opposed Amos" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Oracles against nations", description: "Judgment on 8 nations including Israel", reference: "Amos 1-2" },
      { order: 2, title: "Cows of Bashan", description: "Rebuke of Samaria's wealthy women", reference: "Amos 4:1-3" },
      { order: 3, title: "Let justice roll", description: "Central call to righteousness", reference: "Amos 5:24" },
      { order: 4, title: "Five visions of judgment", description: "Locusts, fire, plumb line, fruit, altar", reference: "Amos 7-9" },
      { order: 5, title: "Confrontation at Bethel", description: "Amaziah orders Amos to leave", reference: "Amos 7:10-17" },
      { order: 6, title: "Tabernacle of David", description: "Restoration promise", reference: "Amos 9:11-15" },
    ],
    culturalNotes: [
      { category: "social", title: "Economic oppression", content: "Amos condemns selling the poor for silver and trampling the needy." },
      { category: "worship", title: "Empty ritual", content: "God hates feasts detached from justice." },
      { category: "customs", title: "Sycamore figs", content: "A poor man's food; Amos pierced them to ripen." },
      { category: "law", title: "Covenant lawsuit", content: "Amos structures his oracles as a legal indictment." },
    ],
    didYouKnow: [
      "Amos was contemporary with Hosea and Jonah.",
      "James quotes Amos 9:11-12 at the Jerusalem Council (Acts 15).",
      "Martin Luther King Jr. often quoted Amos 5:24.",
      "Amos uses the \"for three sins, even for four\" formula 8 times.",
    ],
  },
  {
    id: "OBA",
    name: "Obadiah",
    overview: {
      shortSummary: "A single-chapter oracle against Edom for gloating over Jerusalem.",
      fullSummary: "Obadiah is the shortest OT book. It condemns Edom (descendants of Esau) for betraying their Israelite brothers during Jerusalem's fall and foretells Edom's destruction and Israel's restoration.",
      themes: ["Divine justice", "Pride brought low", "Day of the LORD", "Restoration"],
      keyMessages: ["As you have done, it shall be done to you", "The kingdom shall be the LORD's"],
    },
    author: { traditional: "Obadiah", notes: "Name means \"servant of the LORD\"; otherwise unknown." },
    timePeriod: {
      eventsDate: "c.586-553 BC (likely)",
      writingDate: "Same",
      biblicalPlacement: "Minor Prophet",
      relationToEvents: "Shortly after Jerusalem's fall",
    },
    historicalSetting: {
      rulers: [],
      israelKings: [],
      neighboringPowers: ["Edom (target)", "Babylon (instrument)"],
      politicalBackground: "Edom helped Babylon and celebrated Jerusalem's fall.",
    },
    mapLocations: [
      { name: "Edom / Mount Seir", type: "region", description: "Target of the oracle", svgX: 170, svgY: 185 },
      { name: "Petra / Sela", type: "city", description: "Edomite rock fortresses", svgX: 172, svgY: 188 },
      { name: "Jerusalem", type: "city", description: "Victim of Edom's betrayal", svgX: 160, svgY: 165 },
      { name: "Mount Zion", type: "city", description: "Future kingdom center", svgX: 160, svgY: 165 },
    ],
    genealogy: {
      description: "Esau-Jacob ancestral conflict.",
      nodes: [
        { id: "isaac", name: "Isaac" },
        { id: "esau", name: "Esau", parentId: "isaac", notes: "Ancestor of Edom" },
        { id: "jacob", name: "Jacob", parentId: "isaac", notes: "Ancestor of Israel" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Edom's pride exposed", description: "Rock dweller will be brought down", reference: "Obadiah 1-4" },
      { order: 2, title: "Betrayal of Jerusalem", description: "Edom gloated and helped destroy", reference: "Obadiah 10-14" },
      { order: 3, title: "Day of the LORD", description: "Universal judgment", reference: "Obadiah 15" },
      { order: 4, title: "Kingdom promised", description: "Mount Zion will rule", reference: "Obadiah 21" },
    ],
    culturalNotes: [
      { category: "social", title: "Tribal enmity", content: "Israel-Edom rivalry ran from Esau and Jacob through Moses to the monarchy." },
      { category: "geography", title: "Rock-cut fortresses", content: "Edomite cities were carved into cliffs, feeling impregnable." },
      { category: "law", title: "Brother's keeper failure", content: "Edom's sin was betraying a brother in distress." },
      { category: "customs", title: "Prophetic oracle", content: "A concentrated oracle against a single nation." },
    ],
    didYouKnow: [
      "Obadiah is the shortest book in the Old Testament (21 verses).",
      "Edom was eventually absorbed by the Nabateans and ceased as a people.",
      "Herod the Great was an Idumean (Edomite descendant).",
      "The book's name means \"servant of Yahweh.\"",
    ],
  },
  {
    id: "JON",
    name: "Jonah",
    overview: {
      shortSummary: "A reluctant prophet flees God's command to preach to Nineveh.",
      fullSummary: "Jonah is commanded to preach to Assyria's Nineveh but flees. A storm, a great fish, a reluctant sermon, and a miraculous repentance follow — then Jonah sulks at God's mercy. The book teaches God's concern for all nations.",
      themes: ["God's mercy", "Mission to the nations", "Running from God", "Repentance"],
      keyMessages: ["Salvation is from the LORD", "God has mercy on whomever He wills", "His pity extends to great cities"],
    },
    author: { traditional: "Jonah son of Amittai", notes: "Prophet from Gath-hepher in Galilee." },
    timePeriod: {
      eventsDate: "c.780-760 BC",
      writingDate: "c.770 BC or later",
      biblicalPlacement: "Minor Prophet; unique narrative form",
      relationToEvents: "Contemporary with Amos",
    },
    historicalSetting: {
      rulers: ["Jeroboam II (Israel)", "Assyrian king (unnamed)"],
      israelKings: ["Jeroboam II"],
      neighboringPowers: ["Assyria (rising threat)"],
      politicalBackground: "Assyria was Israel's feared enemy; Jonah resented God's mercy to a dangerous oppressor.",
    },
    mapLocations: [
      { name: "Gath-hepher", type: "city", description: "Jonah's hometown", svgX: 162, svgY: 147 },
      { name: "Joppa", type: "city", description: "Port of departure", svgX: 152, svgY: 160 },
      { name: "Tarshish (far west)", type: "city", description: "Intended escape", svgX: 60, svgY: 155 },
      { name: "Nineveh", type: "city", description: "Mission destination", svgX: 248, svgY: 128 },
    ],
    genealogy: {
      description: "Prophet's lineage.",
      nodes: [
        { id: "amittai", name: "Amittai" },
        { id: "jonah", name: "Jonah", parentId: "amittai" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Jonah flees", description: "Boards ship to Tarshish", reference: "Jonah 1" },
      { order: 2, title: "Swallowed by great fish", description: "3 days and nights inside", reference: "Jonah 1:17-2:10" },
      { order: 3, title: "Second commission", description: "God commands again", reference: "Jonah 3:1-2" },
      { order: 4, title: "Nineveh repents", description: "King in sackcloth; city saved", reference: "Jonah 3:5-10" },
      { order: 5, title: "Jonah's anger", description: "Protests God's mercy", reference: "Jonah 4:1-3" },
      { order: 6, title: "Plant and worm lesson", description: "God's compassion for the city", reference: "Jonah 4:5-11" },
    ],
    culturalNotes: [
      { category: "geography", title: "Great fish", content: "Hebrew dag gadol — not specifically a whale." },
      { category: "social", title: "Nineveh's size", content: "The city was so great it took three days to traverse." },
      { category: "worship", title: "Sackcloth on animals", content: "Nineveh's repentance even clothed livestock in mourning cloth." },
      { category: "law", title: "Universal concern", content: "Book challenges nationalistic theology." },
    ],
    didYouKnow: [
      "Jesus compared His burial to Jonah's 3 days in the fish (Matt 12:40).",
      "Nineveh fell about 150 years after Jonah, in 612 BC.",
      "Jonah is the only OT prophet Jesus directly compared Himself to.",
      "The book is read in full on Yom Kippur in Jewish tradition.",
    ],
  },
  {
    id: "MIC",
    name: "Micah",
    overview: {
      shortSummary: "Justice, mercy, and humble walk with God — and a Messiah from Bethlehem.",
      fullSummary: "Micah of Moresheth ministered to Judah (with oracles about Israel) during the Assyrian crisis. He denounced corrupt leaders, promised judgment, and foretold the Messiah's birth in Bethlehem.",
      themes: ["Justice", "Humility", "Messianic hope", "Remnant"],
      keyMessages: ["Do justly, love mercy, walk humbly", "From Bethlehem shall come a ruler", "Who is a God like You?"],
    },
    author: { traditional: "Micah", notes: "Contemporary of Isaiah." },
    timePeriod: {
      eventsDate: "c.740-700 BC",
      writingDate: "c.700 BC",
      biblicalPlacement: "Minor Prophet",
      relationToEvents: "During Jotham, Ahaz, Hezekiah",
    },
    historicalSetting: {
      rulers: ["Jotham", "Ahaz", "Hezekiah"],
      israelKings: ["Last northern kings"],
      neighboringPowers: ["Assyria"],
      politicalBackground: "Assyria pressed both kingdoms; Judah's leadership was corrupt.",
    },
    mapLocations: [
      { name: "Moresheth-Gath", type: "city", description: "Micah's hometown", svgX: 152, svgY: 168 },
      { name: "Jerusalem", type: "city", description: "Primary audience", svgX: 160, svgY: 165 },
      { name: "Samaria", type: "city", description: "Subject of early oracles", svgX: 158, svgY: 152 },
      { name: "Bethlehem Ephrathah", type: "city", description: "Messiah's birthplace prophesied", svgX: 160, svgY: 167 },
    ],
    genealogy: {
      description: "Minimal.",
      nodes: [
        { id: "micah", name: "Micah of Moresheth" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Judgment on Samaria and Jerusalem", description: "Prophet's opening indictment", reference: "Micah 1" },
      { order: 2, title: "Woe to land-grabbers", description: "Condemns exploitative rich", reference: "Micah 2" },
      { order: 3, title: "Mountain of the LORD exalted", description: "Nations stream to Zion", reference: "Micah 4:1-5" },
      { order: 4, title: "Messiah from Bethlehem", description: "Ruler from Bethlehem Ephrathah", reference: "Micah 5:2" },
      { order: 5, title: "What the LORD requires", description: "Justice, mercy, humility", reference: "Micah 6:6-8" },
      { order: 6, title: "God's pardoning love", description: "\"Who is a God like You?\"", reference: "Micah 7:18-20" },
    ],
    culturalNotes: [
      { category: "social", title: "Agrarian injustice", content: "Wealthy seized ancestral family lands." },
      { category: "worship", title: "True vs. false worship", content: "Sacrifices without justice are offensive to God." },
      { category: "customs", title: "Prophetic word-plays", content: "Micah uses Hebrew puns on town names throughout chapter 1." },
      { category: "law", title: "Ancient boundary stones", content: "Moving them was a symbol of greed Micah condemns." },
    ],
    didYouKnow: [
      "The magi's priests quoted Micah 5:2 to Herod (Matt 2:5-6).",
      "Micah 4:1-3 parallels Isaiah 2:2-4 almost word for word.",
      "Micah 6:8 is sometimes called the greatest summary of biblical ethics.",
      "Jeremiah's life was spared because elders recalled Micah's precedent (Jer 26:18-19).",
    ],
  },
];
