import type { OTBookContext } from "../context-types";

export const CONTEXT_LAM_TO_HOS: OTBookContext[] = [
  {
    id: "LAM",
    name: "Lamentations",
    overview: {
      shortSummary: "Five acrostic dirges mourning Jerusalem's destruction.",
      fullSummary: "Lamentations is a collection of funeral poems over fallen Jerusalem (586 BC). At the heart stands a confession of hope: \"His mercies are new every morning.\"",
      themes: ["Grief", "Confession", "God's faithful compassion", "Restoration hope"],
      keyMessages: ["Great is Thy faithfulness", "Let us examine our ways", "The LORD is good to those who wait"],
    },
    author: { traditional: "Jeremiah", notes: "Anonymous; Jeremiah's authorship widely held." },
    timePeriod: {
      eventsDate: "586 BC (immediate aftermath)",
      writingDate: "c.586-585 BC",
      biblicalPlacement: "Megilloth; read on 9th of Av",
      relationToEvents: "Written shortly after the fall",
    },
    historicalSetting: {
      rulers: ["Nebuchadnezzar (victor)"],
      israelKings: ["None; monarchy ended"],
      neighboringPowers: ["Babylon, Edom (gloating)"],
      politicalBackground: "Jerusalem's walls breached, temple burned, elite deported.",
    },
    mapLocations: [
      { name: "Jerusalem (destroyed)", type: "battle", description: "Scene of desolation", svgX: 160, svgY: 165 },
      { name: "Temple Mount", type: "city", description: "Burned and ruined", svgX: 160, svgY: 165 },
      { name: "Edom", type: "region", description: "Celebrated Jerusalem's fall", svgX: 170, svgY: 185 },
    ],
    genealogy: {
      description: "Anonymous poet grieves.",
      nodes: [
        { id: "poet", name: "The Poet (likely Jeremiah)", notes: "Eyewitness to fall" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Jerusalem as widow", description: "Desolate and alone", reference: "Lamentations 1" },
      { order: 2, title: "Day of the LORD's anger", description: "The city overthrown", reference: "Lamentations 2" },
      { order: 3, title: "New every morning", description: "Central affirmation of hope", reference: "Lamentations 3:22-24" },
      { order: 4, title: "Horror of the siege", description: "Famine so severe mothers ate children", reference: "Lamentations 4" },
      { order: 5, title: "Final plea", description: "Restore us, O LORD", reference: "Lamentations 5:21" },
    ],
    culturalNotes: [
      { category: "customs", title: "Acrostic poems", content: "Chapters 1, 2, 4 use Hebrew alphabet acrostics; ch. 3 triples each letter." },
      { category: "worship", title: "Public mourning", content: "Ash, sackcloth, torn clothes — standard communal grief." },
      { category: "social", title: "Honest lament", content: "The book models honest grief before God without tidy resolution." },
      { category: "customs", title: "Tisha B'Av", content: "Jews still read Lamentations annually on 9th of Av." },
    ],
    didYouKnow: [
      "The hymn \"Great Is Thy Faithfulness\" comes from Lamentations 3:22-23.",
      "The book's middle chapter (3) is its longest and most hopeful.",
      "Lamentations is the only book entirely composed of laments.",
      "Both temples (586 BC, AD 70) were destroyed on the 9th of Av.",
    ],
  },
  {
    id: "EZK",
    name: "Ezekiel",
    overview: {
      shortSummary: "Exiled priest sees visions of God's glory departing and returning.",
      fullSummary: "Ezekiel, a priest deported to Babylon, had dramatic visions — wheels within wheels, dry bones, a new temple. He ministered to the exiles for about 22 years, proclaiming God's sovereignty and future restoration.",
      themes: ["Glory of God", "Judgment of sin", "Restoration of Israel", "God's sovereignty"],
      keyMessages: ["They will know that I am the LORD", "A new heart and new spirit", "God's glory will return"],
    },
    author: { traditional: "Ezekiel", notes: "Priest deported in 597 BC." },
    timePeriod: {
      eventsDate: "c.593-571 BC",
      writingDate: "c.590-570 BC",
      biblicalPlacement: "Major Prophet",
      relationToEvents: "Contemporary with Jeremiah and Daniel",
    },
    historicalSetting: {
      rulers: ["Nebuchadnezzar", "Jehoiachin (in exile)"],
      israelKings: ["None; Zedekiah last in Jerusalem"],
      neighboringPowers: ["Babylon (captor)", "Egypt", "Tyre", "Edom"],
      politicalBackground: "Ezekiel ministered among the Jewish exiles in Babylon from Tel-abib on the Chebar canal.",
    },
    mapLocations: [
      { name: "Tel-abib (Chebar Canal)", type: "exile", description: "Ezekiel's exile community", svgX: 275, svgY: 175 },
      { name: "Jerusalem", type: "city", description: "Object of many oracles", svgX: 160, svgY: 165 },
      { name: "Tyre", type: "city", description: "Oracle of judgment", svgX: 153, svgY: 140 },
      { name: "Valley of dry bones", type: "region", description: "Vision of Israel's revival", svgX: 275, svgY: 175 },
    ],
    genealogy: {
      description: "Priestly lineage.",
      nodes: [
        { id: "buzi", name: "Buzi (priest)" },
        { id: "ezekiel", name: "Ezekiel", parentId: "buzi", notes: "Priest-prophet" },
        { id: "wife", name: "Ezekiel's wife", notes: "Died as prophetic sign" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Vision by the Chebar", description: "Wheels, living creatures, glory of God", reference: "Ezekiel 1" },
      { order: 2, title: "Eating the scroll", description: "Commissioned as watchman", reference: "Ezekiel 2-3" },
      { order: 3, title: "Glory departs temple", description: "Vision of God leaving Jerusalem", reference: "Ezekiel 10-11" },
      { order: 4, title: "Individual responsibility", description: "Soul that sins shall die", reference: "Ezekiel 18" },
      { order: 5, title: "Oracles against nations", description: "Tyre, Sidon, Egypt", reference: "Ezekiel 25-32" },
      { order: 6, title: "Good Shepherd prophecy", description: "God will shepherd His sheep", reference: "Ezekiel 34" },
      { order: 7, title: "Valley of dry bones", description: "Israel's national resurrection", reference: "Ezekiel 37" },
      { order: 8, title: "New temple vision", description: "Detailed plan of future worship", reference: "Ezekiel 40-48" },
    ],
    culturalNotes: [
      { category: "customs", title: "Prophetic signs", content: "Ezekiel lay on his side 390+40 days, cooked over dung, cut hair — all dramatized prophecies." },
      { category: "worship", title: "Priestly concern with glory", content: "Ezekiel's visions center on God's kabod (weighty glory)." },
      { category: "social", title: "Watchman metaphor", content: "Ezekiel warned that silent prophets bore guilt for others' sins." },
      { category: "law", title: "Personal accountability", content: "Rebuked the proverb that children suffer for parents' sins." },
    ],
    didYouKnow: [
      "Ezekiel was likely around 30 when called (priestly age).",
      "The \"son of man\" title occurs 93 times — Jesus later adopted it.",
      "Gog and Magog (Ezek 38-39) reappear in Revelation 20.",
      "Ezekiel's wife died the day Jerusalem's siege began — as a prophetic sign.",
    ],
  },
  {
    id: "DAN",
    name: "Daniel",
    overview: {
      shortSummary: "Faithfulness in Babylon and visions of future kingdoms.",
      fullSummary: "Daniel and friends keep faith in pagan courts. Chapters 1-6 narrate their trials; chapters 7-12 record visions of world empires rising and falling, ending in God's everlasting kingdom.",
      themes: ["God's sovereignty over kingdoms", "Faithfulness under pressure", "Apocalyptic hope", "Prayer"],
      keyMessages: ["The Most High rules the kingdoms of men", "Dare to be a Daniel", "A kingdom that shall never be destroyed"],
    },
    author: { traditional: "Daniel", notes: "Exilic prince among the Babylonian and Persian courts." },
    timePeriod: {
      eventsDate: "c.605-536 BC",
      writingDate: "c.535 BC",
      biblicalPlacement: "Writings (Hebrew); Major Prophets (English)",
      relationToEvents: "Contemporary with Jeremiah and Ezekiel",
    },
    historicalSetting: {
      rulers: ["Nebuchadnezzar", "Belshazzar", "Darius the Mede", "Cyrus"],
      israelKings: [],
      neighboringPowers: ["Babylon, Medo-Persia"],
      politicalBackground: "Daniel served Babylonian and then Persian courts. His visions foresee Greece and Rome.",
    },
    mapLocations: [
      { name: "Babylon", type: "city", description: "Primary setting", svgX: 272, svgY: 178 },
      { name: "Plain of Dura", type: "city", description: "Fiery furnace", svgX: 274, svgY: 180 },
      { name: "Susa", type: "city", description: "Location of later visions", svgX: 298, svgY: 173 },
      { name: "Media", type: "region", description: "Daniel's vision of ram", svgX: 305, svgY: 155 },
    ],
    genealogy: {
      description: "The four Hebrew youths.",
      nodes: [
        { id: "daniel", name: "Daniel (Belteshazzar)" },
        { id: "hananiah", name: "Hananiah (Shadrach)" },
        { id: "mishael", name: "Mishael (Meshach)" },
        { id: "azariah", name: "Azariah (Abednego)" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Diet refused", description: "Daniel will not defile himself", reference: "Daniel 1" },
      { order: 2, title: "King's dream of statue", description: "Four successive kingdoms", reference: "Daniel 2" },
      { order: 3, title: "Fiery furnace", description: "Three friends delivered", reference: "Daniel 3" },
      { order: 4, title: "Handwriting on the wall", description: "Belshazzar's doom", reference: "Daniel 5" },
      { order: 5, title: "Lions' den", description: "Daniel delivered by God", reference: "Daniel 6" },
      { order: 6, title: "Vision of the four beasts", description: "Empires and Son of Man", reference: "Daniel 7" },
      { order: 7, title: "70 weeks of years", description: "Prophecy of Messiah's coming", reference: "Daniel 9" },
      { order: 8, title: "End-time visions", description: "Final prophecies and resurrection", reference: "Daniel 11-12" },
    ],
    culturalNotes: [
      { category: "social", title: "Court officials", content: "Daniel served at the highest levels of two empires." },
      { category: "customs", title: "Aramaic sections", content: "Daniel 2:4-7:28 is in Aramaic — imperial language of the era." },
      { category: "worship", title: "Windows toward Jerusalem", content: "Daniel prayed 3 times a day facing Jerusalem (Dan 6:10)." },
      { category: "law", title: "Dietary laws", content: "Refusing unclean food was a mark of fidelity under pressure." },
    ],
    didYouKnow: [
      "Daniel likely lived to age 85 or more.",
      "\"Son of Man\" in Daniel 7 is Jesus' favorite self-designation.",
      "Daniel prophesied the exact timing of Messiah's arrival (Dan 9:24-27).",
      "Gabriel appears in Daniel and again at the Annunciation (Luke 1).",
    ],
  },
  {
    id: "HOS",
    name: "Hosea",
    overview: {
      shortSummary: "The prophet's broken marriage mirrors God's love for faithless Israel.",
      fullSummary: "God commanded Hosea to marry a prostitute, Gomer, as a living picture of Israel's unfaithfulness. Hosea preached to the northern kingdom in its final decades, pleading for repentance.",
      themes: ["Covenant loyalty (hesed)", "Spiritual adultery", "God's persistent love", "Judgment and restoration"],
      keyMessages: ["I desire mercy, not sacrifice", "Return to the LORD", "I will heal their apostasy"],
    },
    author: { traditional: "Hosea", notes: "Northern prophet; only Minor Prophet from the northern kingdom." },
    timePeriod: {
      eventsDate: "c.755-710 BC",
      writingDate: "c.710 BC",
      biblicalPlacement: "First of the Minor Prophets",
      relationToEvents: "Contemporary with Amos and Isaiah",
    },
    historicalSetting: {
      rulers: ["Jeroboam II", "last kings of Israel", "Uzziah through Hezekiah (Judah)"],
      israelKings: ["Jeroboam II, Zechariah, Shallum, Menahem, Pekahiah, Pekah, Hoshea"],
      neighboringPowers: ["Assyria (rising)", "Aram"],
      politicalBackground: "Northern kingdom's final decades of political chaos and idolatry before Assyrian conquest.",
    },
    mapLocations: [
      { name: "Samaria", type: "city", description: "Northern capital", svgX: 158, svgY: 152 },
      { name: "Bethel", type: "city", description: "Center of calf worship", svgX: 162, svgY: 158 },
      { name: "Gilgal", type: "city", description: "Corrupt worship site", svgX: 170, svgY: 165 },
      { name: "Valley of Achor", type: "region", description: "\"Door of hope\"", svgX: 168, svgY: 167 },
      { name: "Jezreel", type: "city", description: "Named Hosea's son as sign", svgX: 158, svgY: 148 },
    ],
    genealogy: {
      description: "Hosea's family as prophetic sign.",
      nodes: [
        { id: "hosea", name: "Hosea", notes: "Prophet" },
        { id: "gomer", name: "Gomer", notes: "Wife, unfaithful" },
        { id: "jezreel", name: "Jezreel", parentId: "hosea", notes: "\"God scatters\"" },
        { id: "loruhamah", name: "Lo-Ruhamah", parentId: "hosea", notes: "\"No mercy\"" },
        { id: "loammi", name: "Lo-Ammi", parentId: "hosea", notes: "\"Not My people\"" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Marriage to Gomer", description: "Prophetic sign of Israel's unfaithfulness", reference: "Hosea 1" },
      { order: 2, title: "Names of the children", description: "Each name proclaims judgment", reference: "Hosea 1:4-9" },
      { order: 3, title: "Redeeming Gomer", description: "Hosea buys his wife back from slavery", reference: "Hosea 3" },
      { order: 4, title: "Indictment of Israel", description: "No faithfulness, no love, no knowledge of God", reference: "Hosea 4" },
      { order: 5, title: "Call to return", description: "\"Come, let us return to the LORD\"", reference: "Hosea 6:1-3" },
      { order: 6, title: "Promise of healing", description: "\"I will heal their apostasy\"", reference: "Hosea 14:4" },
    ],
    culturalNotes: [
      { category: "worship", title: "Baal worship", content: "Fertility cult worship with sexual elements permeated Israel." },
      { category: "customs", title: "Bride-price", content: "Hosea paid 15 shekels + barley for Gomer — a slave's price." },
      { category: "social", title: "Political chaos", content: "Four kings of Israel assassinated in Hosea's lifetime." },
      { category: "law", title: "Marriage as covenant", content: "Hosea reinforces marriage as a covenant mirror of God's relationship with Israel." },
    ],
    didYouKnow: [
      "Paul quotes Hosea 1-2 to explain Gentile inclusion (Rom 9:25-26).",
      "\"I desire mercy, not sacrifice\" (Hos 6:6) is quoted twice by Jesus.",
      "Hosea's name means \"salvation\" — same Hebrew root as Joshua/Jesus.",
      "Hosea ministered 60+ years, the longest northern prophetic ministry.",
    ],
  },
];
