import type { OTBookContext } from "../context-types";

export const CONTEXT_1TI_TO_PHM: OTBookContext[] = [
  {
    id: "1TI",
    name: "1 Timothy",
    overview: {
      shortSummary: "Paul's manual for church order — sound doctrine, qualified leaders, true godliness.",
      fullSummary: "Paul left Timothy in Ephesus to correct false teachers and establish proper church order. The letter covers qualifications for overseers and deacons, prayer, women in worship, care for widows and elders, and warnings about love of money.",
      themes: ["Sound doctrine", "Church leadership", "Godliness", "Prayer", "False teaching"],
      keyMessages: ["Fight the good fight of faith", "Godliness with contentment is great gain", "The saying is trustworthy: Christ Jesus came to save sinners"],
    },
    author: { traditional: "Paul the Apostle", notes: "One of the Pastoral Epistles; written c.AD 62-66." },
    timePeriod: { eventsDate: "c.AD 62-66", writingDate: "c.AD 62-66", biblicalPlacement: "Fifteenth NT book; Pastoral Epistle", relationToEvents: "Written after Paul's first Roman imprisonment" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "False teachers in Ephesus mixed Jewish genealogies, myths, and proto-Gnostic ideas with Christianity.",
    },
    mapLocations: [
      { name: "Ephesus", type: "city", description: "Where Timothy was stationed", svgX: 112, svgY: 150 },
      { name: "Macedonia", type: "region", description: "Where Paul went; wrote from there", svgX: 108, svgY: 155 },
    ],
    genealogy: {
      description: "Paul's pastoral team.",
      nodes: [
        { id: "paul", name: "Paul", notes: "Apostle and mentor" },
        { id: "timothy", name: "Timothy", notes: "Paul's true son in faith; stationed in Ephesus" },
        { id: "eunice", name: "Eunice", notes: "Timothy's mother" },
        { id: "lois", name: "Lois", notes: "Timothy's grandmother" },
        { id: "hymenaeus", name: "Hymenaeus", notes: "False teacher" },
        { id: "alexander", name: "Alexander", notes: "False teacher" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Charge to Timothy", description: "Stay and correct false teachers", reference: "1 Timothy 1:3-7" },
      { order: 2, title: "Paul's testimony", description: "Chief of sinners saved by grace", reference: "1 Timothy 1:12-17" },
      { order: 3, title: "Prayer for all people", description: "God desires all to be saved", reference: "1 Timothy 2:1-6" },
      { order: 4, title: "Overseer qualifications", description: "Above reproach, husband of one wife...", reference: "1 Timothy 3:1-7" },
      { order: 5, title: "Deacon qualifications", description: "Tested and found blameless", reference: "1 Timothy 3:8-13" },
      { order: 6, title: "Care for widows", description: "Honor those who are truly widows", reference: "1 Timothy 5" },
      { order: 7, title: "Fight the good fight", description: "Lay hold of eternal life", reference: "1 Timothy 6:12" },
    ],
    culturalNotes: [
      { category: "worship", title: "Elder/overseer", content: "Episkopos (bishop) and presbuteros (elder) describe the same role in the Pastorals." },
      { category: "social", title: "Honor for widows", content: "Widows with no family had no social safety net; the church was to care for them." },
      { category: "law", title: "Love of money", content: "1 Tim 6:10 says the love (not money itself) is a root of all kinds of evil." },
      { category: "customs", title: "Laying on of hands", content: "Ordination of church leaders marked by this ancient commissioning practice." },
    ],
    didYouKnow: [
      "The Pastoral Epistles (1-2 Tim, Titus) are the only NT letters addressed to individuals in church leadership.",
      "1 Timothy 2:5 — 'one mediator between God and men, the man Christ Jesus' — is a core atonement text.",
      "Timothy was the son of a Jewish mother and Greek father — a bridge between cultures.",
      "Paul calls Timothy his 'true child in the faith' — their relationship spanned 15+ years.",
    ],
  },
  {
    id: "2TI",
    name: "2 Timothy",
    overview: {
      shortSummary: "Paul's final letter — a charge to Timothy to endure, preach the Word, and finish the race.",
      fullSummary: "2 Timothy is Paul's last known letter, written from prison facing execution under Nero. It is deeply personal — Paul is lonely, cold, and forsaken by many. He urges Timothy to come, to guard the gospel, and to preach the Word in season and out.",
      themes: ["Endurance", "Guarding the gospel", "Scripture's authority", "Finishing well"],
      keyMessages: ["Preach the Word in season and out of season", "All Scripture is God-breathed", "I have fought the good fight; I have finished the race"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Rome, c.AD 67-68, shortly before Paul's execution." },
    timePeriod: { eventsDate: "c.AD 67-68", writingDate: "c.AD 67-68", biblicalPlacement: "Sixteenth NT book; Paul's farewell letter", relationToEvents: "Paul's final imprisonment under Nero" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "After Rome's fire (AD 64), Nero blamed Christians; systematic persecution began. Paul was re-arrested and faced death.",
    },
    mapLocations: [
      { name: "Rome", type: "city", description: "Paul's final imprisonment", svgX: 58, svgY: 148 },
      { name: "Ephesus", type: "city", description: "Timothy's location", svgX: 112, svgY: 150 },
      { name: "Troas", type: "city", description: "Paul left cloak and scrolls there", svgX: 118, svgY: 148 },
    ],
    genealogy: {
      description: "Paul's inner circle at the end.",
      nodes: [
        { id: "paul", name: "Paul", notes: "Facing execution" },
        { id: "timothy", name: "Timothy", notes: "Urged to come before winter" },
        { id: "luke", name: "Luke", notes: "Only Paul's companion at end" },
        { id: "mark", name: "Mark", notes: "Paul asks for him" },
        { id: "demas", name: "Demas", notes: "Deserted for love of the world" },
        { id: "onesiphorus", name: "Onesiphorus", notes: "Sought Paul out; not ashamed" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Fan into flame", description: "Stir up the gift of God; not a spirit of timidity", reference: "2 Timothy 1:6-7" },
      { order: 2, title: "Guard the deposit", description: "By the Spirit guard the good deposit", reference: "2 Timothy 1:14" },
      { order: 3, title: "Endure as a soldier", description: "Soldier, athlete, farmer — three metaphors for ministry", reference: "2 Timothy 2:1-7" },
      { order: 4, title: "All Scripture God-breathed", description: "Profitable for doctrine, correction, training in righteousness", reference: "2 Timothy 3:16-17" },
      { order: 5, title: "Preach the Word", description: "In season and out; the time is coming when people won't endure sound doctrine", reference: "2 Timothy 4:1-5" },
      { order: 6, title: "Paul's farewell", description: "I have fought the good fight; a crown awaits", reference: "2 Timothy 4:6-8" },
    ],
    culturalNotes: [
      { category: "worship", title: "God-breathed (theopneustos)", content: "Only occurrence in the NT of this word; all Scripture has divine breath in it." },
      { category: "social", title: "Parchments", content: "Paul asked for his parchments (possibly OT scrolls or Jesus' words)." },
      { category: "customs", title: "Roman execution", content: "Paul was likely beheaded (as a Roman citizen) on the Ostian Way outside Rome." },
      { category: "law", title: "Crown of righteousness", content: "Paul anticipates the victor's wreath — eternal reward for faithful service." },
    ],
    didYouKnow: [
      "2 Timothy 3:16-17 is the foundational text for the doctrine of biblical inspiration.",
      "Paul's mention of needing his cloak suggests he wrote in a cold, damp prison cell.",
      "Demas is mentioned in Colossians as a faithful coworker; here he has defected.",
      "Paul was likely executed c.AD 67-68, probably by Nero's order.",
    ],
  },
  {
    id: "TIT",
    name: "Titus",
    overview: {
      shortSummary: "Paul's instructions to Titus for establishing order in the Cretan churches.",
      fullSummary: "Paul left Titus in Crete to appoint elders and correct false teachers. The letter emphasizes sound doctrine producing good works, with a striking passage on God's grace that trains us to say no to ungodliness.",
      themes: ["Sound doctrine and good works", "Church order", "Grace that trains", "Godly living"],
      keyMessages: ["The grace of God trains us to say no to ungodliness", "Be ready for every good work", "Our great God and Savior Jesus Christ"],
    },
    author: { traditional: "Paul the Apostle", notes: "Pastoral Epistle; written c.AD 62-66." },
    timePeriod: { eventsDate: "c.AD 62-66", writingDate: "c.AD 62-66", biblicalPlacement: "Seventeenth NT book; Pastoral Epistle", relationToEvents: "After Paul's release from first Roman imprisonment" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Crete had a mixed Jewish and pagan population; the churches needed structure and correction from Jewish-influenced false teachers.",
    },
    mapLocations: [
      { name: "Crete", type: "region", description: "Titus's field of ministry", svgX: 118, svgY: 178 },
      { name: "Nicopolis", type: "city", description: "Where Paul planned to winter", svgX: 105, svgY: 162 },
    ],
    genealogy: {
      description: "Key figures.",
      nodes: [
        { id: "paul", name: "Paul" },
        { id: "titus", name: "Titus", notes: "Paul's true child; left in Crete" },
        { id: "artemas", name: "Artemas", notes: "To replace Titus" },
        { id: "zenas", name: "Zenas", notes: "Lawyer; to be helped on journey" },
        { id: "apollos", name: "Apollos", notes: "Traveling with Zenas" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Appoint elders", description: "Blameless, one wife, believing children...", reference: "Titus 1:5-9" },
      { order: 2, title: "Rebuke false teachers", description: "Especially Jewish circumcision party", reference: "Titus 1:10-16" },
      { order: 3, title: "Older and younger taught", description: "Sound in faith; self-controlled; pure", reference: "Titus 2:1-8" },
      { order: 4, title: "Grace that trains", description: "Denying ungodliness; looking for the blessed hope", reference: "Titus 2:11-14" },
      { order: 5, title: "Justified by grace", description: "Heirs according to the hope of eternal life", reference: "Titus 3:4-7" },
    ],
    culturalNotes: [
      { category: "social", title: "Cretans' reputation", content: "Paul quotes a Cretan poet calling Cretans 'always liars, evil beasts, lazy gluttons' — the stereotype was known even locally." },
      { category: "worship", title: "Savior God", content: "Titus applies 'Savior' to both God the Father (1:3) and Jesus Christ (1:4, 2:13) — high Christology." },
      { category: "law", title: "Good works", content: "Titus uses 'good works' more per verse than any other NT letter — grace produces works." },
      { category: "customs", title: "Genealogies and myths", content: "Jewish teachers in Crete promoted endless genealogies; Paul calls them unprofitable." },
    ],
    didYouKnow: [
      "Titus 2:13 calls Jesus 'our great God and Savior' — one of the clearest NT deity statements.",
      "Crete is one of the oldest locations of Christian mission in the Mediterranean.",
      "Titus is never mentioned in Acts despite appearing in Paul's letters as a key coworker.",
      "Paul's 'faithful saying' in Titus 3:8 summarizes the gospel's practical implications.",
    ],
  },
  {
    id: "PHM",
    name: "Philemon",
    overview: {
      shortSummary: "Paul appeals to Philemon to receive the runaway slave Onesimus as a brother.",
      fullSummary: "Philemon is Paul's shortest letter — a masterpiece of Christian diplomacy. Onesimus, a runaway slave, had been converted by Paul in Rome. Paul appeals to his owner, Philemon, to receive him back not as a slave but as a beloved brother in Christ.",
      themes: ["Reconciliation", "Christian brotherhood", "Grace transforming social structures", "Forgiveness"],
      keyMessages: ["Receive him as you would receive me", "No longer as a slave but as a dear brother", "Charge it to my account"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Rome, c.AD 60-62." },
    timePeriod: { eventsDate: "c.AD 60-62", writingDate: "c.AD 60-62", biblicalPlacement: "Eighteenth NT book; shortest Pauline letter", relationToEvents: "Written alongside Colossians from prison" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Roman law allowed execution of runaway slaves. Paul navigates this carefully, appealing to Christian love rather than commanding.",
    },
    mapLocations: [
      { name: "Colossae", type: "city", description: "Philemon's home church", svgX: 130, svgY: 152 },
      { name: "Rome", type: "city", description: "Paul's imprisonment; where Onesimus converted", svgX: 58, svgY: 148 },
    ],
    genealogy: {
      description: "The three key figures.",
      nodes: [
        { id: "paul", name: "Paul", notes: "Writes from prison; spiritual father" },
        { id: "philemon", name: "Philemon", notes: "Slave owner; church host" },
        { id: "onesimus", name: "Onesimus", notes: "Runaway slave; converted" },
        { id: "apphia", name: "Apphia", notes: "Philemon's wife" },
        { id: "archippus", name: "Archippus", notes: "Fellow soldier" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Thanksgiving for Philemon", description: "Faith and love refreshing hearts of saints", reference: "Philemon 4-7" },
      { order: 2, title: "The appeal", description: "Paul appeals rather than commands", reference: "Philemon 8-9" },
      { order: 3, title: "Onesimus introduced", description: "My child whom I begat in chains; formerly useless", reference: "Philemon 10-11" },
      { order: 4, title: "Receive him as me", description: "Welcome him as you would welcome me", reference: "Philemon 17" },
      { order: 5, title: "Charge it to my account", description: "Paul pays the debt; a picture of atonement", reference: "Philemon 18-19" },
    ],
    culturalNotes: [
      { category: "social", title: "Slavery in Rome", content: "Approximately one third of Rome's population were slaves; a runaway could be branded or crucified." },
      { category: "law", title: "Paul's diplomacy", content: "Paul does not directly condemn slavery but subverts it by calling Onesimus a brother." },
      { category: "customs", title: "Imputed debt", content: "Paul's offer to pay Onesimus's debt is widely seen as a picture of Christ's atonement." },
      { category: "social", title: "Letter of recommendation", content: "Ancient travelers carried such letters; Paul writes one for Onesimus." },
    ],
    didYouKnow: [
      "Philemon is the only private letter in the NT.",
      "Onesimus means 'useful' in Greek — Paul's wordplay on 'formerly useless, now useful' is intentional.",
      "Ignatius of Antioch mentions a bishop of Ephesus named Onesimus — possibly the same man.",
      "The letter is only 25 verses but has shaped Christian thinking on slavery and brotherhood for 2000 years.",
    ],
  },
];
