import type { OTBookContext } from "../context-types";

export const CONTEXT_ACT_TO_2CO: OTBookContext[] = [
  {
    id: "ACT",
    name: "Acts",
    overview: {
      shortSummary: "The Holy Spirit's power launches the church from Jerusalem to Rome.",
      fullSummary: "Acts is Luke's second volume, tracing the gospel's spread from Jerusalem through Judea, Samaria, and to the ends of the earth. It features Pentecost, the Jerusalem church, Paul's three missionary journeys, and his voyage to Rome.",
      themes: ["Holy Spirit", "Mission", "Church growth", "Witness", "Persecution and victory"],
      keyMessages: ["You will receive power when the Holy Spirit comes", "Repent and be baptized", "To the ends of the earth"],
    },
    author: { traditional: "Luke, companion of Paul", notes: "Continues directly from the Gospel of Luke." },
    timePeriod: {
      eventsDate: "c.AD 30-62",
      writingDate: "c.AD 62",
      biblicalPlacement: "Second volume of Luke-Acts; bridge to the Epistles",
      relationToEvents: "Ends abruptly with Paul in Rome, suggesting written before his trial outcome",
    },
    historicalSetting: {
      rulers: ["Tiberius", "Caligula", "Claudius", "Nero", "Herod Agrippa I & II", "Felix", "Festus"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "The church spread throughout the Roman Empire, using Roman roads and trade routes. Roman citizenship (like Paul's) provided legal protection.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "Pentecost; early church; councils", svgX: 160, svgY: 165 },
      { name: "Antioch (Syria)", type: "city", description: "First called Christians; Paul's sending church", svgX: 205, svgY: 122 },
      { name: "Ephesus", type: "city", description: "Three years of Paul's ministry", svgX: 112, svgY: 150 },
      { name: "Corinth", type: "city", description: "18 months of ministry", svgX: 102, svgY: 165 },
      { name: "Athens", type: "city", description: "Areopagus speech", svgX: 105, svgY: 168 },
      { name: "Philippi", type: "city", description: "Lydia; prison earthquake", svgX: 105, svgY: 152 },
      { name: "Rome", type: "city", description: "Paul arrives under house arrest", svgX: 58, svgY: 148 },
    ],
    genealogy: {
      description: "Key apostles and leaders of the early church.",
      nodes: [
        { id: "peter", name: "Peter", notes: "Leader of Jerusalem church" },
        { id: "james", name: "James (Lord's brother)", notes: "Elder of Jerusalem" },
        { id: "stephen", name: "Stephen", notes: "First martyr" },
        { id: "philip", name: "Philip the Evangelist", notes: "Spread gospel to Samaria and Ethiopia" },
        { id: "saul", name: "Saul/Paul", notes: "Apostle to Gentiles" },
        { id: "barnabas", name: "Barnabas", notes: "Paul's first partner" },
        { id: "silas", name: "Silas/Silvanus", notes: "Paul's second journey partner" },
        { id: "timothy", name: "Timothy", notes: "Paul's protégé" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Ascension and Pentecost", description: "Holy Spirit poured out; 3000 saved", reference: "Acts 1-2" },
      { order: 2, title: "Early Jerusalem church", description: "Signs, sharing, growth, persecution", reference: "Acts 3-7" },
      { order: 3, title: "Stephen martyred", description: "First Christian martyr; Saul consents", reference: "Acts 7" },
      { order: 4, title: "Paul's conversion", description: "Blinded on Damascus road; transformed", reference: "Acts 9" },
      { order: 5, title: "Peter and Cornelius", description: "Gospel goes to Gentiles", reference: "Acts 10" },
      { order: 6, title: "First missionary journey", description: "Cyprus, Galatia, Lystra", reference: "Acts 13-14" },
      { order: 7, title: "Jerusalem Council", description: "Gentiles not bound by Mosaic law", reference: "Acts 15" },
      { order: 8, title: "Second and third journeys", description: "Greece, Ephesus, Macedonia", reference: "Acts 16-20" },
      { order: 9, title: "Paul arrested, voyage to Rome", description: "Shipwreck, Malta, Rome", reference: "Acts 21-28" },
    ],
    culturalNotes: [
      { category: "customs", title: "Roman roads", content: "The Via Egnatia, Via Appia, and other Roman highways enabled rapid gospel spread." },
      { category: "social", title: "Synagogues as base", content: "Paul always went to the synagogue first in each new city." },
      { category: "law", title: "Roman citizenship", content: "Paul invoked his citizenship to escape flogging and appeal to Caesar." },
      { category: "worship", title: "Speaking in tongues", content: "At Pentecost, Jews from many nations heard in their own languages." },
    ],
    didYouKnow: [
      "Acts mentions over 30 cities, most confirmed archaeologically.",
      "The word 'Christian' was first used at Antioch (Acts 11:26).",
      "Paul planted churches in major cities on purpose — strategic urban mission.",
      "Acts ends without recording Paul's death, suggesting Luke wrote before it happened.",
    ],
  },
  {
    id: "ROM",
    name: "Romans",
    overview: {
      shortSummary: "Paul's masterwork on the gospel: all are guilty, all can be justified by faith.",
      fullSummary: "Romans is the most systematic NT letter. Paul explains that all humanity is condemned under sin, that justification comes through faith in Christ alone, that God's righteousness is revealed through the gospel, and that this transforms life and community.",
      themes: ["Righteousness of God", "Justification by faith", "Sin", "Law and grace", "Election", "Christian ethics"],
      keyMessages: ["The just shall live by faith", "All have sinned", "There is therefore now no condemnation", "By grace through faith"],
    },
    author: { traditional: "Paul the Apostle", notes: "Dictated to Tertius (Rom 16:22) from Corinth, c.AD 57." },
    timePeriod: {
      eventsDate: "c.AD 57",
      writingDate: "c.AD 57",
      biblicalPlacement: "First of Paul's epistles in canon; longest",
      relationToEvents: "Written before Paul visited Rome; to prepare the church for his coming",
    },
    historicalSetting: {
      rulers: ["Nero (early, relatively tolerant reign)"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Roman church had both Jewish and Gentile members, with tension after Jews were expelled then allowed to return under Claudius/Nero.",
    },
    mapLocations: [
      { name: "Rome", type: "city", description: "Recipient church; Paul's destination", svgX: 58, svgY: 148 },
      { name: "Corinth", type: "city", description: "Where Paul wrote Romans", svgX: 102, svgY: 165 },
      { name: "Jerusalem", type: "city", description: "Paul planning to deliver collection there", svgX: 160, svgY: 165 },
    ],
    genealogy: {
      description: "Paul traces redemptive history through Adam and Christ.",
      nodes: [
        { id: "adam", name: "Adam", notes: "Through him sin entered; condemnation" },
        { id: "abraham", name: "Abraham", notes: "Justified by faith before circumcision" },
        { id: "david", name: "David", notes: "Blessed without works (Ps 32)" },
        { id: "christ", name: "Jesus Christ", notes: "Second Adam; through Him justification" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Universal condemnation", description: "Gentiles and Jews both guilty before God", reference: "Romans 1-3" },
      { order: 2, title: "Justification by faith", description: "Abraham believed and it was credited as righteousness", reference: "Romans 3-4" },
      { order: 3, title: "Peace with God", description: "Reconciled through Christ's death", reference: "Romans 5" },
      { order: 4, title: "Dead to sin, alive in Christ", description: "Union with Christ in death and resurrection", reference: "Romans 6" },
      { order: 5, title: "The struggle within", description: "\"The good I want to do, I don't do\"", reference: "Romans 7" },
      { order: 6, title: "Life in the Spirit", description: "No condemnation; Abba Father; future glory", reference: "Romans 8" },
      { order: 7, title: "Israel and the Gentiles", description: "God's faithfulness to Israel; mystery of salvation", reference: "Romans 9-11" },
      { order: 8, title: "Living sacrifice", description: "Be transformed by renewing your mind", reference: "Romans 12-15" },
    ],
    culturalNotes: [
      { category: "law", title: "Imputed righteousness", content: "God counts Christ's righteousness to the believer's account — a forensic declaration." },
      { category: "worship", title: "Doxologies", content: "Paul bursts into worship three times (3:23-25; 8:31-39; 11:33-36)." },
      { category: "social", title: "Jewish-Gentile tensions", content: "Romans 14-15 addresses eating meat sacrificed to idols and Sabbath observance." },
      { category: "customs", title: "Letter form", content: "Follows Greco-Roman letter conventions: sender, recipient, greeting, body, closing." },
    ],
    didYouKnow: [
      "Romans sparked the conversions of Augustine (386), Luther (1515), and Wesley (1738).",
      "Romans 8:28-39 is considered one of the greatest passages in all of Scripture.",
      "Paul had never visited Rome when he wrote this letter.",
      "Romans 16 greets 26 individuals by name — remarkable for a church Paul hadn't visited.",
    ],
  },
  {
    id: "1CO",
    name: "1 Corinthians",
    overview: {
      shortSummary: "Paul addresses a divided, immoral, and confused church with wisdom from the cross.",
      fullSummary: "Corinth was the most cosmopolitan city of Greece. The church there had serious problems: divisions, sexual immorality, lawsuits, idol food, spiritual gifts abuse, and denial of resurrection. Paul answers every issue with the wisdom of the cross.",
      themes: ["Unity in Christ", "Sexual ethics", "Spiritual gifts", "Resurrection", "The cross as wisdom"],
      keyMessages: ["Christ crucified — the power and wisdom of God", "Love is the greatest", "Your body is a temple of the Spirit"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Ephesus, c.AD 54-55." },
    timePeriod: {
      eventsDate: "c.AD 54-55",
      writingDate: "c.AD 54-55",
      biblicalPlacement: "Sixth NT book; first Corinthian letter",
      relationToEvents: "Written in response to reports and questions from the Corinthian church",
    },
    historicalSetting: {
      rulers: ["Claudius (or early Nero)"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Corinth was a Roman colony and major port city — wealthy, multicultural, morally permissive, known for temple prostitution.",
    },
    mapLocations: [
      { name: "Corinth", type: "city", description: "Recipient church; Paul spent 18 months here", svgX: 102, svgY: 165 },
      { name: "Ephesus", type: "city", description: "Where Paul wrote 1 Corinthians", svgX: 112, svgY: 150 },
      { name: "Cenchreae", type: "city", description: "Eastern port of Corinth", svgX: 104, svgY: 167 },
    ],
    genealogy: {
      description: "Church factions and key figures.",
      nodes: [
        { id: "paul", name: "Paul", notes: "Founded the Corinthian church" },
        { id: "apollos", name: "Apollos", notes: "Eloquent teacher; party rivalry" },
        { id: "peter", name: "Peter (Cephas)", notes: "Another party rallied around him" },
        { id: "chloe", name: "Chloe's people", notes: "Reported divisions to Paul" },
        { id: "stephanas", name: "Stephanas", notes: "First Corinthian convert" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Divisions rebuked", description: "Is Christ divided? Not Paul, Apollos, or Cephas", reference: "1 Corinthians 1-4" },
      { order: 2, title: "Sexual immorality addressed", description: "Incest tolerated; flee sexual sin", reference: "1 Corinthians 5-6" },
      { order: 3, title: "Marriage and singleness", description: "Paul's teaching on celibacy and marriage", reference: "1 Corinthians 7" },
      { order: 4, title: "Food sacrificed to idols", description: "Knowledge puffs up; love builds up", reference: "1 Corinthians 8-10" },
      { order: 5, title: "Lord's Supper corrected", description: "Eating and drinking judgment", reference: "1 Corinthians 11" },
      { order: 6, title: "Spiritual gifts ordered", description: "Body metaphor; tongues, prophecy, love", reference: "1 Corinthians 12-14" },
      { order: 7, title: "Love chapter", description: "\"Love never fails\"", reference: "1 Corinthians 13" },
      { order: 8, title: "Resurrection defended", description: "If Christ is not raised, your faith is futile", reference: "1 Corinthians 15" },
    ],
    culturalNotes: [
      { category: "social", title: "Greco-Roman rhetoric", content: "Corinthians prized eloquent speakers; Paul deliberately refused to impress (2:1-5)." },
      { category: "worship", title: "Temple of Aphrodite", content: "Corinth's pagan temple had ritual prostitution; sexual ethics were countercultural." },
      { category: "customs", title: "Head coverings", content: "1 Cor 11 addresses worship practices tied to Roman social honor customs." },
      { category: "law", title: "Lawsuits before pagans", content: "Paul rebukes Corinthians for suing each other in Roman courts." },
    ],
    didYouKnow: [
      "Paul's 'love chapter' (1 Cor 13) was written to a church famous for fighting, not loving.",
      "1 Corinthians 15 is the earliest written account of Jesus' resurrection appearances (c.AD 54).",
      "Corinth was destroyed in 146 BC, then rebuilt by Julius Caesar in 44 BC as a Roman colony.",
      "Paul likely wrote at least 4 letters to Corinth; only 2 survive.",
    ],
  },
  {
    id: "2CO",
    name: "2 Corinthians",
    overview: {
      shortSummary: "Paul's most personal letter — defending his ministry and revealing his heart.",
      fullSummary: "2 Corinthians is Paul's most autobiographical epistle. He defends his apostolic authority against 'super-apostles', describes his sufferings, explains the new covenant ministry, and appeals for the Jerusalem collection. Strength through weakness is its central paradox.",
      themes: ["Apostolic suffering", "New covenant ministry", "Strength in weakness", "Reconciliation", "Generosity"],
      keyMessages: ["My grace is sufficient for you", "When I am weak, then I am strong", "God was reconciling the world to Himself"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Macedonia, c.AD 55-56." },
    timePeriod: {
      eventsDate: "c.AD 55-56",
      writingDate: "c.AD 55-56",
      biblicalPlacement: "Seventh NT book",
      relationToEvents: "Written after a painful visit and a severe letter to Corinth",
    },
    historicalSetting: {
      rulers: ["Nero (early reign)"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Jewish-Christian 'super-apostles' had arrived in Corinth undermining Paul's authority and demanding letters of recommendation.",
    },
    mapLocations: [
      { name: "Macedonia", type: "region", description: "Where Paul wrote 2 Corinthians", svgX: 108, svgY: 155 },
      { name: "Corinth", type: "city", description: "Recipient church", svgX: 102, svgY: 165 },
      { name: "Troas", type: "city", description: "Paul's anxiety waiting for Titus", svgX: 118, svgY: 148 },
    ],
    genealogy: {
      description: "Key figures in the conflict.",
      nodes: [
        { id: "paul", name: "Paul" },
        { id: "titus", name: "Titus", notes: "Paul's envoy to Corinth" },
        { id: "timothy", name: "Timothy", notes: "Co-sender" },
        { id: "superapostles", name: "Super-apostles", notes: "False teachers attacking Paul" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Comfort in suffering", description: "God comforts us so we comfort others", reference: "2 Corinthians 1" },
      { order: 2, title: "New covenant ministry", description: "Letters written on hearts; unveiled faces", reference: "2 Corinthians 3" },
      { order: 3, title: "Treasure in jars of clay", description: "Power from God, not us", reference: "2 Corinthians 4" },
      { order: 4, title: "Ministry of reconciliation", description: "Ambassadors for Christ; be reconciled to God", reference: "2 Corinthians 5" },
      { order: 5, title: "Cheerful giving", description: "God loves a cheerful giver", reference: "2 Corinthians 9" },
      { order: 6, title: "Paul's boasting in weakness", description: "Thorn in flesh; \"My grace is sufficient\"", reference: "2 Corinthians 11-12" },
    ],
    culturalNotes: [
      { category: "customs", title: "Letters of recommendation", content: "Traveling teachers carried letters vouching for their authenticity; Paul's letter was the Corinthians themselves." },
      { category: "social", title: "Triumphal procession", content: "Paul uses the image of a Roman triumph (2:14) — captives led in the victor's parade." },
      { category: "worship", title: "Heavenly vision", content: "Paul's description of being caught to the third heaven (12:2) is unique in the NT." },
      { category: "law", title: "Grace giving", content: "Paul's collection for Jerusalem modeled voluntary, joyful giving — not law-based tithing." },
    ],
    didYouKnow: [
      "2 Corinthians 5:17 — 'new creation' — is foundational to Christian identity.",
      "Paul lists his sufferings in 11:23-29 — among the most remarkable autobiographical passages in the Bible.",
      "The 'thorn in the flesh' has been debated for 2000 years; Paul never identifies it.",
      "Paul's sarcastic 'boasting' section (11-12) uses irony to expose false boasting.",
    ],
  },
];
