import type { OTBookContext } from "../context-types";

export const CONTEXT_GAL_TO_COL: OTBookContext[] = [
  {
    id: "GAL",
    name: "Galatians",
    overview: {
      shortSummary: "Paul's fiery defense of salvation by grace alone through faith alone.",
      fullSummary: "Galatians is Paul's most polemical letter. False teachers (Judaizers) were insisting Gentile converts must be circumcised and keep the Mosaic law. Paul defends the gospel of grace and Christian freedom with passionate urgency.",
      themes: ["Justification by faith alone", "Christian freedom", "Law vs. grace", "Fruit of the Spirit"],
      keyMessages: ["A man is not justified by the law but by faith in Christ", "It is for freedom that Christ set you free", "Walk by the Spirit"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written c.AD 48-49 (South Galatia view) — possibly Paul's earliest letter." },
    timePeriod: {
      eventsDate: "c.AD 48-49 or 55",
      writingDate: "Same",
      biblicalPlacement: "Ninth NT book; before or after Jerusalem Council",
      relationToEvents: "Written in crisis to churches under attack from Judaizers",
    },
    historicalSetting: {
      rulers: ["Claudius Caesar"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Jewish-Christian teachers followed Paul into Galatia insisting Gentiles must be circumcised to be fully saved.",
    },
    mapLocations: [
      { name: "Galatia (region)", type: "region", description: "Recipient churches in central Asia Minor", svgX: 145, svgY: 140 },
      { name: "Antioch (Syria)", type: "city", description: "Where Paul confronted Peter publicly", svgX: 205, svgY: 122 },
      { name: "Jerusalem", type: "city", description: "Where Paul met the apostles", svgX: 160, svgY: 165 },
      { name: "Arabia", type: "region", description: "Paul's post-conversion retreat", svgX: 200, svgY: 200 },
    ],
    genealogy: {
      description: "Key figures in the Galatian controversy.",
      nodes: [
        { id: "paul", name: "Paul", notes: "Apostle to the Gentiles" },
        { id: "peter", name: "Peter", notes: "Confronted by Paul at Antioch" },
        { id: "james", name: "James", notes: "Lord's brother; pillar apostle" },
        { id: "barnabas", name: "Barnabas", notes: "Swept along by hypocrisy" },
        { id: "judaizers", name: "Judaizers", notes: "False teachers; 'agitators'" },
      ],
    },
    keyEvents: [
      { order: 1, title: "No other gospel", description: "Even an angel preaching another gospel is accursed", reference: "Galatians 1:6-9" },
      { order: 2, title: "Paul's apostolic authority", description: "Gospel received by revelation, not men", reference: "Galatians 1:11-24" },
      { order: 3, title: "Confronting Peter", description: "Hypocrisy at Antioch rebuked", reference: "Galatians 2:11-14" },
      { order: 4, title: "Crucified with Christ", description: "\"I no longer live, but Christ lives in me\"", reference: "Galatians 2:20" },
      { order: 5, title: "Abraham's faith", description: "Justified by faith 430 years before the law", reference: "Galatians 3" },
      { order: 6, title: "Sons, not slaves", description: "Adopted as heirs through Christ", reference: "Galatians 4" },
      { order: 7, title: "Fruit of the Spirit", description: "Love, joy, peace, patience...", reference: "Galatians 5:22-23" },
    ],
    culturalNotes: [
      { category: "law", title: "Circumcision debate", content: "Circumcision was the covenant sign of Judaism; requiring it of Gentiles made Christ's work insufficient." },
      { category: "customs", title: "Pedagogue (tutor)", content: "Paul likens the law to a Greek paidagogos — a slave who led children to school, then handed them off." },
      { category: "social", title: "Galatian loyalty", content: "Galatians were known for fickle loyalty; Paul marvels they turned away so quickly (1:6)." },
      { category: "worship", title: "Neither slave nor free", content: "Galatians 3:28 is one of the most radical social declarations in the ancient world." },
    ],
    didYouKnow: [
      "Galatians is sometimes called 'the Magna Carta of Christian liberty.'",
      "Paul wrote the postscript in his own large handwriting (6:11) — authenticating the letter.",
      "Luther's commentary on Galatians was the book that shaped the Reformation.",
      "The fruit of the Spirit (5:22-23) is singular — one cluster, not separate gifts.",
    ],
  },
  {
    id: "EPH",
    name: "Ephesians",
    overview: {
      shortSummary: "The church as the body of Christ — united, empowered, and armored for spiritual warfare.",
      fullSummary: "Ephesians is Paul's highest theological epistle, often called the 'queen of the epistles.' It explains God's eternal plan to unite all things in Christ, the nature of the church as His body and bride, and the believer's spiritual armor.",
      themes: ["God's eternal plan", "Unity in Christ", "The church", "Spiritual warfare", "Walking worthy"],
      keyMessages: ["Saved by grace through faith", "One body, one Spirit, one Lord", "Put on the full armor of God"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Rome during his imprisonment, c.AD 60-62." },
    timePeriod: {
      eventsDate: "c.AD 60-62",
      writingDate: "c.AD 60-62",
      biblicalPlacement: "Tenth NT book; Prison Epistle",
      relationToEvents: "Written during Paul's Roman imprisonment",
    },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Ephesus was the capital of the Roman province of Asia; home of the great temple of Artemis (one of the 7 Wonders).",
    },
    mapLocations: [
      { name: "Ephesus", type: "city", description: "Recipient church; major city of Asia Minor", svgX: 112, svgY: 150 },
      { name: "Rome", type: "city", description: "Where Paul wrote from prison", svgX: 58, svgY: 148 },
    ],
    genealogy: {
      description: "The household of God.",
      nodes: [
        { id: "godfather", name: "God the Father" },
        { id: "christ", name: "Jesus Christ", parentId: "godfather", notes: "Head of the church" },
        { id: "church", name: "The Church", parentId: "christ", notes: "His body and bride" },
        { id: "paul", name: "Paul", notes: "Prisoner of Christ Jesus" },
        { id: "tychicus", name: "Tychicus", notes: "Delivered the letter" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Blessed in the heavenly realms", description: "Every spiritual blessing in Christ", reference: "Ephesians 1:3-14" },
      { order: 2, title: "Dead made alive", description: "Saved by grace through faith, not works", reference: "Ephesians 2:1-10" },
      { order: 3, title: "One new humanity", description: "Gentiles and Jews united; the dividing wall broken", reference: "Ephesians 2:11-22" },
      { order: 4, title: "Mystery revealed", description: "Gentiles are co-heirs — hidden through ages", reference: "Ephesians 3" },
      { order: 5, title: "Walk worthy", description: "Unity, holiness, relationships", reference: "Ephesians 4-5" },
      { order: 6, title: "Household code", description: "Wives, husbands, children, parents, slaves", reference: "Ephesians 5-6" },
      { order: 7, title: "Armor of God", description: "Stand against the schemes of the devil", reference: "Ephesians 6:10-18" },
    ],
    culturalNotes: [
      { category: "worship", title: "Temple of Artemis", content: "Ephesus was dominated by one of the 7 Wonders; the church was God's true temple in the city." },
      { category: "social", title: "Household codes", content: "Paul transforms Greco-Roman household ethics with mutual submission and sacrificial love." },
      { category: "customs", title: "Roman armor", content: "Paul's armor metaphor maps to specific pieces of a Roman legionary's equipment." },
      { category: "law", title: "Mystery", content: "Greek mysterion — a secret now revealed; the Gentile inclusion was hidden in past ages." },
    ],
    didYouKnow: [
      "Ephesians 2:8-9 is arguably the clearest statement of salvation by grace in the Bible.",
      "Some manuscripts omit 'in Ephesus' — suggesting it was a circular letter.",
      "Ephesians contains the longest sentence in the Greek NT (1:3-14 — one sentence in Greek).",
      "The 'armor of God' passage draws on Isaiah's description of God as warrior.",
    ],
  },
  {
    id: "PHP",
    name: "Philippians",
    overview: {
      shortSummary: "The letter of joy — rejoice always, in all circumstances.",
      fullSummary: "Philippians is Paul's warmest letter, written from prison to his most beloved church. Despite imprisonment, trials, and the prospect of death, joy runs through every chapter. The great Christ hymn (2:5-11) is at its heart.",
      themes: ["Joy in all circumstances", "Humility of Christ", "Unity", "Contentment", "Gospel partnership"],
      keyMessages: ["Rejoice in the Lord always", "To live is Christ, to die is gain", "I can do all things through Christ who strengthens me"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Rome (or Ephesus), c.AD 60-62." },
    timePeriod: {
      eventsDate: "c.AD 60-62",
      writingDate: "c.AD 60-62",
      biblicalPlacement: "Eleventh NT book; Prison Epistle",
      relationToEvents: "Written during imprisonment; prompted by gift from Philippi",
    },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Philippi was a Roman colony whose citizens were proud of Roman citizenship; Paul contrasts this with heavenly citizenship.",
    },
    mapLocations: [
      { name: "Philippi", type: "city", description: "Recipient church; Roman colony in Macedonia", svgX: 105, svgY: 152 },
      { name: "Rome", type: "city", description: "Paul's imprisonment; where letter was written", svgX: 58, svgY: 148 },
    ],
    genealogy: {
      description: "Key people in Philippians.",
      nodes: [
        { id: "paul", name: "Paul" },
        { id: "timothy", name: "Timothy", notes: "Co-sender" },
        { id: "epaphroditus", name: "Epaphroditus", notes: "Philippian messenger; nearly died" },
        { id: "lydia", name: "Lydia", notes: "Church founder in Philippi" },
        { id: "euodia", name: "Euodia", notes: "In conflict with Syntyche" },
        { id: "syntyche", name: "Syntyche", notes: "In conflict with Euodia" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Thanksgiving for partnership", description: "Confident God will complete His work", reference: "Philippians 1:1-11" },
      { order: 2, title: "Chains advance the gospel", description: "What happened to me advances the gospel", reference: "Philippians 1:12-26" },
      { order: 3, title: "Christ hymn", description: "Emptied Himself; humbled to death; exalted", reference: "Philippians 2:5-11" },
      { order: 4, title: "Rejoice — always", description: "\"Rejoice in the Lord always. Again I say rejoice\"", reference: "Philippians 4:4" },
      { order: 5, title: "Think on these things", description: "Whatever is true, noble, right, pure...", reference: "Philippians 4:8" },
      { order: 6, title: "Contentment in all things", description: "\"I have learned, in whatever state I am, to be content\"", reference: "Philippians 4:11" },
    ],
    culturalNotes: [
      { category: "social", title: "Roman colony pride", content: "Philippians leverages Roman citizenship metaphors to point to heavenly citizenship (3:20)." },
      { category: "worship", title: "Christ hymn (kenosis)", content: "One of the oldest pre-Pauline hymns, teaching Christ's self-emptying (kenosis)." },
      { category: "customs", title: "Prison letter", content: "Paul writes from chains with joy — a profound witness to his jailers." },
      { category: "social", title: "Partnership (koinonia)", content: "Philippi sent financial support to Paul multiple times; unique among his churches." },
    ],
    didYouKnow: [
      "Philippians 4:13 is the most tattooed Bible verse in the world.",
      "The word 'joy' or 'rejoice' appears 16 times in just 4 chapters.",
      "Lydia of Thyatira was the first European convert to Christianity.",
      "Paul likely wrote Philippians from Rome while chained to a rotating guard.",
    ],
  },
  {
    id: "COL",
    name: "Colossians",
    overview: {
      shortSummary: "Christ is supreme over all creation — the fullness of God in bodily form.",
      fullSummary: "The Colossian heresy mixed Jewish law, pagan philosophy, and angel worship. Paul counters with a majestic vision of Christ's cosmic supremacy. All fullness dwells in Him; nothing else is needed.",
      themes: ["Supremacy of Christ", "Fullness in Christ", "False philosophy", "New life in Christ"],
      keyMessages: ["Christ is all, and in all", "You are complete in Him", "Set your mind on things above"],
    },
    author: { traditional: "Paul the Apostle", notes: "Written from Rome, c.AD 60-62; delivered with Ephesians by Tychicus." },
    timePeriod: {
      eventsDate: "c.AD 60-62",
      writingDate: "c.AD 60-62",
      biblicalPlacement: "Twelfth NT book; Prison Epistle",
      relationToEvents: "Paul had not visited Colossae; church founded by Epaphras",
    },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Colossae was in the Lycus Valley of Asia Minor, near Laodicea and Hierapolis. The church faced a syncretistic heresy blending Jewish and pagan elements.",
    },
    mapLocations: [
      { name: "Colossae", type: "city", description: "Recipient church; Lycus Valley", svgX: 130, svgY: 152 },
      { name: "Laodicea", type: "city", description: "Neighboring church; letter to be exchanged", svgX: 128, svgY: 153 },
      { name: "Rome", type: "city", description: "Paul's imprisonment", svgX: 58, svgY: 148 },
    ],
    genealogy: {
      description: "Key figures.",
      nodes: [
        { id: "epaphras", name: "Epaphras", notes: "Founded Colossian church; reported to Paul" },
        { id: "paul", name: "Paul", notes: "Writes from prison" },
        { id: "tychicus", name: "Tychicus", notes: "Delivered the letter" },
        { id: "onesimus", name: "Onesimus", notes: "Runaway slave; Philemon connection" },
        { id: "markc", name: "Mark", notes: "With Paul in Rome" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Christ hymn", description: "Firstborn over all creation; head of the body", reference: "Colossians 1:15-20" },
      { order: 2, title: "Mystery revealed", description: "Christ in you, the hope of glory", reference: "Colossians 1:27" },
      { order: 3, title: "False philosophy rebuked", description: "Hollow and deceptive philosophy", reference: "Colossians 2:8" },
      { order: 4, title: "Fullness in Christ", description: "All fullness of deity dwells in Him bodily", reference: "Colossians 2:9-10" },
      { order: 5, title: "Raised with Christ", description: "Set your mind on things above", reference: "Colossians 3:1-4" },
      { order: 6, title: "New self", description: "Put on love — the bond of perfection", reference: "Colossians 3:12-14" },
    ],
    culturalNotes: [
      { category: "worship", title: "Angel worship", content: "The Colossian heresy involved worship of angelic beings as mediators." },
      { category: "law", title: "Shadow and substance", content: "Food laws, new moons, Sabbaths are shadows; Christ is the substance." },
      { category: "customs", title: "Household code", content: "Similar to Ephesians; grounds social ethics in the new creation." },
      { category: "social", title: "Syncretism", content: "Blending Christianity with other religious systems was the ancient error Colossians combats — still relevant today." },
    ],
    didYouKnow: [
      "Colossians 1:15-20 is one of the highest Christological passages in the NT.",
      "Colossians and Philemon share the same group of coworkers — written at the same time.",
      "The 'Colossian heresy' has never been precisely identified — scholars still debate it.",
      "Colossians 3:23 — 'Whatever you do, do it as for the Lord' — applies Christian faith to daily work.",
    ],
  },
];
