import type { OTBookContext } from "../context-types";

export const CONTEXT_HEB_TO_2PE: OTBookContext[] = [
  {
    id: "HEB",
    name: "Hebrews",
    overview: {
      shortSummary: "Christ is better — better than angels, Moses, priests, and the old covenant.",
      fullSummary: "Hebrews is a sermon-letter addressed to Jewish Christians tempted to return to Judaism. It argues that Jesus is the fulfillment and surpassing of every OT institution — priest, sacrifice, covenant, tabernacle. The great 'faith chapter' (Hebrews 11) anchors the call to persevere.",
      themes: ["Superiority of Christ", "Perseverance in faith", "Better covenant", "High priesthood", "Faith hall of fame"],
      keyMessages: ["Jesus is the same yesterday, today, and forever", "Let us draw near with confidence", "Run with endurance the race set before us"],
    },
    author: { traditional: "Unknown (Paul, Apollos, Priscilla, Barnabas all suggested)", notes: "Origen (c.AD 250): 'Only God truly knows.'" },
    timePeriod: { eventsDate: "c.AD 60-70", writingDate: "c.AD 60-70", biblicalPlacement: "Nineteenth NT book; General Epistles begin", relationToEvents: "Before or just after Jerusalem's destruction (AD 70)" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Jewish Christians were being pressured to renounce Christ and return to the synagogue to avoid Roman persecution of the new sect.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "The temple still standing; at risk of destruction", svgX: 160, svgY: 165 },
      { name: "Italy", type: "region", description: "Greetings from 'those from Italy' (13:24)", svgX: 65, svgY: 145 },
    ],
    genealogy: {
      description: "OT figures cited in the faith chapter.",
      nodes: [
        { id: "abel", name: "Abel" },
        { id: "enoch", name: "Enoch" },
        { id: "noah", name: "Noah" },
        { id: "abraham", name: "Abraham" },
        { id: "moses", name: "Moses" },
        { id: "rahab", name: "Rahab" },
        { id: "jesus", name: "Jesus", notes: "Author and perfecter of faith" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Son greater than angels", description: "God spoke finally through His Son", reference: "Hebrews 1" },
      { order: 2, title: "Greater than Moses", description: "Moses was faithful as a servant; Christ as Son", reference: "Hebrews 3" },
      { order: 3, title: "Sabbath rest remains", description: "Strive to enter God's rest", reference: "Hebrews 4" },
      { order: 4, title: "High priest after Melchizedek", description: "Eternal priesthood; not Levitical", reference: "Hebrews 5-7" },
      { order: 5, title: "Better covenant", description: "New covenant written on hearts; obsolete old", reference: "Hebrews 8" },
      { order: 6, title: "Once for all sacrifice", description: "Not repeated like animal sacrifices", reference: "Hebrews 9-10" },
      { order: 7, title: "Faith chapter", description: "The great cloud of witnesses", reference: "Hebrews 11" },
      { order: 8, title: "Run with endurance", description: "Fix eyes on Jesus; endure discipline", reference: "Hebrews 12" },
    ],
    culturalNotes: [
      { category: "worship", title: "Melchizedek", content: "A mysterious OT priest-king (Gen 14) whose eternal priesthood prefigures Christ's." },
      { category: "law", title: "Day of Atonement", content: "Hebrews unpacks Yom Kippur as a shadow fulfilled by Christ's once-for-all sacrifice." },
      { category: "customs", title: "Tabernacle typology", content: "Every piece of the tabernacle is a type pointing to Christ." },
      { category: "social", title: "Shame culture", content: "Hebrews uses honor/shame language; Jesus 'despised the shame' to win glory." },
    ],
    didYouKnow: [
      "Hebrews quotes the OT over 35 times — more than any other NT letter.",
      "The 'faith hall of fame' (ch. 11) names 16 people and refers to many more.",
      "Hebrews 4:12 — 'The Word of God is living and active' — is the foundational text for Bible study.",
      "The authorship of Hebrews remains the longest-standing mystery in NT scholarship.",
    ],
  },
  {
    id: "JAS",
    name: "James",
    overview: {
      shortSummary: "Practical wisdom for living faith — faith without works is dead.",
      fullSummary: "James, the Lord's brother, wrote the NT's most practical letter. It emphasizes that genuine faith produces action — in trials, temptation, speech, partiality, prayer, and care for the poor. It corrects faith that is merely intellectual.",
      themes: ["Faith and works", "Wisdom", "Trials", "Speech", "Partiality"],
      keyMessages: ["Faith without works is dead", "Be doers of the word, not hearers only", "Pray and the prayer of faith will save the sick"],
    },
    author: { traditional: "James, brother of Jesus", notes: "Elder of the Jerusalem church; martyred c.AD 62." },
    timePeriod: { eventsDate: "c.AD 45-49", writingDate: "c.AD 45-49", biblicalPlacement: "Twentieth NT book; possibly earliest NT letter", relationToEvents: "Written before the Jerusalem Council (AD 49)" },
    historicalSetting: {
      rulers: ["Claudius (or early Herod Agrippa era)"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Jewish Christians scattered by early persecution; James writes to stabilize communities facing economic hardship and ethical pressure.",
    },
    mapLocations: [
      { name: "Jerusalem", type: "city", description: "James's base as church elder", svgX: 160, svgY: 165 },
      { name: "Diaspora", type: "region", description: "'Twelve tribes scattered abroad' — Jews in exile", svgX: 190, svgY: 160 },
    ],
    genealogy: {
      description: "James's position.",
      nodes: [
        { id: "joseph", name: "Joseph" },
        { id: "mary", name: "Mary" },
        { id: "jesus", name: "Jesus", parentId: "joseph" },
        { id: "james", name: "James", parentId: "joseph", notes: "Half-brother of Jesus; elder of Jerusalem" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Trials produce endurance", description: "Count it joy when you face trials", reference: "James 1:2-4" },
      { order: 2, title: "Be doers", description: "Not hearers only who deceive themselves", reference: "James 1:22" },
      { order: 3, title: "No partiality", description: "Do not show favoritism to the rich over the poor", reference: "James 2:1-13" },
      { order: 4, title: "Faith without works is dead", description: "Show me your faith by your works", reference: "James 2:14-26" },
      { order: 5, title: "Taming the tongue", description: "The tongue is a fire; no one can tame it", reference: "James 3" },
      { order: 6, title: "Wisdom from above", description: "Pure, peaceable, gentle, open to reason", reference: "James 3:17" },
      { order: 7, title: "Prayer of faith", description: "Elijah prayed and it did not rain; pray for healing", reference: "James 5:13-18" },
    ],
    culturalNotes: [
      { category: "social", title: "Rich and poor", content: "James is more direct on economic justice than almost any other NT book." },
      { category: "customs", title: "Wisdom tradition", content: "James resembles Proverbs and the Sermon on the Mount — practical wisdom, not systematic theology." },
      { category: "worship", title: "Elders and anointing", content: "James 5:14 establishes elder-led prayer and anointing for healing." },
      { category: "law", title: "Royal law", content: "'Love your neighbor as yourself' — James calls this the royal (kingly) law." },
    ],
    didYouKnow: [
      "Luther called James 'an epistle of straw' — he later moderated his view.",
      "James was martyred by being thrown from the temple pinnacle, c.AD 62.",
      "James 1:17 — 'every good and perfect gift' — is often used in grace before meals.",
      "James uses more nature imagery (waves, fire, plants, horses) than any other NT letter.",
    ],
  },
  {
    id: "1PE",
    name: "1 Peter",
    overview: {
      shortSummary: "Suffering Christians exhorted to holy living and steadfast hope as strangers in the world.",
      fullSummary: "Peter writes to scattered Christians in Asia Minor undergoing social hostility and potential persecution. He grounds their identity in election and new birth, calls them to holy conduct among pagans, and models Christ's suffering as the pattern for theirs.",
      themes: ["Suffering and hope", "Holy living as exiles", "Christ's example", "Submission", "Glory to come"],
      keyMessages: ["You are a chosen people, a royal priesthood", "Humble yourselves under God's mighty hand", "Cast all your anxiety on Him"],
    },
    author: { traditional: "Peter the Apostle", notes: "Written from Rome ('Babylon') c.AD 62-64; Silas was his secretary." },
    timePeriod: { eventsDate: "c.AD 62-64", writingDate: "c.AD 62-64", biblicalPlacement: "Twenty-first NT book", relationToEvents: "Just before or during Nero's persecution" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Christians in Asia Minor faced social ostracism, slander, and the beginning of official Roman hostility after the AD 64 fire.",
    },
    mapLocations: [
      { name: "Pontus, Galatia, Cappadocia, Asia, Bithynia", type: "region", description: "Recipient provinces of Asia Minor", svgX: 145, svgY: 140 },
      { name: "Rome (Babylon)", type: "city", description: "Where Peter wrote from", svgX: 58, svgY: 148 },
    ],
    genealogy: {
      description: "Key figures.",
      nodes: [
        { id: "peter", name: "Peter", notes: "Apostle; eyewitness of Christ's sufferings" },
        { id: "silas", name: "Silas", notes: "Secretary" },
        { id: "mark", name: "Mark", notes: "'My son' — with Peter in Rome" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Living hope through resurrection", description: "Born again to a living hope", reference: "1 Peter 1:3-5" },
      { order: 2, title: "Chosen people, royal priesthood", description: "Identity of God's people", reference: "1 Peter 2:9-10" },
      { order: 3, title: "Submit to authorities", description: "For the Lord's sake; silencing critics", reference: "1 Peter 2:13-17" },
      { order: 4, title: "Christ's suffering as example", description: "He bore our sins; by His wounds we are healed", reference: "1 Peter 2:21-25" },
      { order: 5, title: "Wives and husbands", description: "Gentle spirit; dwell with understanding", reference: "1 Peter 3:1-7" },
      { order: 6, title: "Always be ready", description: "Give a reason for your hope with gentleness", reference: "1 Peter 3:15" },
      { order: 7, title: "Fiery trial", description: "Rejoice inasmuch as you share Christ's sufferings", reference: "1 Peter 4:12-13" },
    ],
    culturalNotes: [
      { category: "social", title: "Paroikoi (exiles)", content: "Peter's audience was socially marginal; they were resident aliens without full civic rights." },
      { category: "customs", title: "Household codes", content: "1 Peter addresses master-slave, husband-wife, elder-congregation relationships." },
      { category: "worship", title: "Baptism", content: "1 Peter 3:21 — baptism as an appeal to God for a clean conscience." },
      { category: "law", title: "Suffering for righteousness", content: "The entire letter reframes suffering not as divine punishment but as participation in Christ." },
    ],
    didYouKnow: [
      "1 Peter 3:15 is the foundational text for Christian apologetics.",
      "Peter calls Rome 'Babylon' — a code name also used in Revelation.",
      "The letter was likely circulated through Asia Minor by a messenger.",
      "Peter and Paul were likely both in Rome in the AD 60s and both martyred there.",
    ],
  },
  {
    id: "2PE",
    name: "2 Peter",
    overview: {
      shortSummary: "Peter's farewell warning against false teachers and call to grow in grace.",
      fullSummary: "Peter knows he is near death and writes a final warning against false teachers who distort Scripture and deny Christ's return. He grounds certainty in the Transfiguration eyewitness account and the prophetic word, and calls believers to grow in grace and knowledge.",
      themes: ["Godly growth", "Warning against false teachers", "Certainty of Christ's return", "Scripture's authority"],
      keyMessages: ["Grow in grace and knowledge of our Lord", "No prophecy of Scripture is of private interpretation", "The Lord is not slow — He is patient"],
    },
    author: { traditional: "Peter the Apostle", notes: "Written c.AD 64-68, shortly before Peter's martyrdom." },
    timePeriod: { eventsDate: "c.AD 64-68", writingDate: "c.AD 64-68", biblicalPlacement: "Twenty-second NT book; Peter's farewell", relationToEvents: "Peter anticipates imminent death (1:14)" },
    historicalSetting: {
      rulers: ["Nero"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "False teachers were infiltrating churches, denying Christ's return and living immorally under the claim that grace permits all things.",
    },
    mapLocations: [
      { name: "Rome", type: "city", description: "Likely Peter's final location", svgX: 58, svgY: 148 },
      { name: "Mount of Transfiguration", type: "city", description: "Peter cites as eyewitness proof", svgX: 160, svgY: 147 },
    ],
    genealogy: {
      description: "Peter, Paul, and the false teachers.",
      nodes: [
        { id: "peter", name: "Peter", notes: "Writing his final letter" },
        { id: "paul", name: "Paul", notes: "Mentioned as beloved brother" },
        { id: "falseteachers", name: "False teachers", notes: "Distorting Paul's letters; denying return of Christ" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Partakers of divine nature", description: "Escape corruption through precious promises", reference: "2 Peter 1:4" },
      { order: 2, title: "Add to your faith", description: "Virtue, knowledge, self-control, perseverance, godliness, brotherly love", reference: "2 Peter 1:5-7" },
      { order: 3, title: "Transfiguration eyewitness", description: "We were there; we heard the voice", reference: "2 Peter 1:16-18" },
      { order: 4, title: "Warning against false teachers", description: "Bring in destructive heresies; many will follow", reference: "2 Peter 2" },
      { order: 5, title: "Day of the Lord", description: "One day is like a thousand; patient not slow", reference: "2 Peter 3:8-10" },
      { order: 6, title: "Grow in grace", description: "Closing charge; beware of being carried away", reference: "2 Peter 3:17-18" },
    ],
    culturalNotes: [
      { category: "worship", title: "Prophetic word", content: "Peter says Scripture is more sure than even his Transfiguration experience." },
      { category: "social", title: "Private interpretation", content: "Scripture was not to be interpreted in isolation from community and the Spirit." },
      { category: "law", title: "Day of the Lord", content: "Mockers denied the return because nothing had changed; Peter answers with God's patience and timelessness." },
      { category: "customs", title: "Peter and Paul", content: "2 Peter is the only NT letter that refers to another apostle's writings as Scripture." },
    ],
    didYouKnow: [
      "2 Peter refers to Paul's letters as 'Scripture' — an early canon indicator.",
      "Peter was crucified upside down in Rome, c.AD 64-68, by his own request.",
      "2 Peter has the most debated authorship of any Petrine writing.",
      "The 'day like a thousand years' (3:8) echoes Psalm 90:4.",
    ],
  },
];
