import type { OTBookContext } from "../context-types";

export const CONTEXT_MAT_TO_JHN: OTBookContext[] = [
  {
    id: "MAT",
    name: "Matthew",
    overview: {
      shortSummary: "Jesus as the promised Messiah and King — the fulfillment of the Old Testament.",
      fullSummary: "Matthew presents Jesus as the long-awaited Messiah, Son of David, and Son of Abraham. Written for a Jewish audience, it demonstrates that Jesus fulfilled the OT prophecies. It contains the Sermon on the Mount, the Great Commission, and five major teaching discourses.",
      themes: ["Jesus as Messiah-King", "Kingdom of Heaven", "Fulfillment of prophecy", "Discipleship", "Mission to all nations"],
      keyMessages: ["The kingdom of heaven is at hand", "Follow Me", "Go and make disciples of all nations", "I am with you always"],
    },
    author: { traditional: "Matthew (Levi), apostle and tax collector", notes: "Early church unanimously attributed this Gospel to Matthew." },
    timePeriod: {
      eventsDate: "c.4 BC – AD 33",
      writingDate: "c.AD 50-70",
      biblicalPlacement: "First Gospel; bridge from OT to NT",
      relationToEvents: "Written after the events, drawing on eyewitness testimony",
    },
    historicalSetting: {
      rulers: ["Herod the Great (birth)", "Herod Antipas (ministry)", "Pontius Pilate (crucifixion)", "Caesar Augustus, Tiberius"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Judea was under Roman occupation. Jewish religious leaders (Pharisees, Sadducees, scribes) held social authority.",
    },
    mapLocations: [
      { name: "Bethlehem", type: "city", description: "Jesus' birthplace", svgX: 160, svgY: 167 },
      { name: "Nazareth", type: "city", description: "Jesus' hometown", svgX: 160, svgY: 148 },
      { name: "Jerusalem", type: "city", description: "Triumphal entry, crucifixion, resurrection", svgX: 160, svgY: 165 },
      { name: "Capernaum", type: "city", description: "Ministry headquarters", svgX: 168, svgY: 143 },
      { name: "Mount of Beatitudes", type: "city", description: "Sermon on the Mount", svgX: 168, svgY: 143 },
      { name: "Galilee", type: "region", description: "Primary ministry region", svgX: 162, svgY: 145 },
      { name: "Egypt", type: "journey", description: "Flight of the holy family", svgX: 120, svgY: 195 },
    ],
    genealogy: {
      description: "Matthew opens with Jesus' legal lineage through Joseph, establishing his Davidic credentials.",
      nodes: [
        { id: "abraham", name: "Abraham" },
        { id: "david", name: "David", parentId: "abraham" },
        { id: "solomon", name: "Solomon", parentId: "david" },
        { id: "joseph", name: "Joseph (legal father)", parentId: "solomon" },
        { id: "jesus", name: "Jesus", parentId: "joseph", notes: "Born of the Virgin Mary" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Birth and Magi", description: "Wise men follow the star to Bethlehem", reference: "Matthew 1-2" },
      { order: 2, title: "Baptism and temptation", description: "Declared Son of God; resists Satan 40 days", reference: "Matthew 3-4" },
      { order: 3, title: "Sermon on the Mount", description: "Kingdom ethics and beatitudes", reference: "Matthew 5-7" },
      { order: 4, title: "Miracles and mission", description: "Healing, stilling storm, feeding 5000", reference: "Matthew 8-14" },
      { order: 5, title: "Peter's confession", description: "\"You are the Christ, Son of the living God\"", reference: "Matthew 16:13-20" },
      { order: 6, title: "Transfiguration", description: "Jesus glorified before Peter, James, John", reference: "Matthew 17" },
      { order: 7, title: "Triumphal entry", description: "King enters Jerusalem on a donkey", reference: "Matthew 21" },
      { order: 8, title: "Passion and resurrection", description: "Betrayal, crucifixion, empty tomb", reference: "Matthew 26-28" },
      { order: 9, title: "Great Commission", description: "Go make disciples of all nations", reference: "Matthew 28:18-20" },
    ],
    culturalNotes: [
      { category: "social", title: "Tax collectors", content: "Matthew was a publican — Jewish tax collectors for Rome were despised as traitors." },
      { category: "worship", title: "Fulfillment formula", content: "Matthew uses 'this was to fulfill...' over 10 times, connecting Jesus to OT prophecy." },
      { category: "customs", title: "Sermon on the Mount", content: "Moses gave law on Sinai; Jesus gave new covenant ethics on a mountain." },
      { category: "law", title: "Antitheses", content: "\"You have heard it said...but I say to you\" — Jesus deepens the law." },
    ],
    didYouKnow: [
      "Matthew quotes or alludes to the OT more than any other Gospel.",
      "The Sermon on the Mount (Matt 5-7) is the longest recorded teaching of Jesus.",
      "Matthew organizes Jesus' teachings into 5 discourses, mirroring the 5 books of Moses.",
      "The Great Commission has launched more missionaries than any other single passage.",
    ],
  },
  {
    id: "MRK",
    name: "Mark",
    overview: {
      shortSummary: "The action-packed Gospel of Jesus as the Servant — immediate, powerful, purposeful.",
      fullSummary: "Mark is the shortest and most fast-paced Gospel. Writing for a Roman audience, Mark emphasizes Jesus' deeds over His discourses. The word 'immediately' (euthys) appears 41 times. Jesus is the Servant who came to give His life as a ransom.",
      themes: ["Jesus as Servant", "Kingdom of God", "Discipleship cost", "Authority and power", "Messianic secret"],
      keyMessages: ["The Son of Man came to serve", "Take up your cross and follow Me", "Repent and believe the Gospel"],
    },
    author: { traditional: "John Mark, companion of Peter", notes: "Papias (c.AD 125) says Mark recorded Peter's memoirs." },
    timePeriod: {
      eventsDate: "c.AD 27-33",
      writingDate: "c.AD 55-65",
      biblicalPlacement: "Second Gospel; likely written first",
      relationToEvents: "Likely the earliest Gospel",
    },
    historicalSetting: {
      rulers: ["Herod Antipas", "Pontius Pilate", "Tiberius Caesar"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Roman military occupation; Herod Antipas ruled Galilee. Mark's Roman audience was familiar with persecution.",
    },
    mapLocations: [
      { name: "Capernaum", type: "city", description: "Base of ministry, many miracles", svgX: 168, svgY: 143 },
      { name: "Sea of Galilee", type: "region", description: "Stilling of storm; walking on water", svgX: 170, svgY: 145 },
      { name: "Decapolis", type: "region", description: "Gentile territory; demoniac healed", svgX: 175, svgY: 155 },
      { name: "Caesarea Philippi", type: "city", description: "Peter's confession", svgX: 173, svgY: 138 },
      { name: "Jerusalem", type: "city", description: "Passion week and resurrection", svgX: 160, svgY: 165 },
    ],
    genealogy: {
      description: "Mark provides no genealogy — Jesus is introduced immediately as the Son of God.",
      nodes: [
        { id: "jesus", name: "Jesus Christ, Son of God" },
        { id: "peter", name: "Peter", notes: "Primary eyewitness behind Mark" },
        { id: "mark", name: "John Mark", notes: "Author; companion of Peter and Paul" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Baptism and temptation", description: "'Immediately' Jesus is driven into the wilderness", reference: "Mark 1:1-13" },
      { order: 2, title: "Calling of disciples", description: "Fishermen leave nets immediately", reference: "Mark 1:16-20" },
      { order: 3, title: "Miracles cascade", description: "Demon, fever, leper, paralytic healed", reference: "Mark 1-5" },
      { order: 4, title: "Feeding 5000 and 4000", description: "Two miraculous feedings", reference: "Mark 6, 8" },
      { order: 5, title: "Transfiguration", description: "On the mountain with Moses and Elijah", reference: "Mark 9" },
      { order: 6, title: "Triumphal entry", description: "King enters Jerusalem", reference: "Mark 11" },
      { order: 7, title: "Gethsemane to resurrection", description: "Passion and empty tomb", reference: "Mark 14-16" },
    ],
    culturalNotes: [
      { category: "social", title: "Roman audience", content: "Mark explains Jewish customs and translates Aramaic phrases for Gentile readers." },
      { category: "customs", title: "\"Immediately\"", content: "Euthys — 41 times — gives Mark its breathless, urgent pace." },
      { category: "worship", title: "Messianic secret", content: "Jesus often told healed people not to tell anyone — building to the cross revelation." },
      { category: "law", title: "Ransom saying", content: "Mark 10:45 — 'to give his life as a ransom for many' — is the theological heart of the book." },
    ],
    didYouKnow: [
      "Mark is the shortest Gospel — only 16 chapters.",
      "Many scholars believe Mark was written first and Matthew and Luke used it as a source.",
      "Mark mentions that a young man fled naked at Jesus' arrest — possibly Mark himself (14:51-52).",
      "The original ending of Mark (16:8) ends with the women fleeing in fear — deliberately unresolved.",
    ],
  },
  {
    id: "LUK",
    name: "Luke",
    overview: {
      shortSummary: "The Gospel of the Son of Man — Jesus as Savior for all people, especially the marginalized.",
      fullSummary: "Luke, a physician and traveling companion of Paul, wrote the most orderly and comprehensive Gospel. He emphasizes the Holy Spirit, prayer, women, the poor, Samaritans, and outcasts. Luke-Acts forms a two-volume work on the spread of the Gospel.",
      themes: ["Universal salvation", "Holy Spirit", "Prayer", "The poor and outcasts", "Women", "Joy"],
      keyMessages: ["The Son of Man came to seek and save the lost", "Today salvation has come to this house", "Rejoice — the lost is found"],
    },
    author: { traditional: "Luke, physician and companion of Paul", notes: "The 'we' sections in Acts (Acts 16, 20-21, 27-28) confirm Luke traveled with Paul." },
    timePeriod: {
      eventsDate: "c.6 BC – AD 33",
      writingDate: "c.AD 60-62",
      biblicalPlacement: "Third Gospel; first volume of Luke-Acts",
      relationToEvents: "Luke interviewed eyewitnesses (Luke 1:1-4)",
    },
    historicalSetting: {
      rulers: ["Augustus (census)", "Tiberius", "Herod Antipas", "Pilate", "Annas and Caiaphas"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Luke situates Jesus in world history (Roman censuses, governor lists), asserting the Gospel's historical reality.",
    },
    mapLocations: [
      { name: "Bethlehem", type: "city", description: "Birth of Jesus during census", svgX: 160, svgY: 167 },
      { name: "Nazareth", type: "city", description: "Childhood home; rejected in synagogue", svgX: 160, svgY: 148 },
      { name: "Jericho", type: "city", description: "Zacchaeus; blind Bartimaeus", svgX: 167, svgY: 165 },
      { name: "Emmaus", type: "city", description: "Resurrection appearance on road", svgX: 155, svgY: 165 },
      { name: "Jerusalem", type: "city", description: "Goal of Jesus' journey", svgX: 160, svgY: 165 },
      { name: "Samaria", type: "region", description: "Good Samaritan; 10 lepers", svgX: 158, svgY: 152 },
    ],
    genealogy: {
      description: "Luke traces Jesus' lineage through Mary's line all the way back to Adam — Son of Man for all humanity.",
      nodes: [
        { id: "adam", name: "Adam", notes: "\"Son of God\"" },
        { id: "abraham", name: "Abraham", parentId: "adam" },
        { id: "david", name: "David", parentId: "abraham" },
        { id: "nathan", name: "Nathan (son of David)", parentId: "david", notes: "Mary's line, not Solomon's" },
        { id: "heli", name: "Heli", parentId: "nathan", notes: "Mary's father (Joseph's father-in-law)" },
        { id: "jesus", name: "Jesus", parentId: "heli" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Annunciation and birth", description: "Gabriel to Mary; shepherds in the field", reference: "Luke 1-2" },
      { order: 2, title: "Boy Jesus in the temple", description: "\"I must be about My Father's business\"", reference: "Luke 2:41-52" },
      { order: 3, title: "Nazareth rejection", description: "\"The Spirit of the Lord is upon Me\" — then rejected", reference: "Luke 4:16-30" },
      { order: 4, title: "Parables of the lost", description: "Lost sheep, lost coin, prodigal son", reference: "Luke 15" },
      { order: 5, title: "Zacchaeus", description: "\"Today salvation has come to this house\"", reference: "Luke 19:1-10" },
      { order: 6, title: "Passion and resurrection", description: "Gethsemane through empty tomb", reference: "Luke 22-24" },
      { order: 7, title: "Road to Emmaus", description: "Resurrection appearance; burning hearts", reference: "Luke 24:13-35" },
    ],
    culturalNotes: [
      { category: "social", title: "Women in Luke", content: "Mary, Elizabeth, Anna, widow of Nain, sinful woman, Mary Magdalene — women are prominent." },
      { category: "customs", title: "Physician's eye", content: "Luke records more medical details and notes emotional states others omit." },
      { category: "worship", title: "Prayer emphasis", content: "Luke records Jesus praying 10 times; 7 are unique to Luke." },
      { category: "social", title: "Outcasts included", content: "Samaritans, lepers, tax collectors, sinners receive special attention." },
    ],
    didYouKnow: [
      "Luke is the longest book in the NT by word count (including Acts).",
      "Luke is the only NT author who was certainly a Gentile.",
      "The Magnificat (Luke 1:46-55) is the oldest Christian hymn.",
      "Luke contains more parables than any other Gospel (19 unique).",
    ],
  },
  {
    id: "JHN",
    name: "John",
    overview: {
      shortSummary: "The theological Gospel — Jesus as the eternal Word, the Son of God, who gives eternal life.",
      fullSummary: "John's Gospel stands apart from the Synoptics. It opens with the eternal Word (Logos), features seven 'I Am' statements, seven signs, and long theological discourses. Written so readers may believe Jesus is the Christ and have life in His name.",
      themes: ["Incarnation of the Word", "Belief and eternal life", "Light and darkness", "Love", "The Holy Spirit (Paraclete)"],
      keyMessages: ["For God so loved the world", "I am the way, the truth, and the life", "Believe and have life in His name"],
    },
    author: { traditional: "John the Apostle, son of Zebedee", notes: "The 'beloved disciple' is identified as the author (John 21:24)." },
    timePeriod: {
      eventsDate: "c.27-33 AD",
      writingDate: "c.AD 85-95",
      biblicalPlacement: "Fourth Gospel; written last",
      relationToEvents: "Written late, with deep theological reflection",
    },
    historicalSetting: {
      rulers: ["Tiberius Caesar", "Pontius Pilate", "Caiaphas"],
      israelKings: [],
      neighboringPowers: ["Roman Empire"],
      politicalBackground: "Written to the broader Greco-Roman world; engages Greek philosophical concepts (Logos) and Jewish Passover symbolism.",
    },
    mapLocations: [
      { name: "Cana", type: "city", description: "First sign — water to wine", svgX: 160, svgY: 147 },
      { name: "Jerusalem (Temple)", type: "city", description: "Cleansing; Nicodemus; Bethesda", svgX: 160, svgY: 165 },
      { name: "Sychar (Samaria)", type: "city", description: "Woman at the well", svgX: 160, svgY: 155 },
      { name: "Bethany", type: "city", description: "Lazarus raised from the dead", svgX: 162, svgY: 166 },
      { name: "Pool of Siloam", type: "city", description: "Blind man healed", svgX: 160, svgY: 165 },
      { name: "Sea of Tiberias", type: "region", description: "Resurrection appearance; Peter restored", svgX: 170, svgY: 145 },
    ],
    genealogy: {
      description: "John begins not with Abraham or Adam but with eternity — 'In the beginning was the Word.'",
      nodes: [
        { id: "logos", name: "The Word (eternal)", notes: "\"In the beginning was the Word\"" },
        { id: "jesus", name: "Jesus — the Word made flesh", parentId: "logos" },
        { id: "johnbap", name: "John the Baptist", notes: "Witness to the Light" },
        { id: "disciples", name: "The Twelve", notes: "Those He chose" },
      ],
    },
    keyEvents: [
      { order: 1, title: "Prologue — the Word", description: "\"In the beginning was the Word\"", reference: "John 1:1-18" },
      { order: 2, title: "Wedding at Cana", description: "First sign; water into wine", reference: "John 2:1-11" },
      { order: 3, title: "Nicodemus — born again", description: "\"You must be born again\"", reference: "John 3" },
      { order: 4, title: "Woman at the well", description: "Living water; true worship", reference: "John 4" },
      { order: 5, title: "Feeding of 5000 and Bread of Life", description: "\"I am the bread of life\"", reference: "John 6" },
      { order: 6, title: "Lazarus raised", description: "\"I am the resurrection and the life\"", reference: "John 11" },
      { order: 7, title: "Upper Room discourse", description: "\"I am the way\" — Paraclete promised", reference: "John 13-17" },
      { order: 8, title: "Passion and resurrection", description: "\"It is finished\"; empty tomb; Thomas", reference: "John 18-20" },
      { order: 9, title: "Peter restored", description: "\"Do you love Me? Feed My sheep\"", reference: "John 21" },
    ],
    culturalNotes: [
      { category: "worship", title: "Seven 'I Am' statements", content: "Bread, Light, Door, Shepherd, Resurrection, Way-Truth-Life, Vine — all echo Exodus 3:14." },
      { category: "customs", title: "Seven signs", content: "Cana, official's son, Bethesda, 5000 fed, walking on water, blind man, Lazarus." },
      { category: "social", title: "Logos theology", content: "Greek philosophers used 'logos' for cosmic reason; John says the Logos became flesh." },
      { category: "law", title: "Passover symbolism", content: "John structures his Gospel around three Passovers; Jesus is the true Lamb of God." },
    ],
    didYouKnow: [
      "John 3:16 is the most memorized verse in the Bible.",
      "John's Gospel never mentions Matthew, Mark, or Luke by name.",
      "The word 'believe' (pisteuo) appears 98 times in John — more than any other NT book.",
      "John 11:35 ('Jesus wept') is the shortest verse in the Bible.",
    ],
  },
];
